export default {
   REQUEST_PRODUCT: "REQUEST_PRODUCT",
   REQUEST_PRODUCT_PENDING: "REQUEST_PRODUCT_PENDING",
   REQUEST_PRODUCT_REJECTED: "REQUEST_PRODUCT_REJECTED",
   REQUEST_PRODUCT_FULFILLED: "REQUEST_PRODUCT_FULFILLED",
 
   UPLOAD_PRODUCT_IMAGE: "UPLOAD_PRODUCT_IMAGE",
   UPLOAD_PRODUCT_IMAGE_PENDING: "UPLOAD_PRODUCT_IMAGE_PENDING",
   UPLOAD_PRODUCT_IMAGE_REJECTED: "UPLOAD_PRODUCT_IMAGE_REJECTED",
   UPLOAD_PRODUCT_IMAGE_FULFILLED: "UPLOAD_PRODUCT_IMAGE_FULFILLED",
 
   REQUEST_PRODUCT_LOG: "REQUEST_PRODUCT_LOG",
   REQUEST_PRODUCT_LOG_PENDING: "REQUEST_PRODUCT_LOG_PENDING",
   REQUEST_PRODUCT_LOG_REJECTED: "REQUEST_PRODUCT_LOG_REJECTED",
   REQUEST_PRODUCT_LOG_FULFILLED: "REQUEST_PRODUCT_LOG_FULFILLED",
 
   REQUEST_PRODUCT_ATTRIBUTES: "REQUEST_PRODUCT_ATTRIBUTES",
   REQUEST_PRODUCT_ATTRIBUTES_PENDING: "REQUEST_PRODUCT_ATTRIBUTES_PENDING",
   REQUEST_PRODUCT_ATTRIBUTES_REJECTED: "REQUEST_PRODUCT_ATTRIBUTES_REJECTED",
   REQUEST_PRODUCT_ATTRIBUTES_FULFILLED: "REQUEST_PRODUCT_ATTRIBUTES_FULFILLED",

  REQUEST_VARIANT_ATTRIBUTE: "REQUEST_VARIANT_ATTRIBUTE",
  REQUEST_VARIANT_ATTRIBUTE_PENDING: "REQUEST_VARIANT_ATTRIBUTE_PENDING",
  REQUEST_VARIANT_ATTRIBUTE_REJECTED: "REQUEST_VARIANT_ATTRIBUTE_REJECTED",
  REQUEST_VARIANT_ATTRIBUTE_FULFILLED: "REQUEST_VARIANT_ATTRIBUTE_FULFILLED",
 
   REQUEST_PRODUCT_COST_LOG: "REQUEST_PRODUCT_COST_LOG",
   REQUEST_PRODUCT_COST_LOG_PENDING: "REQUEST_PRODUCT_COST_LOG_PENDING",
   REQUEST_PRODUCT_COST_LOG_REJECTED: "REQUEST_PRODUCT_COST_LOG_REJECTED",
   REQUEST_PRODUCT_COST_LOG_FULFILLED: "REQUEST_PRODUCT_COST_LOG_FULFILLED",
 
   SEARCH_PRODUCT: "SEARCH_PRODUCT",
   SEARCH_PRODUCT_PENDING: "SEARCH_PRODUCT_PENDING",
   SEARCH_PRODUCT_REJECTED: "SEARCH_PRODUCT_REJECTED",
   SEARCH_PRODUCT_FULFILLED: "SEARCH_PRODUCT_FULFILLED",
   SEARCH_PRODUCT_RESET: "SEARCH_PRODUCT_RESET",
   SEARCH_PRODUCT_RESET_PARTIAL: "SEARCH_PRODUCT_RESET_PARTIAL",
   
   ARCHIVE_PRODUCT: "ARCHIVE_PRODUCT",
   ARCHIVE_PRODUCT_PENDING: "ARCHIVE_PRODUCT_PENDING",
   ARCHIVE_PRODUCT_REJECTED: "ARCHIVE_PRODUCT_REJECTED",
   ARCHIVE_PRODUCT_FULFILLED: "ARCHIVE_PRODUCT_FULFILLED",
 
   ARCHIVE_VARIANT_PRODUCT: "ARCHIVE_VARIANT_PRODUCT",
   ARCHIVE_VARIANT_PRODUCT_PENDING: "ARCHIVE_VARIANT_PRODUCT_PENDING",
   ARCHIVE_VARIANT_PRODUCT_REJECTED: "ARCHIVE_VARIANT_PRODUCT_REJECTED",
   ARCHIVE_VARIANT_PRODUCT_FULFILLED: "ARCHIVE_VARIANT_PRODUCT_FULFILLED",
   RESET_ARCHIVE_VARIANT_PRODUCT: "RESET_ARCHIVE_VARIANT_PRODUCT",
   
   ADD_PRODUCT: "ADD_PRODUCT",
   ADD_PRODUCT_PENDING: "ADD_PRODUCT_PENDING",
   ADD_PRODUCT_REJECTED: "ADD_PRODUCT_REJECTED",
   ADD_PRODUCT_FULFILLED: "ADD_PRODUCT_FULFILLED",
 
   CLONE_PRODUCT: "CLONE_PRODUCT",
   CLONE_PRODUCT_PENDING: "CLONE_PRODUCT_PENDING",
   CLONE_PRODUCT_REJECTED: "CLONE_PRODUCT_REJECTED",
   CLONE_PRODUCT_FULFILLED: "CLONE_PRODUCT_FULFILLED",
   
   UPDATE_PRODUCT: "UPDATE_PRODUCT",
   UPDATE_PRODUCT_PENDING: "UPDATE_PRODUCT_PENDING",
   UPDATE_PRODUCT_REJECTED: "UPDATE_PRODUCT_REJECTED",
   UPDATE_PRODUCT_FULFILLED: "UPDATE_PRODUCT_FULFILLED",
 
   UPDATE_PARTIAL_PRODUCT: "UPDATE_PARTIAL_PRODUCT",
   UPDATE_PARTIAL_PRODUCT_PENDING: "UPDATE_PARTIAL_PRODUCT_PENDING",
   UPDATE_PARTIAL_PRODUCT_REJECTED: "UPDATE_PARTIAL_PRODUCT_REJECTED",
   UPDATE_PARTIAL_PRODUCT_FULFILLED: "UPDATE_PARTIAL_PRODUCT_FULFILLED",
 
   DETAIL_PRODUCTS: "DETAIL_PRODUCTS",
   DETAIL_PRODUCTS_PENDING: "DETAIL_PRODUCTS_PENDING",
   DETAIL_PRODUCTS_REJECTED: "DETAIL_PRODUCTS_REJECTED",
   DETAIL_PRODUCTS_FULFILLED: "DETAIL_PRODUCTS_FULFILLED",
   RESET_DETAIL_PRODUCTS: "RESET_DETAIL_PRODUCTS",
   PARTIAL_RESET_DETAIL_PRODUCTS: "PARTIAL_RESET_DETAIL_PRODUCTS",

   SHOW_TAX_FORM: "SHOW_TAX_FORM",
   SHOW_UNIT_FORM: "SHOW_UNIT_FORM",
   SHOW_VARIANT_ATTRIBUTE_FORM: "SHOW_VARIANT_ATTRIBUTE_FORM",
   
   RESET_PRODUCT: "RESET_PRODUCT",
   RESET_PARTIAL_PRODUCT: "RESET_PARTIAL_PRODUCT",
   RESET_FORM_PRODUCT: "RESET_FORM_PRODUCT",
   RESET_VARIANT_ATTRIBUTE: "RESET_VARIANT_ATTRIBUTE",
   SHOW_PRODUCT_FORM: "SHOW_PRODUCT_FORM",
   SHOW_CATEGORY_FORM: "SHOW_CATEGORY_FORM",
   SHOW_BRAND_FORM: "SHOW_BRAND_FORM",

   RESET_ADD_PRODUCT: "RESET_ADD_PRODUCT",
   RESET_REQUEST_VARIANT_ATTRIBUTE: "RESET_REQUEST_VARIANT_ATTRIBUTE",
   RESET_SWITCH_TYPE_OF_GENERATE_SKU: "RESET_SWITCH_TYPE_OF_GENERATE_SKU",
 
   SWITCH_TYPE_OF_GENERATE_SKU: "SWITCH_TYPE_OF_GENERATE_SKU",

   CHECK_PRODUCT_ATTRIBUTE_VALUE: "CHECK_PRODUCT_ATTRIBUTE_VALUE",
   CHECK_PRODUCT_ATTRIBUTE: "CHECK_PRODUCT_ATTRIBUTE",
   CHECK_PRODUCT_VARIANT: "CHECK_PRODUCT_VARIANT",
   RESET_PRODUCT_VARIANT: "RESET_PRODUCT_VARIANT"
 };