export default {
  REQUEST_INVENTORY_REPORT: "REQUEST_INVENTORY_REPORT",
  REQUEST_INVENTORY_REPORT_PENDING: "REQUEST_INVENTORY_REPORT_PENDING",
  REQUEST_INVENTORY_REPORT_REJECTED: "REQUEST_INVENTORY_REPORT_REJECTED",
  REQUEST_INVENTORY_REPORT_FULFILLED: "REQUEST_INVENTORY_REPORT_FULFILLED",
  
  ARCHIVE_INVENTORY_REPORT: "ARCHIVE_INVENTORY_REPORT",
  ARCHIVE_INVENTORY_REPORT_PENDING: "ARCHIVE_INVENTORY_REPORT_PENDING",
  ARCHIVE_INVENTORY_REPORT_REJECTED: "ARCHIVE_INVENTORY_REPORT_REJECTED",
  ARCHIVE_INVENTORY_REPORT_FULFILLED: "ARCHIVE_INVENTORY_REPORT_FULFILLED",
  
  ADD_INVENTORY_REPORT: "ADD_INVENTORY_REPORT",
  ADD_INVENTORY_REPORT_PENDING: "ADD_INVENTORY_REPORT_PENDING",
  ADD_INVENTORY_REPORT_REJECTED: "ADD_INVENTORY_REPORT_REJECTED",
  ADD_INVENTORY_REPORT_FULFILLED: "ADD_INVENTORY_REPORT_FULFILLED",
  
  UPDATE_INVENTORY_REPORT: "UPDATE_INVENTORY_REPORT",
  UPDATE_INVENTORY_REPORT_PENDING: "UPDATE_INVENTORY_REPORT_PENDING",
  UPDATE_INVENTORY_REPORT_REJECTED: "UPDATE_INVENTORY_REPORT_REJECTED",
  UPDATE_INVENTORY_REPORT_FULFILLED: "UPDATE_INVENTORY_REPORT_FULFILLED",
  
  RESET_INVENTORY_REPORT: "RESET_INVENTORY_REPORT",
  SHOW_INVENTORY_REPORT_FORM: "SHOW_INVENTORY_REPORT_FORM"
};