export default {
  REQUEST_INVENTORY_REPORT: "REQUEST_INVENTORY_REPORT",
  REQUEST_INVENTORY_REPORT_PENDING: "REQUEST_INVENTORY_REPORT_PENDING",
  REQUEST_INVENTORY_REPORT_REJECTED: "REQUEST_INVENTORY_REPORT_REJECTED",
  REQUEST_INVENTORY_REPORT_FULFILLED: "REQUEST_INVENTORY_REPORT_FULFILLED",
  
  RESET_INVENTORY_REPORT: "RESET_INVENTORY_REPORT"
};