export default {
  REQUEST_PRODUCT_REPORT: "REQUEST_PRODUCT_REPORT",
  REQUEST_PRODUCT_REPORT_PENDING: "REQUEST_PRODUCT_REPORT_PENDING",
  REQUEST_PRODUCT_REPORT_REJECTED: "REQUEST_PRODUCT_REPORT_REJECTED",
  REQUEST_PRODUCT_REPORT_FULFILLED: "REQUEST_PRODUCT_REPORT_FULFILLED",
  
  RESET_REQUEST_PRODUCT_REPORT: "REQUEST_PRODUCT_REPORT"
};