export default {
  REQUEST_PROFIT_AND_LOST_REPORT: "REQUEST_PROFIT_AND_LOST_REPORT",
  REQUEST_PROFIT_AND_LOST_REPORT_PENDING: "REQUEST_PROFIT_AND_LOST_REPORT_PENDING",
  REQUEST_PROFIT_AND_LOST_REPORT_REJECTED: "REQUEST_PROFIT_AND_LOST_REPORT_REJECTED",
  REQUEST_PROFIT_AND_LOST_REPORT_FULFILLED: "REQUEST_PROFIT_AND_LOST_REPORT_FULFILLED",
  
  RESET_PROFIT_AND_LOST_REPORT: "RESET_PROFIT_AND_LOST_REPORT"
};