export default {
  REQUEST_PROFIT_AND_LOST_REPORT: "REQUEST_PROFIT_AND_LOST_REPORT",
  REQUEST_PROFIT_AND_LOST_REPORT_PENDING: "REQUEST_PROFIT_AND_LOST_REPORT_PENDING",
  REQUEST_PROFIT_AND_LOST_REPORT_REJECTED: "REQUEST_PROFIT_AND_LOST_REPORT_REJECTED",
  REQUEST_PROFIT_AND_LOST_REPORT_FULFILLED: "REQUEST_PROFIT_AND_LOST_REPORT_FULFILLED",
  
  ARCHIVE_PROFIT_AND_LOST_REPORT: "ARCHIVE_PROFIT_AND_LOST_REPORT",
  ARCHIVE_PROFIT_AND_LOST_REPORT_PENDING: "ARCHIVE_PROFIT_AND_LOST_REPORT_PENDING",
  ARCHIVE_PROFIT_AND_LOST_REPORT_REJECTED: "ARCHIVE_PROFIT_AND_LOST_REPORT_REJECTED",
  ARCHIVE_PROFIT_AND_LOST_REPORT_FULFILLED: "ARCHIVE_PROFIT_AND_LOST_REPORT_FULFILLED",
  
  ADD_PROFIT_AND_LOST_REPORT: "ADD_PROFIT_AND_LOST_REPORT",
  ADD_PROFIT_AND_LOST_REPORT_PENDING: "ADD_PROFIT_AND_LOST_REPORT_PENDING",
  ADD_PROFIT_AND_LOST_REPORT_REJECTED: "ADD_PROFIT_AND_LOST_REPORT_REJECTED",
  ADD_PROFIT_AND_LOST_REPORT_FULFILLED: "ADD_PROFIT_AND_LOST_REPORT_FULFILLED",
  
  UPDATE_PROFIT_AND_LOST_REPORT: "UPDATE_PROFIT_AND_LOST_REPORT",
  UPDATE_PROFIT_AND_LOST_REPORT_PENDING: "UPDATE_PROFIT_AND_LOST_REPORT_PENDING",
  UPDATE_PROFIT_AND_LOST_REPORT_REJECTED: "UPDATE_PROFIT_AND_LOST_REPORT_REJECTED",
  UPDATE_PROFIT_AND_LOST_REPORT_FULFILLED: "UPDATE_PROFIT_AND_LOST_REPORT_FULFILLED",
  
  RESET_PROFIT_AND_LOST_REPORT: "RESET_PROFIT_AND_LOST_REPORT",
  SHOW_PROFIT_AND_LOST_REPORT_FORM: "SHOW_PROFIT_AND_LOST_REPORT_FORM"
};