export default {
  REQUEST_PURCHASE_REPORT: "REQUEST_PURCHASE_REPORT",
  REQUEST_PURCHASE_REPORT_PENDING: "REQUEST_PURCHASE_REPORT_PENDING",
  REQUEST_PURCHASE_REPORT_REJECTED: "REQUEST_PURCHASE_REPORT_REJECTED",
  REQUEST_PURCHASE_REPORT_FULFILLED: "REQUEST_PURCHASE_REPORT_FULFILLED",
  
  RESET_PURCHASE_REPORT: "RESET_PURCHASE_REPORT"
};