export default {
  REQUEST_PURCHASE_REPORT: "REQUEST_PURCHASE_REPORT",
  REQUEST_PURCHASE_REPORT_PENDING: "REQUEST_PURCHASE_REPORT_PENDING",
  REQUEST_PURCHASE_REPORT_REJECTED: "REQUEST_PURCHASE_REPORT_REJECTED",
  REQUEST_PURCHASE_REPORT_FULFILLED: "REQUEST_PURCHASE_REPORT_FULFILLED",
  
  ARCHIVE_PURCHASE_REPORT: "ARCHIVE_PURCHASE_REPORT",
  ARCHIVE_PURCHASE_REPORT_PENDING: "ARCHIVE_PURCHASE_REPORT_PENDING",
  ARCHIVE_PURCHASE_REPORT_REJECTED: "ARCHIVE_PURCHASE_REPORT_REJECTED",
  ARCHIVE_PURCHASE_REPORT_FULFILLED: "ARCHIVE_PURCHASE_REPORT_FULFILLED",
  
  ADD_PURCHASE_REPORT: "ADD_PURCHASE_REPORT",
  ADD_PURCHASE_REPORT_PENDING: "ADD_PURCHASE_REPORT_PENDING",
  ADD_PURCHASE_REPORT_REJECTED: "ADD_PURCHASE_REPORT_REJECTED",
  ADD_PURCHASE_REPORT_FULFILLED: "ADD_PURCHASE_REPORT_FULFILLED",
  
  UPDATE_PURCHASE_REPORT: "UPDATE_PURCHASE_REPORT",
  UPDATE_PURCHASE_REPORT_PENDING: "UPDATE_PURCHASE_REPORT_PENDING",
  UPDATE_PURCHASE_REPORT_REJECTED: "UPDATE_PURCHASE_REPORT_REJECTED",
  UPDATE_PURCHASE_REPORT_FULFILLED: "UPDATE_PURCHASE_REPORT_FULFILLED",
  
  RESET_PURCHASE_REPORT: "RESET_PURCHASE_REPORT",
  SHOW_PURCHASE_REPORT_FORM: "SHOW_PURCHASE_REPORT_FORM"
};