export default {
  REQUEST_SALE_REPORT: "REQUEST_SALE_REPORT",
  REQUEST_SALE_REPORT_PENDING: "REQUEST_SALE_REPORT_PENDING",
  REQUEST_SALE_REPORT_REJECTED: "REQUEST_SALE_REPORT_REJECTED",
  REQUEST_SALE_REPORT_FULFILLED: "REQUEST_SALE_REPORT_FULFILLED",
  
  ARCHIVE_SALE_REPORT: "ARCHIVE_SALE_REPORT",
  ARCHIVE_SALE_REPORT_PENDING: "ARCHIVE_SALE_REPORT_PENDING",
  ARCHIVE_SALE_REPORT_REJECTED: "ARCHIVE_SALE_REPORT_REJECTED",
  ARCHIVE_SALE_REPORT_FULFILLED: "ARCHIVE_SALE_REPORT_FULFILLED",
  
  ADD_SALE_REPORT: "ADD_PAYMENT_METHOD",
  ADD_SALE_REPORT_PENDING: "ADD_SALE_REPORT_PENDING",
  ADD_SALE_REPORT_REJECTED: "ADD_SALE_REPORT_REJECTED",
  ADD_SALE_REPORT_FULFILLED: "ADD_SALE_REPORT_FULFILLED",
  
  UPDATE_SALE_REPORT: "UPDATE_SALE_REPORT",
  UPDATE_SALE_REPORT_PENDING: "UPDATE_SALE_REPORT_PENDING",
  UPDATE_SALE_REPORT_REJECTED: "UPDATE_SALE_REPORT_REJECTED",
  UPDATE_SALE_REPORT_FULFILLED: "UPDATE_SALE_REPORT_FULFILLED",
  
  RESET_SALE_REPORT: "RESET_SALE_REPORT",
  SHOW_SALE_REPORT_FORM: "SHOW_SALE_REPORT_FORM"
};