export default {
  REQUEST_SALE_REPORT: "REQUEST_SALE_REPORT",
  REQUEST_SALE_REPORT_PENDING: "REQUEST_SALE_REPORT_PENDING",
  REQUEST_SALE_REPORT_REJECTED: "REQUEST_SALE_REPORT_REJECTED",
  REQUEST_SALE_REPORT_FULFILLED: "REQUEST_SALE_REPORT_FULFILLED",
  
  RESET_SALE_REPORT: "RESET_SALE_REPORT"
};