
export const REQUEST_PAYMENT_METHOD            = "REQUEST_PAYMENT_METHOD";
export const REQUEST_PAYMENT_METHOD_PENDING    = "REQUEST_PAYMENT_METHOD_PENDING";
export const REQUEST_PAYMENT_METHOD_REJECTED   = "REQUEST_PAYMENT_METHOD_REJECTED";
export const REQUEST_PAYMENT_METHOD_FULFILLED  = "REQUEST_PAYMENT_METHOD_FULFILLED";

export const ARCHIVE_PAYMENT_METHOD  		   = "ARCHIVE_PAYMENT_METHOD";
export const ARCHIVE_PAYMENT_METHOD_PENDING    = "ARCHIVE_PAYMENT_METHOD_PENDING";
export const ARCHIVE_PAYMENT_METHOD_REJECTED   = "ARCHIVE_PAYMENT_METHOD_REJECTED";
export const ARCHIVE_PAYMENT_METHOD_FULFILLED  = "ARCHIVE_PAYMENT_METHOD_FULFILLED";