import React from "react";
import {
  isMobile
} from "react-device-detect";
import CKEditor from "@ckeditor/ckeditor5-react";
import ClassicEditor from "@ckeditor/ckeditor5-build-classic";
import {message} from "antd";
import history from "../../../../common/router/history";
import Enum from "../../../enums";
import StoreAccountAction from "../../../action/settings/storeAccount";
import TaxAction from "../../../action/settings/tax";
import LanguageAction from "../../../action/settings/storeLanguage";
import DeviceAction from "../../../action/settings/device";
import StoreAccountService from "../../../services/settings/StoreAccountService";
import {fetchAllBusinessPlanSystem} from "../../../../../modules/common/actions/businessPlan";
import ConstantDevice from "../../../constants/settings/device";
import Component from "../../../../common/components/Component";
import NoPermission from "../../../../common/components/shares/List/NoPermission";
import StartUp from "../../../../common/components/StartUp";
import menuSource from "../../../../common/components/layout/SiderBar/datasource";
import PrivilegeService from "../../../../pos/services/settings/PrivilegeService";
import ProductService from "../../../../inventory/services/products/ProductService";
import TransactionService from "../../../services/transactions/TransactionService";
import PrivilegeAction from "../../../../pos/action/settings/privilege";
import {modules} from "../../../../common/components/layout/Module";
import "./index.css";

const currentPath = window.location.pathname;

export default class StoreAccountList extends Component {
  constructor(props) {
    super(props);
    this.state = {
      classChange: "unhide",
      getstoreaccid: "",
      selectedModules: [
        {id: 1, route: "transactions", status: 1},
        {id: 2, route: "/transactions/sales", status: 1},
        {id: 3, route: "/pos", status: 1},
        {id: 3, route: "/transactions/saleregister", status: 1}
      ],
      paymentTerm: "",
      address: "",
      deviceList: [],
      isClearProduct: false,
      isClearTransaction: false,
      activeTap: 1
    };
    this.module = <this.Translate id="text_setting" />;
    
    // ERROR CURRENT PASSWORD
    this.errorMessageCurrentPWD = "";
    this.validateClassStatusCurrentPWD = "";
    this.isResetInputCurrentPWD = false;
    this.exampleDateFormat= "";
    this.renewButtonIndex = null;
    this.dispatch = this.props.dispatch;

    this.successMessage = "Success updated.";

    this.client = JSON.parse(localStorage.getItem(["ACCESS_TOKEN"]));

    this.autoGenerateDataSource = [
      {
        name: <this.Translate id="text_auto" />,
        value: this.Enum.GENERATE_PRODUCT_CODE.AUTO
      },
      {
        name: <this.Translate id="text_manaul" />,
        value: this.Enum.GENERATE_PRODUCT_CODE.MANAUL
      }
    ];

    this.paymentTypes = [
      {
        title: <this.Translate id="store_acc_pay_as_your_business_growth" />,
        value: 0
      },
      {
        title: <this.Translate id="store_acc_pay_your_5_stores_package" />,
        value: 1
      },
      {
        title: <this.Translate id="store_acc_pay_your_10_stores_package" />,
        value: 2,
      },
      {
        title: <this.Translate id="store_acc_pay_your_15_stores_package" />,
        value: 3
      }
    ];

    this.currencyPositions = [
      {
        name: <this.Translate id="text_before" />,
        value: this.Enum.CURRENCY_POSITION.BEFORE
      },
      {
        name: <this.Translate id="text_after" />,
        value: this.Enum.CURRENCY_POSITION.AFTER
      }
    ];

    this.customerCreditStatus = [
      {
        name: <this.Translate id="text_enable" />,
        value: Enum.CUSTOMER_CREDIT_STATUS.ENABLE
      },
      {
        name: <this.Translate id="text_disable" />,
        value: Enum.CUSTOMER_CREDIT_STATUS.DISABLE
      }
    ];

    this.hasUpdated = false;

    this.handleOnReNewDeviceNumber = this.handleOnReNewDeviceNumber.bind(this);
    this.handleOnCopyDeviceNumber = this.handleOnCopyDeviceNumber.bind(this);
    this.onChangeOnCheckModule = this.onChangeOnCheckModule.bind(this);
    this.handleSubmit = this.handleSubmit.bind(this);
    this.onChange = this.onChange.bind(this);
    this.onSelect = this.onSelect.bind(this);
    this.handleChangeDateFormat = this.handleChangeDateFormat.bind(this);

  }

  componentDidMount(){
    this.dispatch(PrivilegeAction.checkPermission(StoreAccountService.updateRoute));
    this.dispatch(StoreAccountAction.fetch(this.client.clientId));
    this.dispatch(fetchAllBusinessPlanSystem());
    this.dispatch(TaxAction.fetch(100));
    this.dispatch(LanguageAction.fetch(100));
    this.dispatch(DeviceAction.fetch(100));
    this.onSelect();
  }

  componentDidUpdate() {
    if (this.props.renew.updated) {
      if (this.props.renew.response && this.props.renew.response.data) {
        const deviceList = this.state.deviceList.find(device => device.id === this.props.renew.response.data.id);
        deviceList["status"] = this.props.renew.response.data.status;
        deviceList["code"] = this.props.renew.response.data.code;
      }

      this.Message.success(this.CATranslate("text_new_device_success", this.props.locale));

      this.dispatch(DeviceAction.reset(ConstantDevice.RESET_RENEW_DEVICE));
    }

    if (!this.hasUpdated && this.props.devices.fetched) {
      this.setState({deviceList: this.props.devices.list});
      this.hasUpdated = true;
    }
  }

  componentWillUnmount() {
    this.hasUpdated = false;
  }

  handleSubmit(e){
    e.preventDefault();
    PrivilegeService.checkPermission(StoreAccountService.updateRoute)
      .then(response => {
        this.props.form.validateFieldsAndScroll((err, values) => {
          if (!err) {
            values["id"] = this.client.clientId;
            values["userId"] = this.client.userId;
            values["logo"] = this.getImageFromUpload(values, "logo");
            values["paymentTerm"] = this.state.paymentTerm;
            values["address"] = this.state.address;
            values["status"] = this.Enum.ACTIVE;
            this.dispatch(StoreAccountAction.update(values));
          }
        });
      })
      .catch(error => {
        this.Message.warning(this.CATranslate("text_no_permission", this.props.locale));
      });
  }

  onClearProduct = () => {
    this.Util.sweetAlertConfirm(
      this.CATranslate("text_are_you_sure", this.props.locale),
      "",
      [this.CATranslate("text_cancel", this.props.locale), this.CATranslate("text_yes", this.props.locale)]
    )
    .then(willClear => {
      if (willClear) {
        this.setState({isClearProduct: true});
        ProductService.clear()
        .then(() => {
          message.success("sucess");
        })
        .catch(() => {
          message.error("Error");
        })
        .finally(() => this.setState({isClearProduct: false}));
      }
    });
  }

  onClearTransaction = () => {
    this.Util.sweetAlertConfirm(
      this.CATranslate("text_are_you_sure", this.props.locale),
      "",
      [this.CATranslate("text_cancel", this.props.locale), this.CATranslate("text_yes", this.props.locale)]
    )
    .then(willClear => {
      if (willClear) {
        this.setState({isClearTransaction: true});
        TransactionService.clear()
        .then(() => {
          message.success("Success");
        })
        .catch(() => {
          message.error("Error");
        })
        .finally(() => this.setState({isClearTransaction: false}));
      }
    });
  }

  handleOnCopyDeviceNumber(id, status) {
    if (status !== this.Enum.ACTIVE) {
      this.Message.warning(this.CATranslate("text_not_available", this.props.locale));
      return;
    }
    const div = document.getElementById(id);
    const el = document.createElement("textarea");
    el.value = div.innerHTML;
    document.body.appendChild(el);
    el.select();
    document.execCommand("copy");
    document.body.removeChild(el);
    this.Message.success(this.CATranslate("text_copy", this.props.locale));
  }

  handleOnReNewDeviceNumber(id, index) {
    this.renewButtonIndex = index;
    this.dispatch(DeviceAction.renew(id));
  }

  handleChangeDateFormat(value) {
    this.exampleDateFormat= "Ex: " + this.Util.formatDate("2018-08-04", value);
  }

  onChangeOnCheckModule(e, moduleObj, moduleKey) {
    let selectedModules = this.state.selectedModules;
    const modulesArr = Object.keys(modules).map(key => modules[key]);

    if (e.target.checked) {
      const resultFindIndex = selectedModules.findIndex(value => value.route === moduleObj.route);
      if (resultFindIndex >= 0) {
        selectedModules[resultFindIndex]["status"] = this.Enum.ACTIVE;

        // MAKE AUTO CHECK FOR SUB MODULES
        if (!moduleObj.parent) {
          const subModules = modulesArr.filter(value => value.parent === moduleKey);
          
          subModules.forEach(value => {
            //CHECK EXIST OR NOT
            const subModuleFindIndex = selectedModules.findIndex(selectedModule => selectedModule.route === value.route);
            if (subModuleFindIndex >= 0) {
              selectedModules[subModuleFindIndex]["status"] = this.Enum.ACTIVE;
            }
          });
        }
      } else {
        selectedModules.push({
          route: moduleObj.route,
          status: this.Enum.ACTIVE
        });

        // MAKE AUTO CHECK FOR SUB MODULES
        if (!moduleObj.parent) {
          const subModules = modulesArr.filter(value => value.parent === moduleKey);
          subModules.forEach(value => {
            //CHECK EXIST OR NOT
            const subModuleFindIndex = selectedModules.findIndex(selectedModule => selectedModule.route === value.route);
            if (subModuleFindIndex === -1) {
              selectedModules.push({
                route: value.route,
                status: this.Enum.ACTIVE
              });
            }
          });
        }
      }
    } else {
      let tempSelectedModules = [];
      selectedModules.forEach(value => {
        if (value.id && moduleObj.route === value.route) {
          value["status"] = this.Enum.ARCHIVE;
          tempSelectedModules.push(value);
        } else if (value.route !== moduleObj.route) {
          tempSelectedModules.push(value);
        }
      });

      selectedModules = tempSelectedModules;
      tempSelectedModules = [];

      if (!moduleObj.parent) {
        const subModules = modulesArr.filter(value => value.parent === moduleKey).map(value => value.route);

        selectedModules.forEach(value => {
          if (value.id && subModules.includes(value.route)) {
            value["status"] = this.Enum.ARCHIVE;
            tempSelectedModules.push(value);
          } else if (!subModules.includes(value.route)) {
            tempSelectedModules.push(value);
          }
        });

        console.log("TempSelectedModules:", tempSelectedModules);
        selectedModules = tempSelectedModules;
      }
    }

    console.log("SelectedModules:", selectedModules);

    this.setState({selectedModules});
  }

  onSelect(value){
    this.setState({
      classChange: value === this.props.storeAccount.businessPlanId ? "unhide" : "hide"
    });
  }

  onChange(value){
    this.setState({
      classChange: value === this.props.storeAccount.businessPlanId ? "unhide" : "hide"
    });
  }

  onChangeTab = (key) => {
    this.setState({activeTap: parseInt(key)});
  }

  renderMiniBreadCrumb() {
    // get current path of breadcrum compare with url
    const currentPath = window.location.pathname;
    return (
      <div className="breadcrumb">
        <ul className="list-unstyled">
          <li>
            <this.Link to="/"><span className="icon-home"></span></this.Link>
          </li>
          {
            menuSource[this.module]["subItems"].map((value, index) =>
              currentPath === value["route"] ? 
                <li className="fast-nav text-uppercase" key={index}>
                  <this.Link to={value["route"]}>{value["title"]}</this.Link>
                </li>
                :
                ""
            )
          }
        </ul>
      </div>
    );
  }
  
  render() {
    const {
      form,
      storeAccount,
      storeAccountUpdate,
      response,
      businessplan,
      taxs,
      locale
    } = this.props;

    if(response.updated === true){
      this.Message.success(this.successMessage);
      this.Util.logout(history);
      this.dispatch(StoreAccountAction.reset());
    }

    // HANDLE ERROR BACK FROM SERVER
    if (storeAccountUpdate.error != null) {

      const {error} = storeAccountUpdate;

      if ("error" in error 
      && error.data["error"] != null
      ) {
        if (error.data["error"].code === this.HttpCode.CURRENT_PASSWORD_NOT_MATCH) {
          this.errorMessageCurrentPWD = <this.Translate id="store_acc_error_current_pwd_not_match" />;
        }
      }

      this.validateClassStatusCurrentPWD = "error";

      this.dispatch(StoreAccountAction.reset());
    }

    const currency = storeAccount.list.currency != null ? [storeAccount.list.currency] : [];
    
    let image = {};
    if (storeAccount.fetched) {
      image = {
        uid: "-1",
        name: storeAccount.list.logo,
        status: "done",
        url: this.Util.getProductImage(storeAccount.list.logo, this.Enum.IMAGE_SPACE.GENERAL).url
      };
    }

    return <div style={{width: "100%"}}>
        {
          isMobile ?
            this.renderMiniBreadCrumb()
            :
            <div className="breadcrumb">
              <ul className="list-unstyled">
                <li>
                  <this.Link to="/"><span className="icon-home"></span></this.Link>
                </li>
                <li className="fast-nav text-uppercase">
                  <this.Link to="/">{this.module}</this.Link>
                </li>
                {
                  menuSource["settings"]["subItems"].map((value, index) =>
                    "isFashNav" in value && value["isFashNav"] ?
                      <li className={(currentPath===value["route"] ? "active" : "") + " fast-nav"} key={index}>
                        <this.Link to={value["route"]}>{value["title"]}</this.Link>
                      </li>
                      :
                      ""
                  )
                }
              </ul>
            </div>
        }
        {
          this.Util.isCheckingPermission(this.props) || storeAccount.fetching ?
            <StartUp />
            :
            this.Util.isNoPermissionProp(this.props) ?
              <NoPermission />
              :
              
              <div className="main-layout main-store-account">
                <this.Form onSubmit={this.handleSubmit}>
                  <this.Row>
                    <this.Col md="12"> 
                      <this.Tabs type="card" onChange={this.onChangeTab}>
                        <this.TabPane tab={<this.Translate id="text_general" />} key="1">
                          <this.Row>
                            <this.Col lg="4" md="4"> 
                              <this.InputText
                                name="businessNamekm"
                                data={storeAccount.list.businessNamekm}
                                label={<this.Translate id="store_acc_business_name_km" />}
                                placeholder={this.CATranslate("store_acc_business_name_km", locale)}
                                isAutoFocus={true}
                                required={true}
                                form={form} />
                              <this.InputText
                                name="businessName"
                                data={storeAccount.list.businessName}
                                label={<this.Translate id="store_acc_business_name" />}
                                placeholder={this.CATranslate("store_acc_business_name", locale)}
                                form={form}
                                isAutoFocus={true}
                                required/>
                              <this.UploadImg 
                                name="logo" 
                                label={<this.Translate id="text_logo" />}
                                data={{file: image}}
                                fileList={[image]}
                                endPoint={`${this.Util.getAPIURL()}/file/v1/upload/general`}
                                endPointDelete={`${this.Util.getAPIURL()}/file/v1/general/delete`}
                                accessToken={this.Util.getAccessToken()}
                                form={form} />
                              <this.InputText
                                name="storeName"
                                data={storeAccount.list.storeName}
                                label={<this.Translate id="store_acc_store_name" />}
                                notation=".storevein.com"
                                placeholder={this.CATranslate("store_acc_store_name", locale)}
                                form={form}
                                disabled/>
                  
                              {/* <this.InputText
                                name="countryId"
                                data={storeAccount.list.country != null ? storeAccount.list.country.name : ""}
                                label={<this.Translate id="text_country" />}
                                placeholder={this.CATranslate("text_country", locale)}
                                disabled
                                form={form}/> */}

                              <this.Select
                                name="languageId"
                                dataSource={this.props.languages}
                                defaultValue={storeAccount.list.languageId}
                                valueKey="id"
                                label={<this.Translate id="text_language" />}
                                placeholder={this.CATranslate("text_language", locale)}
                                form={form} />

                              <this.Select
                                name="currencyId"
                                dataSource={currency}
                                defaultValue={storeAccount.list.currencyId}
                                valueKey="id"
                                label={<this.Translate id="text_currency" />}
                                placeholder={this.CATranslate("text_currency", locale)}
                                form={form} disabled />

                              <this.Select
                                name="currencyPosition"
                                dataSource={this.currencyPositions}
                                defaultValue={storeAccount.list.currencyPosition}
                                label={<this.Translate id="text_currency_position" />}
                                placeholder={this.CATranslate("text_currency_position", locale)}
                                form={form} />

                              <this.Select
                                name="taxId"
                                dataSource={taxs}
                                defaultValue={storeAccount.list.taxId}
                                valueKey="id"
                                label={<this.Translate id="text_default_tax" />}
                                placeholder={this.CATranslate("text_default_tax", locale)}
                                form={form} />

                              <this.InputText
                                name="VATNo"
                                data={storeAccount.list.VATNo}
                                label={<this.Translate id="text_vat_no" />}
                                placeholder={this.CATranslate("text_vat_no", locale)}
                                form={form} />

                              <this.Select
                                name="isAllowCustomerCredit"
                                dataSource={this.customerCreditStatus}
                                defaultValue={storeAccount.list.isAllowCustomerCredit}
                                label={<this.Translate id="text_allow_customer_credit" />}
                                placeholder={this.CATranslate("text_allow_customer_credit", locale)}
                                form={form} />

                              {/* <this.InputText
                                name="paymentTerm"
                                data={storeAccount.list.paymentTerm}
                                label={<this.Translate id="text_payment_term" />}
                                placeholder={this.CATranslate("text_payment_term", locale)}
                                form={form} /> */}

                              <div>
                                <div className="ant-form-item-label">
                                  <label htmlFor="paymentTerm"><this.Translate id="text_payment_term" /></label>
                                </div>
                                <div style={{ marginTop: 5 }}>
                                  <CKEditor
                                    editor={ClassicEditor}
                                    data={storeAccount.list.paymentTerm ? storeAccount.list.paymentTerm : "<p></p>"}
                                    onInit={paymentTerm => {
                                      // You can store the "editor" and use when it is needed.
                                      // console.log('Editor is ready to use!', paymentTerm.data);
                                      // this.setState({ paymentTerm: paymentTerm.data });
                                    }}
                                    onChange={(event, editor) => {
                                      const data = editor.getData();
                                      // console.log({ event, editor, data });
                                      this.setState({ paymentTerm: data });
                                    }}
                                    onBlur={(event, editor) => {
                                      // console.log('Blur.', editor);
                                    }}
                                    onFocus={(event, editor) => {
                                      // console.log('Focus.', editor);
                                    }}
                                  />
                                </div>
                              </div>

                              <this.Select
                                name="dateFormat"
                                dataSource={this.Util.listFormatDate()}
                                defaultValue={storeAccount.list.dateFormat}
                                help={`${this.exampleDateFormat}`}
                                onChange={this.handleChangeDateFormat}
                                label={<this.Translate id="store_acc_date_format" />}
                                placeholder={this.CATranslate("store_acc_date_format", locale)}
                                form={form} />

                              <this.Select
                                name="productGenerateCodeType"
                                defaultValue={storeAccount.list.productGenerateCodeType}
                                dataSource={this.autoGenerateDataSource}
                                label={<this.Translate id="text_auto_generate_pcode" />}
                                placeholder={this.CATranslate("text_auto_generate_pcode", locale)}
                                form={form} />

                              <this.InputNumber
                                name="productCodeSequenceStart"
                                label={<this.Translate id="text_start_sequence_code" />}
                                placeholder={this.CATranslate("text_start_sequence_code", locale)}
                                data={storeAccount.list.productCodeSequenceStart}
                                max={9999999999}
                                errorLength={<this.Translate id="store_acc_error_sequence_start_no" />}
                                form={form} />
                            </this.Col>
                          </this.Row>
                        </this.TabPane>
                        <this.TabPane tab={<this.Translate id="text_account" />} key="2">
                          <this.Row>
                            <this.Col lg="4" md="4">
                              <this.InputText
                                data={storeAccount.list.users && storeAccount.list.users.length > 0 ? storeAccount.list.users[0]["userName"] : ""}
                                name="userName"
                                label={<this.Translate id="text_user_name" />}
                                disabled={true}
                                form={form}/>

                              <this.InputPassword
                                // CURRENT PWD
                                currentPWDName="currentPassword"
                                currentPWDLabel={<this.Translate id="text_current_password" />}
                                currentPWDPlaceholder={this.CATranslate("text_current_password", locale)}
                    
                                // PWD
                                label={<this.Translate id="text_new_password" />}
                                placeholder={this.CATranslate("text_new_password", locale)}
                    
                                // CONFIRM PWD
                                confirmLabel={<this.Translate id="text_confirm_password" />}
                                confirmPlaceholder={this.CATranslate("text_confirm_password", locale)}

                                messageIsMatchPassword={<this.Translate id="store_acc_error_confirm_pwd_not_match" />}
                                required={false}
                                requiredCurrentPWD={true}
                                errorRequired={<this.Translate id="store_acc_error_pwd_required" />}
                                errorRequiredConfirm={<this.Translate id="store_acc_error_confirm_pwd_required" />}
                                errorMessageCurrentPWD={this.errorMessageCurrentPWD}
                                validateClassStatusCurrentPWD={this.validateClassStatusCurrentPWD}
                                form={form} />
                            </this.Col>
                          </this.Row>
                        </this.TabPane>
                        <this.TabPane tab={<this.Translate id="text_contact" />} key="3">
                          <this.Row>
                            <this.Col lg="4" md="4"> 
                              <this.InputText
                                data={storeAccount.list.firstName}
                                name="firstName"
                                label={<this.Translate id="text_first_name" />}
                                placeholder={this.CATranslate("text_first_name", locale)}
                                form={form}/>
                           
                              <this.InputText
                                data={storeAccount.list.lastName}
                                name="lastName"
                                label={<this.Translate id="text_last_name" />}
                                placeholder={this.CATranslate("text_last_name", locale)}
                                form={form}/>
                           
                              <this.InputEmail
                                data={storeAccount.list.email}
                                name="email"
                                label={<this.Translate id="text_email" />}
                                placeholder={this.CATranslate("text_email", locale)}
                                form={form}/>
                           
                              <this.InputText
                                data={storeAccount.list.phoneNumber}
                                name="phoneNumber"
                                label={<this.Translate id="text_phone_number" />}
                                placeholder={this.CATranslate("text_phone_number", locale)}
                                form={form} />
                            
                              {/* <this.InputText
                                data={storeAccount.list.address}
                                name="address"
                                label={<this.Translate id="text_address" />}
                                placeholder={this.CATranslate("text_address", locale)}
                                form={form}/> */}
                              
                              <div>
                                <div className="ant-form-item-label">
                                  <label htmlFor="address"><this.Translate id="text_address" /></label>
                                </div>
                                <div style={{ marginTop: 5 }}>
                                  <CKEditor
                                    editor={ClassicEditor}
                                    data={storeAccount.list.address ? storeAccount.list.address : "<p></p>"}
                                    onChange={(event, editor) => {
                                      this.setState({ address: editor.getData() });
                                    }}
                                  />
                                </div>
                              </div>
                          
                              <this.InputText
                                data={storeAccount.list.street}
                                name="street"
                                label={<this.Translate id="text_street" />}
                                placeholder={this.CATranslate("text_street", locale)}
                                form={form}/>
                            
                              <this.InputText
                                data={storeAccount.list.city}
                                name="city"
                                label={<this.Translate id="text_city" />}
                                placeholder={this.CATranslate("text_city", locale)}
                                form={form}/>
                          
                              <this.InputText
                                data={storeAccount.list.postCode}
                                name="postCode"
                                label={<this.Translate id="text_post_code" />}
                                placeholder={this.CATranslate("text_post_code", locale)}
                                form={form} />
                            </this.Col>
                          </this.Row>
                        </this.TabPane>
                        {/* <this.TabPane tab={<this.Translate id="text_module" />} key="4">
                          <this.Row>
                            <this.Col lg="4" md="4" style={{paddingBottom: 15}}> 
                              {
                                Object.keys(modules).map((key, index) => 
                                  <div key={index} className={`module ${modules[key].parent ? "sub-module" : ""}`}>
                                    <this.Checkbox
                                      value={{id: modules[key].id, name: modules[key].route, parent: modules[key].parent}}
                                      checked={this.state.selectedModules.findIndex(value => value.route === modules[key].route && value.status === this.Enum.ACTIVE) >= 0}
                                      onChange={(e) => this.onChangeOnCheckModule(e, modules[key], key)}>
                                      {modules[key].title}
                                    </this.Checkbox>
                                  </div>
                                )
                              }
                            </this.Col> 
                          </this.Row>
                        </this.TabPane> */}
                        <this.TabPane tab={<this.Translate id="text_device" />} key="5">
                          <this.Row>
                            <this.Col lg="5" md="5" style={{marginBottom: 20}}> 
                              <this.InputNumber
                                data={storeAccount.list.numberOfDevice}
                                name="deviceNumber"
                                precision={0}
                                label={<this.Translate id="number_of_device" />}
                                placeholder={this.CATranslate("number_of_device", locale)}
                                disabled={true}
                                form={form} />
                              <this.Table 
                                dataSource={this.state.deviceList}
                                columns={[
                                  {
                                    title: <this.Translate id="text_name" />,
                                    dataIndex: "name",
                                    key: "name",
                                    width: 180
                                  },
                                  {
                                    title: <this.Translate id="text_number" />,
                                    dataIndex: "code",
                                    key: "code",
                                    render: (text, record, index) => {
                                      return <div id={`device-${index}`}>{record.code}</div>;
                                    }
                                  },
                                  {
                                    title: <this.Translate id="text_status" />,
                                    dataIndex: "status",
                                    key: "status",
                                    width: 130,
                                    render: status => {
                                      return (
                                        status === this.Enum.ACTIVE ?
                                          <this.Badge text={<this.Translate id="text_available" />} status="success" />
                                          :
                                          <this.Badge text={<this.Translate id="text_not_available"/>} status="error" />
                                      );
                                    }
                                  },
                                  {
                                    title: <this.Translate id="text_action" />,
                                    key: "action",
                                    width: 100,
                                    render: (text, record, index) => {
                                      return <div className="btn-action-device">{(record.status === this.Enum.ACTIVE ?
                                        <this.Button style={{width: 70}} type="info" onClick={() => this.handleOnCopyDeviceNumber(`device-${index}`, record.status)}>{<this.Translate id="copy_device_number"/>}</this.Button>
                                        :
                                        <this.Button style={{width: 70}} loading={this.props.renew.updating && this.renewButtonIndex === index} type="info" onClick={() => this.handleOnReNewDeviceNumber(record.id, index)}>{<this.Translate id="text_renew"/>}</this.Button>)
                                      }</div>;
                                    }
                                  }
                                ]}
                                locale={{emptyText: <this.Translate id="table_empty_data"/>}}
                                loading={false} />
                            </this.Col> 
                          </this.Row>
                        </this.TabPane>
                        <this.TabPane tab={<this.Translate id="text_billing" />} key="6">
                          <this.Row>
                            <this.Col lg="4" md="4"> 
                              <this.DatePickers
                                name="registerDate"
                                defaultValue={this.Util.formatDatePicker(storeAccount.list.registerDate)}
                                label={<this.Translate id="text_register_date" />}
                                placeholder={this.CATranslate("text_register_date", locale)}
                                form={form}
                                disabled />
                              {
                                storeAccount.list.expiredDate !== null && storeAccount.list.expiredDate !== "undefined"
                                  ?
                                  <this.DatePickers
                                    name="expiredDate"
                                    defaultValue={this.Util.formatDatePicker(storeAccount.list.expiredDate)}
                                    label={<this.Translate id="text_expired_date" />}
                                    placeholder={this.CATranslate("text_expired_date", locale)}
                                    form={form}
                                    disabled />
                                  :
                                  ""
                              }

                              <div className="general">
                                <h6><this.Translate id="text_plan" /></h6>
                              </div>

                              <this.FormGroup>
                                <this.RadioBox 
                                  className="main-radio-acc"
                                  label=" "
                                  name="businessPlanId" 
                                  type="radio"
                                  defaultValue={storeAccount.list.businessPlanId}
                                  form={form}
                                  disabled={true}
                                  onSelect={this.onSelect}
                                  onChange={this.onChange}>
                                  { businessplan.map( (businessplan, key) => 
                                    <this.RadioChildBox
                                      key={key}
                                      title={businessplan.name}
                                      language={businessplan.description}
                                      value={businessplan.id} /> 
                                  ) 
                                  }
                                </this.RadioBox> 
                              </this.FormGroup>
                          
                              <this.RadioButton 
                                name="paymentType"
                                defaultValue={storeAccount.list.paymentType}
                                dataSource={this.paymentTypes}
                                form={form}
                                disabled={true}
                                required/>

                            </this.Col> 
                          </this.Row>
                        </this.TabPane>
                        <this.TabPane tab={<this.Translate id="text_data" />} key="7">
                          <div style={{marginTop: 30, marginBottom: 35}}>
                            <this.Button type="danger" style={{marginRight: 15}} loading={this.state.isClearProduct} onClick={this.onClearProduct}>
                              <this.Icon type="delete" className="icon-padding-right" /> 
                              <this.Translate id="text_clear_product" />
                            </this.Button>
                            <this.Button type="danger" loading={this.state.isClearTransaction} onClick={this.onClearTransaction}>
                              <this.Icon type="delete" className="icon-padding-right" /> 
                              <this.Translate id="text_clear_other" />
                            </this.Button>
                          </div>
                        </this.TabPane>
                      </this.Tabs>
                      
                    </this.Col> 
                              
                  </this.Row>
                  {
                    this.state.activeTap !== 7 && (
                      <this.Button type="info" htmlType="submit" loading={storeAccountUpdate.updating}>
                        <span className="icon-save icon-padding-right"></span><this.Translate id="text_save" />
                      </this.Button>
                    )
                  }
                </this.Form>
              </div>
        }
      </div>;
  }
}