import React from "react";
import history from "../../../../common/router/history";
import StoreAccountAction from "../../../action/settings/storeAccount";
import TaxAction from "../../../action/settings/tax";
import LanguageAction from "../../../action/settings/storeLanguage";
import DeviceAction from "../../../action/settings/device";
import StoreAccountService from "../../../services/settings/StoreAccountService";
import {fetchAllBusinessPlanSystem} from "../../../../../modules/common/actions/businessPlan";
import ConstantDevice from "../../../constants/settings/device";
import Component from "../../../../common/components/Component";
import NoPermission from "../../../../common/components/shares/List/NoPermission";
import StartUp from "../../../../common/components/StartUp";
import menuSource from "../../../../common/components/layout/SiderBar/datasource";
import PrivilegeService from "../../../../pos/services/settings/PrivilegeService";
import PrivilegeAction from "../../../../pos/action/settings/privilege";
import "./index.css";

const currentPath = window.location.pathname;

export default class StoreAccountList extends Component {
  constructor(props) {
    super(props);
    this.state = {
      classChange: "unhide",
      getstoreaccid: "",
    };
    
    // ERROR CURRENT PASSWORD
    this.errorMessageCurrentPWD = "";
    this.validateClassStatusCurrentPWD = "";
    this.isResetInputCurrentPWD = false;
    this.exampleDateFormat= "";
    this.renewButtonIndex = null;
    this.dispatch = this.props.dispatch;

    this.successMessage = "Success updated.";

    this.client = JSON.parse(localStorage.getItem(["ACCESS_TOKEN"]));

    this.autoGenerateDataSource = [
      {
        name: <this.Translate id="store_acc_type_of_generate_code_auto" />,
        value: this.Enum.GENERATE_PRODUCT_CODE.AUTO
      },
      {
        name: <this.Translate id="store_acc_type_of_generate_code_manual" />,
        value: this.Enum.GENERATE_PRODUCT_CODE.MANAUL
      }
    ];

    this.paymentTypes = [
      {
        title: <this.Translate id="store_acc_pay_as_your_business_growth" />,
        value: 0
      },
      {
        title: <this.Translate id="store_acc_pay_your_5_stores_package" />,
        value: 1
      },
      {
        title: <this.Translate id="store_acc_pay_your_10_stores_package" />,
        value: 2,
      },
      {
        title: <this.Translate id="store_acc_pay_your_15_stores_package" />,
        value: 3
      }
    ];

    this.currencyPositions = [
      {
        name: <this.Translate id="store_acc_currency_position_before" />,
        value: this.Enum.CURRENCY_POSITION.BEFORE
      },
      {
        name: <this.Translate id="store_acc_currency_position_after" />,
        value: this.Enum.CURRENCY_POSITION.AFTER
      }
    ];

    this.handleOnReNewDeviceNumber = this.handleOnReNewDeviceNumber.bind(this);
    this.handleOnCopyDeviceNumber = this.handleOnCopyDeviceNumber.bind(this);
    this.handleSubmit = this.handleSubmit.bind(this);
    this.onChange = this.onChange.bind(this);
    this.onSelect = this.onSelect.bind(this);
    this.handleChangeDateFormat = this.handleChangeDateFormat.bind(this);

  }

  componentDidMount(){
    this.dispatch(PrivilegeAction.checkPermission(StoreAccountService.detailRoute));
    this.dispatch(StoreAccountAction.fetch(this.client.clientId));  
    this.dispatch(fetchAllBusinessPlanSystem());
    this.dispatch(TaxAction.fetch(100));
    this.dispatch(LanguageAction.fetch(100));
    this.dispatch(DeviceAction.fetch(100));
    this.onSelect();
  }

  componentDidUpdate() {
    if (this.props.renew.updated) {
      this.dispatch(DeviceAction.reset(ConstantDevice.RESET_RENEW_DEVICE));
      window.location.reload();
    }
  }

  handleSubmit(e){
    e.preventDefault();
    PrivilegeService.checkPermission(StoreAccountService.updateRoute)
      .then(response => {
        this.props.form.validateFieldsAndScroll((err, values) => {
          if (!err) {
            values["id"] = this.client.clientId;
            values["userId"] = this.client.userId;
            values["logo"] = this.getImageFromUpload(values, "logo");
            values["status"] = this.Enum.ACTIVE;
            this.dispatch(StoreAccountAction.update(values));
          }
        });
      })
      .catch(error => {
        this.Message.warning(this.CATranslate("text_no_permission", this.props.locale));
      });
  }

  handleOnCopyDeviceNumber(id, status) {
    if (status !== this.Enum.ACTIVE) {
      this.Message.warning(this.CATranslate("text_not_available", this.props.locale));
      return;
    }
    const div = document.getElementById(id);
    const el = document.createElement("textarea");
    el.value = div.innerHTML;
    document.body.appendChild(el);
    el.select();
    document.execCommand("copy");
    document.body.removeChild(el);
    this.Message.success(this.CATranslate("text_copy", this.props.locale));
  }

  handleOnReNewDeviceNumber(id, index) {
    this.renewButtonIndex = index;
    this.dispatch(DeviceAction.renew(id));
  }

  handleChangeDateFormat(value) {
    this.exampleDateFormat= "Ex: " + this.Util.formatDate("2018-08-04", value);
  }

  onSelect(value){
    this.setState({
      classChange: value === this.props.storeAccount.businessPlanId ? "unhide" : "hide"
    });
  }

  onChange(value){
    this.setState({
      classChange: value === this.props.storeAccount.businessPlanId ? "unhide" : "hide"
    });
  }
  
  render() {
    const {
      form,
      storeAccount,
      storeAccountUpdate,
      response,
      businessplan,
      taxs,
      locale
    } = this.props;

    if(response.updated === true){
      this.Message.success(this.successMessage);
      this.Util.logout(history);
      this.dispatch(StoreAccountAction.reset());
    }

    // HANDLE ERROR BACK FROM SERVER
    if (storeAccountUpdate.error != null) {

      const {error} = storeAccountUpdate;

      if ("error" in error 
      && error["error"] != null
      ) {
        if (error["error"].code === this.HttpCode.CURRENT_PASSWORD_NOT_MATCH) {
          this.errorMessageCurrentPWD = <this.Translate id="store_acc_error_current_pwd_not_match" />;
        }
      }

      this.validateClassStatusCurrentPWD = "error";

      this.dispatch(StoreAccountAction.reset());
    }

    const currency = storeAccount.list.currency != null ? [storeAccount.list.currency] : [];
    
    let image = {};
    if (storeAccount.list) {
      image = {
        uid: "-1",
        name: storeAccount.list.logo,
        status: "done",
        url: this.Util.getProductImage(storeAccount.list.logo, this.Enum.IMAGE_SPACE.GENERAL).url
      };
    }

    return (
      <div style={{width: "100%"}}>
        <div className="breadcrumb">
          <ul className="list-unstyled">
            <li>
              <this.Link to="/"><span className="icon-home"></span></this.Link>
            </li>
            <li className="fast-nav text-uppercase">
              <this.Link to="/">SETTINGS</this.Link>
            </li>
            {
              menuSource["settings"]["subItems"].map((value, index) =>
                "isFashNav" in value && value["isFashNav"] ?
                  <li className={(currentPath===value["route"] ? "active" : "") + " fast-nav"} key={index}>
                    <this.Link to={value["route"]}>{value["title"]}</this.Link>
                  </li>
                  :
                  ""
              )
            }
          </ul>
        </div>
        {
          this.Util.isCheckingPermission(this.props) ?
            <StartUp />
            :
            this.Util.isNoPermissionProp(this.props) ?
              <NoPermission />
              :
              
              <div className="main-layout main-store-account">
                <this.Form onSubmit={this.handleSubmit}>
                  <this.Row>
                    <this.Col md="12"> 
                      <this.Tabs type="card">
                        <this.TabPane tab={<this.Translate id="store_acc_general" />} key="1">
                          <this.Row>
                            <this.Col lg="4" md="4"> 
                              <this.InputText
                                name="businessName"
                                data={storeAccount.list.businessName}
                                label={<this.Translate id="store_acc_business_name" />}
                                placeholder={this.CATranslate("store_acc_business_name", locale)}
                                form={form}
                                isAutoFocus={true}
                                required/>
                              <this.UploadImg 
                                name="logo" 
                                label={<this.Translate id="text_logo" />}
                                data={{file: image}}
                                fileList={[image]}
                                endPoint={`${this.Util.getAPIURL()}/file/v1/upload/general`}
                                endPointDelete={`${this.Util.getAPIURL()}/file/v1/general/delete`}
                                accessToken={this.Util.getAccessToken()}
                                form={form} />
                              <this.InputText
                                name="storeName"
                                data={storeAccount.list.storeName}
                                label={<this.Translate id="store_acc_store_name" />}
                                notation=".storevein.com"
                                placeholder={this.CATranslate("store_acc_store_name", locale)}
                                form={form}
                                disabled/>
                  
                              <this.InputText
                                name="countryId"
                                data={storeAccount.list.country != null ? storeAccount.list.country.name : ""}
                                label={<this.Translate id="store_acc_country" />}
                                placeholder={this.CATranslate("store_acc_country", locale)}
                                disabled
                                form={form}/>

                              <this.Select
                                name="languageId"
                                dataSource={this.props.languages}
                                defaultValue={storeAccount.list.languageId}
                                valueKey="id"
                                label={<this.Translate id="store_acc_language" />}
                                placeholder={this.CATranslate("store_acc_language", locale)}
                                form={form} />

                              <this.Select
                                name="currencyId"
                                dataSource={currency}
                                defaultValue={storeAccount.list.currencyId}
                                valueKey="id"
                                label={<this.Translate id="store_acc_currency" />}
                                placeholder={this.CATranslate("store_acc_currency", locale)}
                                form={form} disabled />

                              <this.Select
                                name="currencyPosition"
                                dataSource={this.currencyPositions}
                                defaultValue={storeAccount.list.currencyPosition}
                                label={<this.Translate id="store_acc_currency_position" />}
                                placeholder={this.CATranslate("store_acc_currency_position", locale)}
                                form={form} />

                              <this.Select
                                name="taxId"
                                dataSource={taxs}
                                defaultValue={storeAccount.list.taxId}
                                valueKey="id"
                                label={<this.Translate id="store_acc_tax" />}
                                placeholder={this.CATranslate("store_acc_tax", locale)}
                                form={form} />

                              <this.Select
                                name="dateFormat"
                                dataSource={this.Util.listFormatDate()}
                                defaultValue={storeAccount.list.dateFormat}
                                help={`${this.exampleDateFormat}`}
                                onChange={this.handleChangeDateFormat}
                                label={<this.Translate id="store_acc_date_format" />}
                                placeholder={this.CATranslate("store_acc_date_format", locale)}
                                form={form} />

                            </this.Col>
                          </this.Row>
                        </this.TabPane>
                        <this.TabPane tab={<this.Translate id="store_acc_account" />} key="2">
                          <this.Row>
                            <this.Col lg="4" md="4"> 
                              <this.InputPassword
                                // CURRENT PWD
                                currentPWDName="currentPassword"
                                currentPWDLabel={<this.Translate id="store_acc_current_password" />}
                                currentPWDPlaceholder={this.CATranslate("store_acc_current_password", locale)}
                    
                                // PWD
                                label={<this.Translate id="store_acc_new_password" />}
                                placeholder={this.CATranslate("store_acc_new_password", locale)}
                    
                                // CONFIRM PWD
                                confirmLabel={<this.Translate id="store_acc_confirm_password" />}
                                confirmPlaceholder={this.CATranslate("store_acc_confirm_password", locale)}

                                messageIsMatchPassword={<this.Translate id="store_acc_error_confirm_pwd_not_match" />}
                                required={false}
                                requiredCurrentPWD={true}
                                errorRequired={<this.Translate id="store_acc_error_pwd_required" />}
                                errorRequiredConfirm={<this.Translate id="store_acc_error_confirm_pwd_required" />}
                                errorMessageCurrentPWD={this.errorMessageCurrentPWD}
                                validateClassStatusCurrentPWD={this.validateClassStatusCurrentPWD}
                                form={form} />
                            </this.Col>
                          </this.Row>
                        </this.TabPane>
                        <this.TabPane tab={<this.Translate id="store_acc_contact" />} key="3">
                          <this.Row>
                            <this.Col lg="4" md="4"> 
                              <this.InputText
                                data={storeAccount.list.firstName}
                                name="firstName"
                                label={<this.Translate id="store_acc_first_name" />}
                                placeholder={this.CATranslate("store_acc_first_name", locale)}
                                form={form}/>
                           
                              <this.InputText
                                data={storeAccount.list.lastName}
                                name="lastName"
                                label={<this.Translate id="store_acc_last_name" />}
                                placeholder={this.CATranslate("store_acc_last_name", locale)}
                                form={form}/>
                           
                              <this.InputEmail
                                data={storeAccount.list.email}
                                name="email"
                                label={<this.Translate id="store_acc_email" />}
                                placeholder={this.CATranslate("store_acc_email", locale)}
                                form={form}/>
                           
                              <this.InputText
                                data={storeAccount.list.phoneNumber}
                                name="phoneNumber"
                                label={<this.Translate id="store_acc_phone_number" />}
                                placeholder={this.CATranslate("store_acc_phone_number", locale)}
                                form={form} />
                            
                              <this.InputText
                                data={storeAccount.list.address}
                                name="address"
                                label={<this.Translate id="text_address" />}
                                placeholder={this.CATranslate("text_address", locale)}
                                form={form}/>
                          
                              <this.InputText
                                data={storeAccount.list.street}
                                name="street"
                                label={<this.Translate id="store_acc_street" />}
                                placeholder={this.CATranslate("store_acc_street", locale)}
                                form={form}/>
                            
                              <this.InputText
                                data={storeAccount.list.city}
                                name="city"
                                label={<this.Translate id="store_acc_city" />}
                                placeholder={this.CATranslate("store_acc_city", locale)}
                                form={form}/>
                          
                              <this.InputText
                                data={storeAccount.list.postCode}
                                name="postCode"
                                label={<this.Translate id="store_acc_post_code" />}
                                placeholder={this.CATranslate("store_acc_post_code", locale)}
                                form={form} />
                            </this.Col>
                          </this.Row>
                        </this.TabPane>
                        <this.TabPane tab={<this.Translate id="store_acc_setting" />} key="4">
                          <this.Row>
                            <this.Col lg="4" md="4"> 
                              <this.Select
                                name="productGenerateCodeType"
                                defaultValue={storeAccount.list.productGenerateCodeType}
                                dataSource={this.autoGenerateDataSource}
                                label={<this.Translate id="store_acc_auto_generate_pcode" />}
                                placeholder={this.CATranslate("store_acc_auto_generate_pcode", locale)}
                                form={form} />

                              <this.InputNumber
                                name="productCodeSequenceStart"
                                label={<this.Translate id="store_acc_start_sequence_code" />}
                                placeholder={this.CATranslate("store_acc_start_sequence_code", locale)}
                                data={storeAccount.list.productCodeSequenceStart}
                                max={9999999999}
                                errorLength={<this.Translate id="store_acc_error_sequence_start_no" />}
                                form={form} />
                            </this.Col> 
                          </this.Row>
                        </this.TabPane>
                        <this.TabPane tab="Device" key="5">
                          <this.Row>
                            <this.Col lg="4" md="4" style={{marginBottom: 20}}> 
                              <this.InputNumber
                                data={storeAccount.list.numberOfDevice}
                                name="deviceNumber"
                                precision={0}
                                label={<this.Translate id="number_of_device" />}
                                placeholder={this.CATranslate("number_of_device", locale)}
                                disabled={true}
                                form={form} />
                              <this.Table 
                                dataSource={this.props.devices.list}
                                columns={[
                                  {
                                    title: <this.Translate id="text_number" />,
                                    dataIndex: "code",
                                    key: "code",
                                    render: (text, record, index) => {
                                      return <div id={`device-${index}`}>{record.code}</div>;
                                    }
                                  },
                                  {
                                    title: <this.Translate id="text_status" />,
                                    dataIndex: "status",
                                    key: "status",
                                    width: 130,
                                    render: status => {
                                      return (
                                        status === this.Enum.ACTIVE ?
                                          <this.Badge text={<this.Translate id="text_available" />} status="success" />
                                          :
                                          <this.Badge text={<this.Translate id="text_not_available"/>} status="error" />
                                      );
                                    }
                                  },
                                  {
                                    title: <this.Translate id="text_action" />,
                                    key: "action",
                                    width: 50,
                                    render: (text, record, index) => {
                                      return <div className="btn-action-device">{(record.status === this.Enum.ACTIVE ?
                                        <this.Button style={{width: 70}} type="info" onClick={() => this.handleOnCopyDeviceNumber(`device-${index}`, record.status)}>{<this.Translate id="copy_device_number"/>}</this.Button>
                                        :
                                        <this.Button style={{width: 70}} loading={this.props.renew.updating && this.renewButtonIndex === index} type="info" onClick={() => this.handleOnReNewDeviceNumber(record.id, index)}>{<this.Translate id="text_renew"/>}</this.Button>)
                                      }</div>;
                                    }
                                  }
                                ]}
                                locale={{emptyText: <this.Translate id="table_empty_data"/>}}
                                loading={false} />
                            </this.Col> 
                          </this.Row>
                        </this.TabPane>
                        <this.TabPane tab={<this.Translate id="store_acc_billing" />} key="6">
                          <this.Row>
                            <this.Col lg="4" md="4"> 
                              <this.DatePickers
                                name="registerDate"
                                defaultValue={this.Util.formatDatePicker(storeAccount.list.registerDate)}
                                label={<this.Translate id="store_acc_register_date" />}
                                placeholder={this.CATranslate("store_acc_register_date", locale)}
                                form={form}
                                disabled />
                              {
                                storeAccount.list.expiredDate !== null && storeAccount.list.expiredDate !== "undefined"
                                  ?
                                  <this.DatePickers
                                    name="expiredDate"
                                    defaultValue={this.Util.formatDatePicker(storeAccount.list.expiredDate)}
                                    label={<this.Translate id="store_acc_expired_date" />}
                                    placeholder={this.CATranslate("store_acc_expired_date", locale)}
                                    form={form}
                                    disabled />
                                  :
                                  ""
                              }

                              <div className="general">
                                <h6><this.Translate id="store_acc_plan" /></h6>
                              </div>

                              <this.FormGroup>
                                <this.RadioBox 
                                  className="main-radio-acc"
                                  label=" "
                                  name="businessPlanId" 
                                  type="radio"
                                  defaultValue={storeAccount.list.businessPlanId}
                                  form={form}
                                  disabled={true}
                                  onSelect={this.onSelect}
                                  onChange={this.onChange}>
                                  { businessplan.map( (businessplan, key) => 
                                    <this.RadioChildBox
                                      key={key}
                                      title={businessplan.name}
                                      language={businessplan.description}
                                      value={businessplan.id} /> 
                                  ) 
                                  }
                                </this.RadioBox> 
                              </this.FormGroup>
                          
                              <this.RadioButton 
                                name="paymentType"
                                defaultValue={storeAccount.list.paymentType}
                                dataSource={this.paymentTypes}
                                form={form}
                                disabled={true}
                                required/>

                            </this.Col> 
                          </this.Row>
                        </this.TabPane>
    
                      </this.Tabs>
                      
                    </this.Col> 
                              
                  </this.Row>
                  <this.Button type="info" htmlType="submit" loading={storeAccountUpdate.updating}>
                    <span className="icon-save icon-padding-right"></span><this.Translate id="text_save" />
                  </this.Button>
                </this.Form>
              </div>
        }
      </div>
    );
  }
}