export default {
  REQUEST_MANAGEMENT_EMPLOYEE: "REQUEST_MANAGEMENT_EMPLOYEE",
  REQUEST_MANAGEMENT_EMPLOYEE_PENDING: "REQUEST_MANAGEMENT_EMPLOYEE_PENDING",
  REQUEST_MANAGEMENT_EMPLOYEE_REJECTED: "REQUEST_MANAGEMENT_EMPLOYEE_REJECTED",
  REQUEST_MANAGEMENT_EMPLOYEE_FULFILLED: "REQUEST_MANAGEMENT_EMPLOYEE_FULFILLED",
  
  ARCHIVE_MANAGEMENT_EMPLOYEE: "ARCHIVE_MANAGEMENT_EMPLOYEE",
  ARCHIVE_MANAGEMENT_EMPLOYEE_PENDING: "ARCHIVE_MANAGEMENT_EMPLOYEE_PENDING",
  ARCHIVE_MANAGEMENT_EMPLOYEE_REJECTED: "ARCHIVE_MANAGEMENT_EMPLOYEE_REJECTED",
  ARCHIVE_MANAGEMENT_EMPLOYEE_FULFILLED: "ARCHIVE_MANAGEMENT_EMPLOYEE_FULFILLED",
  
  ADD_MANAGEMENT_EMPLOYEE: "ADD_MANAGEMENT_EMPLOYEE",
  ADD_MANAGEMENT_EMPLOYEE_PENDING: "ADD_MANAGEMENT_EMPLOYEE_PENDING",
  ADD_MANAGEMENT_EMPLOYEE_REJECTED: "ADD_MANAGEMENT_EMPLOYEE_REJECTED",
  ADD_MANAGEMENT_EMPLOYEE_FULFILLED: "ADD_MANAGEMENT_EMPLOYEE_FULFILLED",
  
  UPDATE_MANAGEMENT_EMPLOYEE: "UPDATE_MANAGEMENT_EMPLOYEE",
  UPDATE_MANAGEMENT_EMPLOYEE_PENDING: "UPDATE_MANAGEMENT_EMPLOYEE_PENDING",
  UPDATE_MANAGEMENT_EMPLOYEE_REJECTED: "UPDATE_MANAGEMENT_EMPLOYEE_REJECTED",
  UPDATE_MANAGEMENT_EMPLOYEE_FULFILLED: "UPDATE_MANAGEMENT_EMPLOYEE_FULFILLED",

  DETAIL_MANAGEMENT_EMPLOYEE: "DETAIL_MANAGEMENT_EMPLOYEE",
  DETAIL_MANAGEMENT_EMPLOYEE_PENDING: "DETAIL_MANAGEMENT_EMPLOYEE_PENDING",
  DETAIL_MANAGEMENT_EMPLOYEE_REJECTED: "DETAIL_MANAGEMENT_EMPLOYEE_REJECTED",
  DETAIL_MANAGEMENT_EMPLOYEE_FULFILLED: "DETAIL_MANAGEMENT_EMPLOYEE_FULFILLED",
  RESET_DETAIL_MANAGEMENT_EMPLOYEE: "RESET_DETAIL_MANAGEMENT_EMPLOYEE",
  
  RESET_MANAGEMENT_EMPLOYEE: "RESET_MANAGEMENT_EMPLOYEE",
  SHOW_MANAGEMENT_EMPLOYEE_FORM: "SHOW_MANAGEMENT_EMPLOYEE_FORM"
};