export default {
  REQUEST_EMPLOYEE: "REQUEST_EMPLOYEE",
  REQUEST_EMPLOYEE_PENDING: "REQUEST_EMPLOYEE_PENDING",
  REQUEST_EMPLOYEE_REJECTED: "REQUEST_EMPLOYEE_REJECTED",
  REQUEST_EMPLOYEE_FULFILLED: "REQUEST_EMPLOYEE_FULFILLED",
  
  ARCHIVE_EMPLOYEE: "ARCHIVE_EMPLOYEE",
  ARCHIVE_EMPLOYEE_PENDING: "ARCHIVE_EMPLOYEE_PENDING",
  ARCHIVE_EMPLOYEE_REJECTED: "ARCHIVE_EMPLOYEE_REJECTED",
  ARCHIVE_EMPLOYEE_FULFILLED: "ARCHIVE_EMPLOYEE_FULFILLED",
  
  ADD_EMPLOYEE: "ADD_EMPLOYEE",
  ADD_EMPLOYEE_PENDING: "ADD_EMPLOYEE_PENDING",
  ADD_EMPLOYEE_REJECTED: "ADD_EMPLOYEE_REJECTED",
  ADD_EMPLOYEE_FULFILLED: "ADD_EMPLOYEE_FULFILLED",
  
  UPDATE_EMPLOYEE: "UPDATE_EMPLOYEE",
  UPDATE_EMPLOYEE_PENDING: "UPDATE_EMPLOYEE_PENDING",
  UPDATE_EMPLOYEE_REJECTED: "UPDATE_EMPLOYEE_REJECTED",
  UPDATE_EMPLOYEE_FULFILLED: "UPDATE_EMPLOYEE_FULFILLED",

  DETAIL_EMPLOYEE: "DETAIL_EMPLOYEE",
  DETAIL_EMPLOYEE_PENDING: "DETAIL_EMPLOYEE_PENDING",
  DETAIL_EMPLOYEE_REJECTED: "DETAIL_EMPLOYEE_REJECTED",
  DETAIL_EMPLOYEE_FULFILLED: "DETAIL_EMPLOYEE_FULFILLED",
  RESET_DETAIL_EMPLOYEE: "RESET_DETAIL_EMPLOYEE",
  
  RESET_EMPLOYEE: "RESET_EMPLOYEE",
  SHOW_EMPLOYEE_FORM: "SHOW_EMPLOYEE_FORM"
};