export default {
  REQUEST__EMPLOYEE: "REQUEST__EMPLOYEE",
  REQUEST__EMPLOYEE_PENDING: "REQUEST__EMPLOYEE_PENDING",
  REQUEST__EMPLOYEE_REJECTED: "REQUEST__EMPLOYEE_REJECTED",
  REQUEST__EMPLOYEE_FULFILLED: "REQUEST__EMPLOYEE_FULFILLED",
  
  ARCHIVE__EMPLOYEE: "ARCHIVE__EMPLOYEE",
  ARCHIVE__EMPLOYEE_PENDING: "ARCHIVE__EMPLOYEE_PENDING",
  ARCHIVE__EMPLOYEE_REJECTED: "ARCHIVE__EMPLOYEE_REJECTED",
  ARCHIVE__EMPLOYEE_FULFILLED: "ARCHIVE__EMPLOYEE_FULFILLED",
  
  ADD__EMPLOYEE: "ADD__EMPLOYEE",
  ADD__EMPLOYEE_PENDING: "ADD__EMPLOYEE_PENDING",
  ADD__EMPLOYEE_REJECTED: "ADD__EMPLOYEE_REJECTED",
  ADD__EMPLOYEE_FULFILLED: "ADD__EMPLOYEE_FULFILLED",
  
  UPDATE__EMPLOYEE: "UPDATE__EMPLOYEE",
  UPDATE__EMPLOYEE_PENDING: "UPDATE__EMPLOYEE_PENDING",
  UPDATE__EMPLOYEE_REJECTED: "UPDATE__EMPLOYEE_REJECTED",
  UPDATE__EMPLOYEE_FULFILLED: "UPDATE__EMPLOYEE_FULFILLED",

  DETAIL__EMPLOYEE: "DETAIL__EMPLOYEE",
  DETAIL__EMPLOYEE_PENDING: "DETAIL__EMPLOYEE_PENDING",
  DETAIL__EMPLOYEE_REJECTED: "DETAIL__EMPLOYEE_REJECTED",
  DETAIL__EMPLOYEE_FULFILLED: "DETAIL__EMPLOYEE_FULFILLED",
  RESET_DETAIL__EMPLOYEE: "RESET_DETAIL__EMPLOYEE",
  
  RESET__EMPLOYEE: "RESET__EMPLOYEE",
  SHOW__EMPLOYEE_FORM: "SHOW__EMPLOYEE_FORM"
};