stages:
  - deploy
deploy:
  stage: deploy
  tags: 
      - webserver
  script:
      - echo "Building deploy package"
      - npm install
      - npm run webpack:build
      - rm -rf /var/www/pos/*
      - cp -R dist/* /var/www/pos
      - echo "Deploy successful"
  only:
      - develop
