export default {
   REQUEST_TAX: "REQUEST_TAX",
   REQUEST_TAX_PENDING: "REQUEST_TAX_PENDING",
   REQUEST_TAX_REJECTED: "REQUEST_TAX_REJECTED",
   REQUEST_TAX_FULFILLED: "REQUEST_TAX_FULFILLED",
 
   DETAIL_TAX: "DETAIL_TAX",
   DETAIL_TAX_PENDING: "DETAIL_TAX_PENDING",
   DETAIL_TAX_REJECTED: "DETAIL_TAX_REJECTED",
   DETAIL_TAX_FULFILLED: "DETAIL_TAX_FULFILLED",
 
   ARCHIVE_TAX: "ARCHIVE_TAX",
   ARCHIVE_TAX_PENDING: "ARCHIVE_TAX_PENDING",
   ARCHIVE_TAX_REJECTED: "ARCHIVE_TAX_REJECTED",
   ARCHIVE_TAX_FULFILLED: "ARCHIVE_TAX_FULFILLED",
 
   ADD_TAX: "ADD_TAX",
   ADD_TAX_PENDING: "ADD_TAX_PENDING",
   ADD_TAX_REJECTED: "ADD_TAX_REJECTED",
   ADD_TAX_FULFILLED: "ADD_TAX_FULFILLED",
 
   UPDATE_TAX: "UPDATE_TAX",
   UPDATE_TAX_PENDING: "UPDATE_TAX_PENDING",
   UPDATE_TAX_REJECTED: "UPDATE_TAX_REJECTED",
   UPDATE_TAX_FULFILLED: "UPDATE_TAX_FULFILLED",
 
   RESET_TAX: "RESET_TAX",
   SHOW_TAX_FORM: "SHOW_TAX_FORM"
 };