export default {
  REQUEST_CUSTOMERS: "REQUEST_CUSTOMERS",
  REQUEST_CUSTOMERS_PENDING: "REQUEST_CUSTOMERS_PENDING",
  REQUEST_CUSTOMERS_REJECTED: "REQUEST_CUSTOMERS_REJECTED",
  REQUEST_CUSTOMERS_FULFILLED: "REQUEST_CUSTOMERS_FULFILLED",
  REQUEST_CUSTOMERS_RESET: "REQUEST_CUSTOMERS_RESET",
  
  ARCHIVE_MANAGEMENT_CUSTOMERS: "ARCHIVE_MANAGEMENT_CUSTOMERS",
  ARCHIVE_CUSTOMERS_PENDING: "ARCHIVE_CUSTOMERS_PENDING",
  ARCHIVE_CUSTOMERS_REJECTED: "ARCHIVE_CUSTOMERS_REJECTED",
  ARCHIVE_CUSTOMERS_FULFILLED: "ARCHIVE_CUSTOMERS_FULFILLED",
  
  ADD_MANAGEMENT_CUSTOMERS: "ADD_MANAGEMENT_CUSTOMERS",
  ADD_CUSTOMERS_PENDING: "ADD_CUSTOMERS_PENDING",
  ADD_CUSTOMERS_REJECTED: "ADD_CUSTOMERS_REJECTED",
  ADD_CUSTOMERS_FULFILLED: "ADD_CUSTOMERS_FULFILLED",
  
  UPDATE_MANAGEMENT_CUSTOMERS: "UPDATE_MANAGEMENT_CUSTOMERS",
  UPDATE_CUSTOMERS_PENDING: "UPDATE_CUSTOMERS_PENDING",
  UPDATE_CUSTOMERS_REJECTED: "UPDATE_CUSTOMERS_REJECTED",
  UPDATE_CUSTOMERS_FULFILLED: "UPDATE_CUSTOMERS_FULFILLED",

  REQUEST_EXTEND_FETCH_CUSTOMERS: "REQUEST_EXTEND_FETCH_CUSTOMERS",
  REQUEST_EXTEND_FETCH_CUSTOMERS_PENDING: "REQUEST_EXTEND_FETCH_CUSTOMERS_PENDING",
  REQUEST_EXTEND_FETCH_CUSTOMERS_REJECTED: "REQUEST_EXTEND_FETCH_CUSTOMERS_REJECTED",
  REQUEST_EXTEND_FETCH_CUSTOMERS_FULFILLED: "REQUEST_EXTEND_FETCH_CUSTOMERS_FULFILLED",

  REQUEST_GROUP_CUSTOMERS: "EQUEST_MANAGEMENT_GROUP_CUSTOMERS",
  REQUEST_GROUP_CUSTOMERS_PENDING: "REQUEST_GROUP_CUSTOMERS_PENDING",
  REQUEST_GROUP_CUSTOMERS_REJECTED: "REQUEST_GROUP_CUSTOMERS_REJECTED",
  REQUEST_GROUP_CUSTOMERS_FULFILLED: "REQUEST_GROUP_CUSTOMERS_FULFILLED",

  DETAIL_CUSTOMERS: "DETAIL_CUSTOMERS",
  DETAIL_CUSTOMERS_PENDING: "DETAIL_CUSTOMERS_PENDING",
  DETAIL_CUSTOMERS_REJECTED: "DETAIL_CUSTOMERS_REJECTED",
  DETAIL_CUSTOMERS_FULFILLED: "DETAIL_CUSTOMERS_FULFILLED",
  RESET_DETAIL_CUSTOMERS: "RESET_DETAIL_CUSTOMERS",
  RESET_DETAIL_PARTIAL_CUSTOMERS: "RESET_DETAIL_PARTIAL_CUSTOMERS",

  RESET_MANAGEMENT_CUSTOMERS: "RESET_MANAGEMENT_CUSTOMERS",
  SHOW_CUSTOMERS_FORM: "SHOW_CUSTOMERS_FORM"
};