export default {
  REQUEST_MANAGEMENT_GROUP_CUSTOMERS: "REQUEST_MANAGEMENT_GROUP_CUSTOMERS",
  REQUEST_MANAGEMENT_GROUP_CUSTOMERS_PENDING: "REQUEST_MANAGEMENT_GROUP_CUSTOMERS_PENDING",
  REQUEST_MANAGEMENT_GROUP_CUSTOMERS_REJECTED: "REQUEST_MANAGEMENT_GROUP_CUSTOMERS_REJECTED",
  REQUEST_MANAGEMENT_GROUP_CUSTOMERS_FULFILLED: "REQUEST_MANAGEMENT_GROUP_CUSTOMERS_FULFILLED",
  
  ADD_MANAGEMENT_GROUP_CUSTOMERS: "ADD_MANAGEMENT_GROUP_CUSTOMERS",
  ADD_MANAGEMENT_GROUP_CUSTOMERS_PENDING: "ADD_MANAGEMENT_GROUP_CUSTOMERS_PENDING",
  ADD_MANAGEMENT_GROUP_CUSTOMERS_REJECTED: "ADD_MANAGEMENT_GROUP_CUSTOMERS_REJECTED",
  ADD_MANAGEMENT_GROUP_CUSTOMERS_FULFILLED: "ADD_MANAGEMENT_GROUP_CUSTOMERS_FULFILLED",

  UPDATE_MANAGEMENT_GROUP_CUSTOMERS: "UPDATE_MANAGEMENT_GROUP_CUSTOMERS",
  UPDATE_MANAGEMENT_GROUP_CUSTOMERS_PENDING: "UPDATE_MANAGEMENT_GROUP_CUSTOMERS_PENDING",
  UPDATE_MANAGEMENT_GROUP_CUSTOMERS_REJECTED: "UPDATE_MANAGEMENT_GROUP_CUSTOMERS_REJECTED",
  UPDATE_MANAGEMENT_GROUP_CUSTOMERS_FULFILLED: "UPDATE_MANAGEMENT_GROUP_CUSTOMERS_FULFILLED",

  RESET_MANAGEMENT_GROUP_CUSTOMERS: "RESET_MANAGEMENT_GROUP_CUSTOMERS",
  SHOW_MANAGEMENT_GROUP_CUSTOMERS_FORM: "SHOW_MANAGEMENT_GROUP_CUSTOMERS_FORM",
};