export default {
  REQUEST_MANAGEMENT_CUSTOMERS: "REQUEST_MANAGEMENT_CUSTOMERS",
  REQUEST_MANAGEMENT_CUSTOMERS_PENDING: "REQUEST_MANAGEMENT_CUSTOMERS_PENDING",
  REQUEST_MANAGEMENT_CUSTOMERS_REJECTED: "REQUEST_MANAGEMENT_CUSTOMERS_REJECTED",
  REQUEST_MANAGEMENT_CUSTOMERS_FULFILLED: "REQUEST_MANAGEMENT_CUSTOMERS_FULFILLED",
  REQUEST_MANAGEMENT_CUSTOMERS_RESET: "REQUEST_MANAGEMENT_CUSTOMERS_RESET",
  
  ARCHIVE_MANAGEMENT_CUSTOMERS: "ARCHIVE_MANAGEMENT_CUSTOMERS",
  ARCHIVE_MANAGEMENT_CUSTOMERS_PENDING: "ARCHIVE_MANAGEMENT_CUSTOMERS_PENDING",
  ARCHIVE_MANAGEMENT_CUSTOMERS_REJECTED: "ARCHIVE_MANAGEMENT_CUSTOMERS_REJECTED",
  ARCHIVE_MANAGEMENT_CUSTOMERS_FULFILLED: "ARCHIVE_MANAGEMENT_CUSTOMERS_FULFILLED",
  
  ADD_MANAGEMENT_CUSTOMERS: "ADD_MANAGEMENT_CUSTOMERS",
  ADD_MANAGEMENT_CUSTOMERS_PENDING: "ADD_MANAGEMENT_CUSTOMERS_PENDING",
  ADD_MANAGEMENT_CUSTOMERS_REJECTED: "ADD_MANAGEMENT_CUSTOMERS_REJECTED",
  ADD_MANAGEMENT_CUSTOMERS_FULFILLED: "ADD_MANAGEMENT_CUSTOMERS_FULFILLED",
  
  UPDATE_MANAGEMENT_CUSTOMERS: "UPDATE_MANAGEMENT_CUSTOMERS",
  UPDATE_MANAGEMENT_CUSTOMERS_PENDING: "UPDATE_MANAGEMENT_CUSTOMERS_PENDING",
  UPDATE_MANAGEMENT_CUSTOMERS_REJECTED: "UPDATE_MANAGEMENT_CUSTOMERS_REJECTED",
  UPDATE_MANAGEMENT_CUSTOMERS_FULFILLED: "UPDATE_MANAGEMENT_CUSTOMERS_FULFILLED",

  REQUEST_EXTEND_FETCH_CUSTOMERS: "REQUEST_EXTEND_FETCH_CUSTOMERS",
  REQUEST_EXTEND_FETCH_CUSTOMERS_PENDING: "REQUEST_EXTEND_FETCH_CUSTOMERS_PENDING",
  REQUEST_EXTEND_FETCH_CUSTOMERS_REJECTED: "REQUEST_EXTEND_FETCH_CUSTOMERS_REJECTED",
  REQUEST_EXTEND_FETCH_CUSTOMERS_FULFILLED: "REQUEST_EXTEND_FETCH_CUSTOMERS_FULFILLED",
  
  RESET_MANAGEMENT_CUSTOMERS: "RESET_MANAGEMENT_CUSTOMERS",
  SHOW_MANAGEMENT_CUSTOMERS_FORM: "SHOW_MANAGEMENT_CUSTOMERS_FORM"
};