import React from "react";
import List from "../List";
import FormCreate from "../../../containers/settings/OperationRecord/FormCreate";
import FormUpdate from "../../../containers/settings/OperationRecord/FormUpdate";
import Constant from "../../../constants/settings/operationRecord";
import OperationRecordAction from "../../../action/settings/operationRecord";
import OperatinRecordService from "../../../services/settings/OperationRecordService";

export default class OperationRecord extends List {
  constructor(props) {
    super(props);
    this.columns = new Column();
    this.formCreate = <FormCreate/>;
    this.formUpdate = <FormUpdate/>;
    this.columnFilterWithKey = ["name"];
    this.service = OperatinRecordService;
    this.action = OperationRecordAction;
    this.RESET_CONSTANT = Constant.RESET_OPERATION_RECORD;
  }

  componentWillUpdate(nextProps) {
    if (nextProps.add.added) {
      nextProps.dispatch(OperationRecordAction.fetch(this.pageSize));
      this.props.dispatch(OperationRecordAction.reset());
    }
  }

  renderFilterStatus() {}

  checkIsAllowDeleteRecordOrNot() {
    if (this.state.selectedListIds &&
      this.state.selectedListIds.length > 0 &&
      this.props[this.fetchingProp]
    ) {
      let isHasSystemRecord = false;
      this.state.selectedListIds.forEach(selectedId => {
        const result = this.props[this.fetchingProp].list.find(record => record.id === selectedId);

        if (result && result.isSystem === this.Enum.IS_SYSTEM) {
          isHasSystemRecord = true;
          this.Message.warning(this.CATranslate("text_warning_delete_system_record", this.props.locale));
        }
      });
      return isHasSystemRecord;
    }
  }
}

class Column extends List {
  constructor(props) {
    super(props);
    this.colorOperationType = ["#4cb64c", "#c72727"];

    return [
      this.columnCreatedAt,
      {
        title: <this.Translate id="text_description" />,
        dataIndex: "name",
        key: "name",
        sorter: true,
      },
      {
        title: <this.Translate id="col_operation_record_recordfor" />,
        dataIndex: "registerDate",
        key: "registerDate",
        width: 160,
        sorter: true,
        render : registerDate => this.Util.formatDate(registerDate)
      },
      {
        title: "Generated By",
        dataIndex: "isSystem",
        key: "isSystem",
        width: 160,
        sorter: true,
        render: (text, record) => {
          let generatedBy = <this.Translate id="text_system" />;
          if (record.isSystem !== this.Enum.IS_SYSTEM && record.user) {
            generatedBy = record.user.fullName;
          }
          return <this.TagLabel color="blue" style={{marginLeft: 10}}>{generatedBy}</this.TagLabel>;
        }
      },
      { 
        title: <this.Translate id="text_type" />,
        dataIndex: "type",
        width: 100,
        align: "center",
        sorter: true,
        render: (text, record) => {
          let colorIndex = 0;
          let type = <this.Translate id="operation_record_income" />;
          if (record.type === this.Enum.OPERATION_TYPE.EXPENSE || record.type === this.Enum.OPERATION_TYPE.COGS) {
            colorIndex = 1;
            type = <this.Translate id="text_expense" />;
          }
          return <this.Tag color={this.colorOperationType[colorIndex]} style={{marginRight: 0}} className="text-center label-stock-status">{type}</this.Tag>;
        }
      },
      {
        title: <this.Translate id="text_amount" />,
        dataIndex: "amount",
        width: 150,
        align: "right",
        sorter: true,
        render: amount => this.Util.formatCurrency(amount, "")
      }
    ];
  }
}