export default {
   DELETE: 3,
   NO_VARIANT: 0,
   PRODUCT_VARIANT: 1,
   PRODUCT_COMPOSITE: 2,
   SERIAL_TYPE: {
     SERIAL: 0,
     SERVICE: 1,
     PRODUCT: 2,
     LICENSE: 3
   },
   TYPE_OF_PRODUCT: {
     GOOD: 0,
     RAW_MATERIAL: 1
   },
   PRODUCT_CODE_GENERATE_TYPE: {
     AUTO: 0,
     CUSTOM: 1
   },
   PROMOTION_TYPE: {
     BASIC: "basic",
     ADVANCE: "advance"
   },
   PO_STEP: {
     DRAFT : 0,
     PROCESS : 1,
     RECEIVED : 2,
     CANCEL : 3,
     RETURN : 4,
     PAID : 5
   },
   IS_AUTO_RECEIVE_STOCK: 1,
   STOCK_ADJUST_STEP: {
     REQUEST : 0,
     COMPLETE : 1
   },
   TYPE_OF_PRINT: {
     BARCODE: 1,
     QR: 2
   },
   STOCK_STRANSFER_STEP: {
     PROCESS : 1,
     RECEIVED : 2,
     CANCEL: 3
   },
   STOCK_CONSIGNMENT_STATUS: {
     DRAFT: "Draft",
     RECEIVED: "Received",
     RETURNED: "Returned"
   },
   STOCK_COUNT_TYPE: {
     PARTIAL: "PARTIAL",
     FULL_COUNT: "FULL"
   },
   STOCK_COUNT_STATUS: {
     IN_PROGRESS: "IN_PROGRESS",
     PAUSE: "PAUSE",
     COMPLETED: "COMPLETED"
   },
   STOCK_COUNT_ENTRY_STATUS: {
     COUNTED: "COUNTED",
     UNCOUNTED: "UNCOUNTED",
     INCLUDE: "INCLUDE",
     EXCLUDE: "EXCLUDE"
   },
   CLIENT_AUTO_NUMBER_TYPE: {
     QUOTATION : 2,
     INVOICE : 4,
     RECEIPT : 6,
     PURCHASE : 8,
     TRANSFER : 10,
     CUSTOMER : 12,
     EMPLOYEE : 14
   },
   LOCAL_SCHEMA: {
     BRAND: "BRAND",
     UNIT: "UNIT",
     TAX: "TAX",
     PRODUCT_TYPE: "PRODUCT_TYPE",
     LANGUAGE: "LANGUAGE",
     VARIANT_ATTRIBUTE: "VARIANT_ATTRIBUTE",
     PRODUCT_TAG: "PRODUCT_TAG",
     LOCATION: "LOCATION",
     SUPPLIER: "SUPPLIER"
   },
   REPORT_TYPE: {
     SALE_SUMMARY: 0,
     PRODUCT: 1,
     CATEGORY: 2,
     USER: 3,
     CUSTOMER: 4,
     LOCATION: 5
   },
   PAYMENT_TERM_TYPE: {
    DAY:"DAY",
    MONTH:"MONTH"
  },
  DISCOUNT_TYPE: {
    PERCENTAGE: 1,
    AMOUNT: 0,
    EACH_ITEM: 2
  },
  PARK_RECEIPT: "PARK_RECEIPT",
  CURRENT_RECEIPT: "CURRENT_RECEIPT",
  TRANSACTION_TYPE: {
    PRE_ORDER: 0,
    INVOICE: 1,
    RECEIPT: 2,
    CREDIT_NOTE: 3,
    RETURN: 4
  },
  TRANSACTION_STATUS: {
    OPEN: 0,
    OVERDUE: 1,
    PAID: 3,
    CREDIT: 4,
    CLOSED: 5
  },
  TRANSACTION_STEP: {
    PROCESS: 1,
    VOID: 2,
    RETURN: 3,
    COMPLETED: 4,
    IN_DELIVERY: 5,
    CREDIT: 6,
    PAID: 7
  },
  SALE_ORDER_STATUS: {
    DRAFT: 0,
    CONFIRMED: 1,
    CLOSED: 2,
    VOID: 4
  },
  INVOICE_STATUS: {
    DRAFT: 0,
    SENT: 1,
    PARTIAL: 2,
    PAID: 3,
    VOID: 4
  },
  INVOICE_TYPE: {
    NON_SCHEDULED: "NON_SCHEDULED",
    SCHEDULED: "SCHEDULED"
  },
  INVOICE_INTERVAL: {
    WEEKLY: "EVERY_WEEK",
    MONTHLY: "EVERY_MONTH"
  },
  PAYMENT_METHOD_AVIALE_ON_POS: 1,
  PRODUCT_AVIALABLE_ON_SALE: 1,
  OPEN_SALE_REGISTRATION_STATUS: {
    OPEN: 1,
    CLOSED: 0
  },
  LANGUAGE_ALREADY_EXIST: 603,
  LITE_PLAN_NOT_ALLOW_CREAE_LOCATION:  628,
  PRO_PLAN_NOT_ALLOW_CREAE_LOCATION: 629,
  SERIAL_NUMBER_REQUIRE: 634,
  INVALID_QUANTITY_SALE_RETURN: 642,
  PAPER_SIZE: {
    A4: 1,
    THERMAL: 2,
    MINI_THERMAL: 3,
    EXCLUDE_TAX: 4,
    INCLUDE_TAX: 5
  },
  CUSTOMER_CREDIT_STATUS: {
    DISABLE: 1,
    ENABLE: 2
  },
  QUOTATION_STEP: {
    DRAFT : 0,
    PROCESS : 1, //create invoice
    CANCEL : 2
  },
  QUOTATION_STATUS: {
    DRAFT: 0,
    SENT: 1,
    APPROVED: 2,
    CLOSED: 3
  },
  QUOTATION_STEP_COLOR: {
    DRAFT: "#FAAD14",
    PROCESS: "#2db7f5",
    CANCEL: "#2DB7F5",
    COMPLETE: "#5BC726"
  },
  PAYMENT_METHOD: {
    CODE: {
      CASH: "001",
      CREDIT: "002"
    }
  },
  LOCATION_NOT_FOUND: 619,
  INVALID_TRANSFER_TO_SAME_LOCATION: 631,
  FORBIDEN_STEP_PROCESS: 610,
  TRANSFER_NUMBER_EXIST: 611,
  PO_NUMBER_ALREADY_EXIST: 611,
  PO_NUMBER_NOT_ALLOW_EMPTY: 612,
  PO_NOT_FOUND: 621,
  PRODUCT_NOT_FOUND: 609,
  PRODUCT_UNIT_NOT_FOUND: 617,
  SUPPLIER_NOT_FOUND: 620,
  PRODUCT_QTY_NOT_ENOUGHT: 630,
  TRANSFER_NOT_FOUND: 633,
  INVALID_LOCATION_FOR_RECEIVE: 632,
  STOCK_ADJUSTMENT_ENTRY_NOT_FOUND: 636,
  ACTIVE: 1,
  ARCHIVE: 3,
  DEACTIVE: 0,
  ALL_STATE: 2,
  IS_SYSTEM: 1,
  IS_DEFAULT: 1,
  NOT_DEFAULT: 0,
  TRANSACTION_ENTRY_STATUS: {
    RETURN: 4
  },
  CURRENCY_POSITION: {
    BEFORE: 0,
    AFTER: 1
  },
  GENERATE_PRODUCT_CODE: {
    MANAUL: 1,
    AUTO: 2
  },
  OPERATION_TYPE: {
    EXPENSE: 0,
    INCOME: 1,
    SALE_INCOME: 2,
    COGS: 3,
    NO_OPERATION: 4
  },
  IS_SALE_RECORD: {
    YES: 1,
    NO: 0
  },
  GENDER: {
    MALE: 0,
    FEMALE: 1
  },
  IMAGE_SPACE: {
    GENERAL: "general",
    EMPLOYEE: "employee",
    PRODUCT: "product",
    BRAND: "brand",
    CATEGORY: "category"
  },
  CASHIER_ROLE: "R003",
  PO_STEP_COLOR: {
    DRAFT: "#f50",
    PROCESS: "#2db7f5",
    RECEIVE: "#87d068",
    CANCEL: "#108ee9",
    RETURN: "blue",
    PAID: "green"
  },
  STOCK_ADJUST_COLOR: {
    REQUEST: "#f0ad4e",
    COMPLETE: "#52c41a",
    REJECT: "#f50"
  },
  STOCK_TRANSFER_STEP_COLOR: {
    PROCESS: "#2db7f5",
    RECEIVED: "#87d068",
    CANCEL: "#108ee9"
  },
  BUSINESS_PLAN_TYPE: {
    FREE: 0,
    LITE: 1,
    PRO: 2,
    PREMIUM: 3
  },
  DURATION_TYPE: {
    DAY: "DAY",
    WEEK: "WEEK",
    MONTH: "MONTH",
    YEAR: "YEAR"
  },
  RECORD_EXIST: 603,
  TAX_NOT_FOUND: 622,
  BRAND_NOT_FOUND: 614,
  PRODUCT_TYPE_NOT_FOUND: 615,
  PRODUCT_UNIT_NOT_FOUND: 617,
  NO_PERMISSON: 627
 };
 