export const REQUEST_CURRENCY            = "REQUEST_CURRENCY";
export const REQUEST_CURRENCY_PENDING    = "REQUEST_CURRENCY_PENDING";
export const REQUEST_CURRENCY_REJECTED   = "REQUEST_CURRENCY_REJECTED";
export const REQUEST_CURRENCY_FULFILLED  = "REQUEST_CURRENCY_FULFILLED";

export const ARCHIVE_CURRENCY = "ARCHIVE_CURRENCY";