export default {
  REQUEST_CURRENCY: "REQUEST_CURRENCY",
  REQUEST_CURRENCY_PENDING: "REQUEST_CURRENCY_PENDING",
  REQUEST_CURRENCY_REJECTED: "REQUEST_CURRENCY_REJECTED",
  REQUEST_CURRENCY_FULFILLED: "REQUEST_CURRENCY_FULFILLED",

  ARCHIVE_CURRENCY: "ARCHIVE_CURRENCY",
  ARCHIVE_CURRENCY_PENDING: "ARCHIVE_CURRENCY_PENDING",
  ARCHIVE_CURRENCY_REJECTED: "ARCHIVE_CURRENCY_REJECTED",
  ARCHIVE_CURRENCY_FULFILLED: "ARCHIVE_CURRENCY_FULFILLED",

  ADD_CURRENCY: "ADD_CURRENCY",
  ADD_CURRENCY_PENDING: "ADD_CURRENCY_PENDING",
  ADD_CURRENCY_REJECTED: "ADD_CURRENCY_REJECTED",
  ADD_CURRENCY_FULFILLED: "ADD_CURRENCY_FULFILLED",

  UPDATE_CURRENCY: "UPDATE_CURRENCY",
  UPDATE_CURRENCY_PENDING: "UPDATE_CURRENCY_PENDING",
  UPDATE_CURRENCY_REJECTED: "UPDATE_CURRENCY_REJECTED",
  UPDATE_CURRENCY_FULFILLED: "UPDATE_CURRENCY_FULFILLED",

  RESET_CURRENCY: "RESET_CURRENCY",
  SHOW_CURRENCY_FORM: "SHOW_CURRENCY_FORM"
};