export default {
  REQUEST_CURRENCY_EXCHANGE: "REQUEST_CURRENCY_EXCHANGE",
  REQUEST_CURRENCY_EXCHANGE_PENDING: "REQUEST_CURRENCY_EXCHANGE_PENDING",
  REQUEST_CURRENCY_EXCHANGE_REJECTED: "REQUEST_CURRENCY_EXCHANGE_REJECTED",
  REQUEST_CURRENCY_EXCHANGE_FULFILLED: "REQUEST_CURRENCY_EXCHANGE_FULFILLED",

  ARCHIVE_CURRENCY_EXCHANGE: "ARCHIVE_CURRENCY_EXCHANGE",
  ARCHIVE_CURRENCY_EXCHANGE_PENDING: "ARCHIVE_CURRENCY_EXCHANGE_PENDING",
  ARCHIVE_CURRENCY_EXCHANGE_REJECTED: "ARCHIVE_CURRENCY_EXCHANGE_REJECTED",
  ARCHIVE_CURRENCY_EXCHANGE_FULFILLED: "ARCHIVE_CURRENCY_EXCHANGE_FULFILLED",

  ADD_CURRENCY_EXCHANGE: "ADD_CURRENCY_EXCHANGE",
  ADD_CURRENCY_EXCHANGE_PENDING: "ADD_CURRENCY_EXCHANGE_PENDING",
  ADD_CURRENCY_EXCHANGE_REJECTED: "ADD_CURRENCY_EXCHANGE_REJECTED",
  ADD_CURRENCY_EXCHANGE_FULFILLED: "ADD_CURRENCY_EXCHANGE_FULFILLED",

  UPDATE_CURRENCY_EXCHANGE: "UPDATE_CURRENCY_EXCHANGE",
  UPDATE_CURRENCY_EXCHANGE_PENDING: "UPDATE_CURRENCY_EXCHANGE_PENDING",
  UPDATE_CURRENCY_EXCHANGE_REJECTED: "UPDATE_CURRENCY_EXCHANGE_REJECTED",
  UPDATE_CURRENCY_EXCHANGE_FULFILLED: "UPDATE_CURRENCY_EXCHANGE_FULFILLED",

  RESET_CURRENCY_EXCHANGE: "RESET_CURRENCY_EXCHANGE",
  SHOW_CURRENCY_EXCHANGE_FORM: "SHOW_CURRENCY_EXCHANGE_FORM"
};