export default {
  REQUEST_DEVICE: "REQUEST_DEVICE",
  REQUEST_DEVICE_PENDING: "REQUEST_DEVICE_PENDING",
  REQUEST_DEVICE_REJECTED: "REQUEST_DEVICE_REJECTED",
  REQUEST_DEVICE_FULFILLED: "REQUEST_DEVICE_FULFILLED",

  UPDATE_DEVICE: "UPDATE_DEVICE",
  UPDATE_DEVICE_PENDING: "UPDATE_DEVICE_PENDING",
  UPDATE_DEVICE_REJECTED: "UPDATE_DEVICE_REJECTED",
  UPDATE_DEVICE_FULFILLED: "UPDATE_DEVICE_FULFILLED",

  RESET_UPDATE: "RESET_UPDATE"

};