export default {
  REQUEST_INCOME_EXPENSE: "REQUEST_INCOME_EXPENSE",
  REQUEST_INCOME_EXPENSE_PENDING: "REQUEST_INCOME_EXPENSE_PENDING",
  REQUEST_INCOME_EXPENSE_REJECTED: "REQUEST_INCOME_EXPENSE_REJECTED",
  REQUEST_INCOME_EXPENSE_FULFILLED: "REQUEST_INCOME_EXPENSE_FULFILLED",
  
  ARCHIVE_INCOME_EXPENSE: "ARCHIVE_INCOME_EXPENSE",
  ARCHIVE_INCOME_EXPENSE_PENDING: "ARCHIVE_INCOME_EXPENSE_PENDING",
  ARCHIVE_INCOME_EXPENSE_REJECTED: "ARCHIVE_INCOME_EXPENSE_REJECTED",
  ARCHIVE_INCOME_EXPENSE_FULFILLED: "ARCHIVE_INCOME_EXPENSE_FULFILLED",
  
  ADD_INCOME_EXPENSE: "ADD_INCOME_EXPENSE",
  ADD_INCOME_EXPENSE_PENDING: "ADD_INCOME_EXPENSE_PENDING",
  ADD_INCOME_EXPENSE_REJECTED: "ADD_INCOME_EXPENSE_REJECTED",
  ADD_INCOME_EXPENSE_FULFILLED: "ADD_INCOME_EXPENSE_FULFILLED",
  
  UPDATE_INCOME_EXPENSE: "UPDATE_INCOME_EXPENSE",
  UPDATE_INCOME_EXPENSE_PENDING: "UPDATE_INCOME_EXPENSE_PENDING",
  UPDATE_INCOME_EXPENSE_REJECTED: "UPDATE_INCOME_EXPENSE_REJECTED",
  UPDATE_INCOME_EXPENSE_FULFILLED: "UPDATE_INCOME_EXPENSE_FULFILLED",
  
  RESET_INCOME_EXPENSE: "RESET_INCOME_EXPENSE",
  SHOW_INCOME_EXPENSE_FORM: "SHOW_INCOME_EXPENSE_FORM"
};