export default {
  REQUEST_OPERATION_RECORD: "REQUEST_OPERATION_RECORD",
  REQUEST_OPERATION_RECORD_PENDING: "REQUEST_OPERATION_RECORD_PENDING",
  REQUEST_OPERATION_RECORD_REJECTED: "REQUEST_OPERATION_RECORD_REJECTED",
  REQUEST_OPERATION_RECORD_FULFILLED: "REQUEST_OPERATION_RECORD_FULFILLED",

  ARCHIVE_OPERATION_RECORD: "ARCHIVE_OPERATION_RECORD",
  ARCHIVE_OPERATION_RECORD_PENDING: "ARCHIVE_OPERATION_RECORD_PENDING",
  ARCHIVE_OPERATION_RECORD_REJECTED: "ARCHIVE_OPERATION_RECORD_REJECTED",
  ARCHIVE_OPERATION_RECORD_FULFILLED: "ARCHIVE_OPERATION_RECORD_FULFILLED",

  ADD_OPERATION_RECORD: "ADD_OPERATION_RECORD",
  ADD_OPERATION_RECORD_PENDING: "ADD_OPERATION_RECORD_PENDING",
  ADD_OPERATION_RECORD_REJECTED: "ADD_OPERATION_RECORD_REJECTED",
  ADD_OPERATION_RECORD_FULFILLED: "ADD_OPERATION_RECORD_FULFILLED",

  UPDATE_OPERATION_RECORD: "UPDATE_OPERATION_RECORD",
  UPDATE_OPERATION_RECORD_PENDING: "UPDATE_OPERATION_RECORD_PENDING",
  UPDATE_OPERATION_RECORD_REJECTED: "UPDATE_OPERATION_RECORD_REJECTED",
  UPDATE_OPERATION_RECORD_FULFILLED: "UPDATE_OPERATION_RECORD_FULFILLED",

  RESET_OPERATION_RECORD: "RESET_OPERATION_RECORD",
  SHOW_OPERATION_RECORD_FORM: "SHOW_OPERATION_RECORD_FORM"
};