export default {
  REQUEST_PAYMENT_METHOD: "REQUEST_PAYMENT_METHOD",
  REQUEST_PAYMENT_METHOD_PENDING: "REQUEST_PAYMENT_METHOD_PENDING",
  REQUEST_PAYMENT_METHOD_REJECTED: "REQUEST_PAYMENT_METHOD_REJECTED",
  REQUEST_PAYMENT_METHOD_FULFILLED: "REQUEST_PAYMENT_METHOD_FULFILLED",

  ARCHIVE_PAYMENT_METHOD: "ARCHIVE_PAYMENT_METHOD",
  ARCHIVE_PAYMENT_METHOD_PENDING: "ARCHIVE_PAYMENT_METHOD_PENDING",
  ARCHIVE_PAYMENT_METHOD_REJECTED: "ARCHIVE_PAYMENT_METHOD_REJECTED",
  ARCHIVE_PAYMENT_METHOD_FULFILLED: "ARCHIVE_PAYMENT_METHOD_FULFILLED",

  ADD_PAYMENT_METHOD: "ADD_PAYMENT_METHOD",
  ADD_PAYMENT_METHOD_PENDING: "ADD_PAYMENT_METHOD_PENDING",
  ADD_PAYMENT_METHOD_REJECTED: "ADD_PAYMENT_METHOD_REJECTED",
  ADD_PAYMENT_METHOD_FULFILLED: "ADD_PAYMENT_METHOD_FULFILLED",

  UPDATE_PAYMENT_METHOD: "UPDATE_PAYMENT_METHOD",
  UPDATE_PAYMENT_METHOD_PENDING: "UPDATE_PAYMENT_METHOD_PENDING",
  UPDATE_PAYMENT_METHOD_REJECTED: "UPDATE_PAYMENT_METHOD_REJECTED",
  UPDATE_PAYMENT_METHOD_FULFILLED: "UPDATE_PAYMENT_METHOD_FULFILLED",

  RESET_PAYMENT_METHOD: "RESET_PAYMENT_METHOD",
  SHOW_PAYMENT_METHOD_FORM: "SHOW_PAYMENT_METHOD_FORM"
};