
export const REQUEST_PAYMENT_METHOD            = "REQUEST_PAYMENT_METHOD";
export const REQUEST_PAYMENT_METHOD_PENDING    = "REQUEST_PAYMENT_METHOD_PENDING";
export const REQUEST_PAYMENT_METHOD_REJECTED   = "REQUEST_PAYMENT_METHOD_REJECTED";
export const REQUEST_PAYMENT_METHOD_FULFILLED  = "REQUEST_PAYMENT_METHOD_FULFILLED";

export const ARCHIVE_PAYMENT_METHOD  		   = "ARCHIVE_PAYMENT_METHOD";
export const ARCHIVE_PAYMENT_METHOD_PENDING    = "ARCHIVE_PAYMENT_METHOD_PENDING";
export const ARCHIVE_PAYMENT_METHOD_REJECTED   = "ARCHIVE_PAYMENT_METHOD_REJECTED";
export const ARCHIVE_PAYMENT_METHOD_FULFILLED  = "ARCHIVE_PAYMENT_METHOD_FULFILLED";

export const ADD_PAYMENT_METHOD  		   = "ADD_PAYMENT_METHOD";
export const ADD_PAYMENT_METHOD_PENDING    = "ADD_PAYMENT_METHOD_PENDING";
export const ADD_PAYMENT_METHOD_REJECTED   = "ADD_PAYMENT_METHOD_REJECTED";
export const ADD_PAYMENT_METHOD_FULFILLED  = "ADD_PAYMENT_METHOD_FULFILLED";

export const UPDATE_PAYMENT_METHOD  		    = "UPDATE_PAYMENT_METHOD";
export const UPDATE_PAYMENT_METHOD_PENDING    = "UPDATE_PAYMENT_METHOD_PENDING";
export const UPDATE_PAYMENT_METHOD_REJECTED   = "UPDATE_PAYMENT_METHOD_REJECTED";
export const UPDATE_PAYMENT_METHOD_FULFILLED  = "UPDATE_PAYMENT_METHOD_FULFILLED";

export const RESET_PAYMENT_METHOD       = "RESET_PAYMENT_METHOD";
export const SHOW_PAYMENT_METHOD_FORM   = "SHOW_PAYMENT_METHOD_FORM";