export default {
  REQUEST_PRIVILEGE: "REQUEST_PRIVILEGE",
  REQUEST_PRIVILEGE_PENDING: "REQUEST_PRIVILEGE_PENDING",
  REQUEST_PRIVILEGE_REJECTED: "REQUEST_PRIVILEGE_REJECTED",
  REQUEST_PRIVILEGE_FULFILLED: "REQUEST_PRIVILEGE_FULFILLED",

  UPDATE_PRIVILEGE: "UPDATE_PRIVILEGE",
  UPDATE_PRIVILEGE_PENDING: "UPDATE_PRIVILEGE_PENDING",
  UPDATE_PRIVILEGE_REJECTED: "UPDATE_PRIVILEGE_REJECTED",
  UPDATE_PRIVILEGE_FULFILLED: "UPDATE_PRIVILEGE_FULFILLED",
};