export default {
  REQUEST_PRIVILEGE: "REQUEST_PRIVILEGE",
  REQUEST_PRIVILEGE_PENDING: "REQUEST_PRIVILEGE_PENDING",
  REQUEST_PRIVILEGE_REJECTED: "REQUEST_PRIVILEGE_REJECTED",
  REQUEST_PRIVILEGE_FULFILLED: "REQUEST_PRIVILEGE_FULFILLED",

  UPDATE_PRIVILEGE: "UPDATE_PRIVILEGE",
  UPDATE_PRIVILEGE_PENDING: "UPDATE_PRIVILEGE_PENDING",
  UPDATE_PRIVILEGE_REJECTED: "UPDATE_PRIVILEGE_REJECTED",
  UPDATE_PRIVILEGE_FULFILLED: "UPDATE_PRIVILEGE_FULFILLED",

  CHECK_PERMISSION: "CHECK_PERMISSION",
  CHECK_PERMISSION_PENDING: "CHECK_PERMISSION_PENDING",
  CHECK_PERMISSION_REJECTED: "CHECK_PERMISSION_REJECTED",
  CHECK_PERMISSION_FULFILLED: "CHECK_PERMISSION_FULFILLED",

  RESET_CHECK_PERMISSION: "RESET_CHECK_PERMISSION" 
};