export default {
  REQUEST_RECEIPT: "REQUEST_RECEIPT",
  REQUEST_RECEIPT_PENDING: "REQUEST_RECEIPT_PENDING",
  REQUEST_RECEIPT_REJECTED: "REQUEST_RECEIPT_REJECTED",
  REQUEST_RECEIPT_FULFILLED: "REQUEST_RECEIPT_FULFILLED",

  ARCHIVE_RECEIPT: "ARCHIVE_RECEIPT",
  ARCHIVE_RECEIPT_PENDING: "ARCHIVE_RECEIPT_PENDING",
  ARCHIVE_RECEIPT_REJECTED: "ARCHIVE_RECEIPT_REJECTED",
  ARCHIVE_RECEIPT_FULFILLED: "ARCHIVE_RECEIPT_FULFILLED",

  ADD_RECEIPT: "ADD_RECEIPT",
  ADD_RECEIPT_PENDING: "ADD_RECEIPT_PENDING",
  ADD_RECEIPT_REJECTED: "ADD_RECEIPT_REJECTED",
  ADD_RECEIPT_FULFILLED: "ADD_RECEIPT_FULFILLED",

  UPDATE_RECEIPT: "UPDATE_RECEIPT",
  UPDATE_RECEIPT_PENDING: "UPDATE_RECEIPT_PENDING",
  UPDATE_RECEIPT_REJECTED: "UPDATE_RECEIPT_REJECTED",
  UPDATE_RECEIPT_FULFILLED: "UPDATE_RECEIPT_FULFILLED",

  RESET_RECEIPT: "RESET_RECEIPT",
  SHOW_RECEIPT_FORM: "SHOW_RECEIPT_FORM"
};