export default {
  REQUEST_ROLE_PRIVILEGE: "REQUEST_ROLE_PRIVILEGE",
  REQUEST_ROLE_PRIVILEGE_PENDING: "REQUEST_ROLE_PRIVILEGE_PENDING",
  REQUEST_ROLE_PRIVILEGE_REJECTED: "REQUEST_ROLE_PRIVILEGE_REJECTED",
  REQUEST_ROLE_PRIVILEGE_FULFILLED: "REQUEST_ROLE_PRIVILEGE_FULFILLED"
};