export default {
  REQUEST_ROLE_ACCESS: "REQUEST_ROLE_ACCESS",
  REQUEST_ROLE_ACCESS_PENDING: "REQUEST_ROLE_ACCESS_PENDING",
  REQUEST_ROLE_ACCESS_REJECTED: "REQUEST_ROLE_ACCESS_REJECTED",
  REQUEST_ROLE_ACCESS_FULFILLED: "REQUEST_ROLE_ACCESS_FULFILLED",

  DETAIL_ROLE_ACCESS: "DETAIL_ROLE_ACCESS",
  DETAIL_ROLE_ACCESS_PENDING: "DETAIL_ROLE_ACCESS_PENDING",
  DETAIL_ROLE_ACCESS_REJECTED: "DETAIL_ROLE_ACCESS_REJECTED",
  DETAIL_ROLE_ACCESS_FULFILLED: "DETAIL_ROLE_ACCESS_FULFILLED",

  ARCHIVE_ROLE_ACCESS: "ARCHIVE_ROLE_ACCESS",
  ARCHIVE_ROLE_ACCESS_PENDING: "ARCHIVE_ROLE_ACCESS_PENDING",
  ARCHIVE_ROLE_ACCESS_REJECTED: "ARCHIVE_ROLE_ACCESS_REJECTED",
  ARCHIVE_ROLE_ACCESS_FULFILLED: "ARCHIVE_ROLE_ACCESS_FULFILLED",

  ADD_ROLE_ACCESS: "ADD_ROLE_ACCESS",
  ADD_ROLE_ACCESS_PENDING: "ADD_ROLE_ACCESS_PENDING",
  ADD_ROLE_ACCESS_REJECTED: "ADD_ROLE_ACCESS_REJECTED",
  ADD_ROLE_ACCESS_FULFILLED: "ADD_ROLE_ACCESS_FULFILLED",

  UPDATE_ROLE_ACCESS: "UPDATE_ROLE_ACCESS",
  UPDATE_ROLE_ACCESS_PENDING: "UPDATE_ROLE_ACCESS_PENDING",
  UPDATE_ROLE_ACCESS_REJECTED: "UPDATE_ROLE_ACCESS_REJECTED",
  UPDATE_ROLE_ACCESS_FULFILLED: "UPDATE_ROLE_ACCESS_FULFILLED",

  RESET_ROLE_ACCESS: "RESET_ROLE_ACCESS",
  SHOW_ROLE_ACCESS_FORM: "SHOW_ROLE_ACCESS_FORM"
};