export default {
  REQUEST_ROLE_PRIVILEGE: "REQUEST_ROLE_PRIVILEGE",
  REQUEST_ROLE_PRIVILEGE_PENDING: "REQUEST_ROLE_PRIVILEGE_PENDING",
  REQUEST_ROLE_PRIVILEGE_REJECTED: "REQUEST_ROLE_PRIVILEGE_REJECTED",
  REQUEST_ROLE_PRIVILEGE_FULFILLED: "REQUEST_ROLE_PRIVILEGE_FULFILLED",

  UPDATE_ROLE_PRIVILEGE: "UPDATE_ROLE_PRIVILEGE",
  UPDATE_ROLE_PRIVILEGE_PENDING: "UPDATE_ROLE_PRIVILEGE_PENDING",
  UPDATE_ROLE_PRIVILEGE_REJECTED: "UPDATE_ROLE_PRIVILEGE_REJECTED",
  UPDATE_ROLE_PRIVILEGE_FULFILLED: "UPDATE_ROLE_PRIVILEGE_FULFILLED",

  RESET_ROLE_PRIVILEGE: "RESET_ROLE_PRIVILEGE",
  RESET_REQUEST_ROLE_PRIVILEGE_PARTIAL: "RESET_REQUEST_ROLE_PRIVILEGE_PARTIAL"
};