export default {
  REQUEST_LOCATION: "REQUEST_LOCATION",
  REQUEST_LOCATION_PENDING: "REQUEST_LOCATION_PENDING",
  REQUEST_LOCATION_REJECTED: "REQUEST_LOCATION_REJECTED",
  REQUEST_LOCATION_FULFILLED: "REQUEST_LOCATION_FULFILLED",

  REQUEST_LOCATION_ACCESS: "REQUEST_LOCATION_ACCESS",
  REQUEST_LOCATION_ACCESS_PENDING: "REQUEST_LOCATION_ACCESS_PENDING",
  REQUEST_LOCATION_ACCESS_REJECTED: "REQUEST_LOCATION_ACCESS_REJECTED",
  REQUEST_LOCATION_ACCESS_FULFILLED: "REQUEST_LOCATION_ACCESS_FULFILLED",

  ARCHIVE_LOCATION: "ARCHIVE_LOCATION",
  ARCHIVE_LOCATION_PENDING: "ARCHIVE_LOCATION_PENDING",
  ARCHIVE_LOCATION_REJECTED: "ARCHIVE_LOCATION_REJECTED",
  ARCHIVE_LOCATION_FULFILLED: "ARCHIVE_LOCATION_FULFILLED",

  ADD_LOCATION: "ADD_LOCATION",
  ADD_LOCATION_PENDING: "ADD_LOCATION_PENDING",
  ADD_LOCATION_REJECTED: "ADD_LOCATION_REJECTED",
  ADD_LOCATION_FULFILLED: "ADD_LOCATION_FULFILLED",

  UPDATE_LOCATION: "UPDATE_LOCATION",
  UPDATE_LOCATION_PENDING: "UPDATE_LOCATION_PENDING",
  UPDATE_LOCATION_REJECTED: "UPDATE_LOCATION_REJECTED",
  UPDATE_LOCATION_FULFILLED: "UPDATE_LOCATION_FULFILLED",

  RESET_STORE_LOCATION: "RESET_STORE_LOCATION",
  SHOW_STORE_LOCATION_FORM: "SHOW_STORE_LOCATION_FORM"
};