export default {
  REQUEST_STORE_LANGUAGE: "REQUEST_STORE_LANGUAGE",
  REQUEST_STORE_LANGUAGE_PENDING: "REQUEST_STORE_LANGUAGE_PENDING",
  REQUEST_STORE_LANGUAGE_REJECTED: "REQUEST_STORE_LANGUAGE_REJECTED",
  REQUEST_STORE_LANGUAGE_FULFILLED: "REQUEST_STORE_LANGUAGE_FULFILLED",

  ARCHIVE_STORE_LANGUAGE: "ARCHIVE_STORE_LANGUAGE",
  ARCHIVE_STORE_LANGUAGE_PENDING: "ARCHIVE_STORE_LANGUAGE_PENDING",
  ARCHIVE_STORE_LANGUAGE_REJECTED: "ARCHIVE_STORE_LANGUAGE_REJECTED",
  ARCHIVE_STORE_LANGUAGE_FULFILLED: "ARCHIVE_STORE_LANGUAGE_FULFILLED",

  ADD_STORE_LANGUAGE: "ADD_STORE_LANGUAGE",
  ADD_STORE_LANGUAGE_PENDING: "ADD_STORE_LANGUAGE_PENDING",
  ADD_STORE_LANGUAGE_REJECTED: "ADD_STORE_LANGUAGE_REJECTED",
  ADD_STORE_LANGUAGE_FULFILLED: "ADD_STORE_LANGUAGE_FULFILLED",

  UPDATE_STORE_LANGUAGE: "UPDATE_STORE_LANGUAGE",
  UPDATE_STORE_LANGUAGE_PENDING: "UPDATE_STORE_LANGUAGE_PENDING",
  UPDATE_STORE_LANGUAGE_REJECTED: "UPDATE_STORE_LANGUAGE_REJECTED",
  UPDATE_STORE_LANGUAGE_FULFILLED: "UPDATE_STORE_LANGUAGE_FULFILLED",

  RESET_STORE_LANGUAGE: "RESET_STORE_LANGUAGE",
  SHOW_STORE_LANGUAGE_FORM: "SHOW_PAYMENT_METHOD_FORM"
};
