export default {
  REQUEST_STORE_ACCOUNT: "REQUEST_STORE_ACCOUNT",
  REQUEST_STORE_ACCOUNT_PENDING: "REQUEST_STORE_ACCOUNT_PENDING",
  REQUEST_STORE_ACCOUNT_REJECTED: "REQUEST_STORE_ACCOUNT_REJECTED",
  REQUEST_STORE_ACCOUNT_FULFILLED: "REQUEST_STORE_ACCOUNT_FULFILLED",
  
  ARCHIVE_STORE_ACCOUNT: "ARCHIVE_STORE_ACCOUNT",
  ARCHIVE_STORE_ACCOUNT_PENDING: "ARCHIVE_STORE_ACCOUNT_PENDING",
  ARCHIVE_STORE_ACCOUNT_REJECTED: "ARCHIVE_STORE_ACCOUNT_REJECTED",
  ARCHIVE_STORE_ACCOUNT_FULFILLED: "ARCHIVE_STORE_ACCOUNT_FULFILLED",
  
  ADD_STORE_ACCOUNT: "ADD_PAYMENT_METHOD",
  ADD_STORE_ACCOUNT_PENDING: "ADD_STORE_ACCOUNT_PENDING",
  ADD_STORE_ACCOUNT_REJECTED: "ADD_STORE_ACCOUNT_REJECTED",
  ADD_STORE_ACCOUNT_FULFILLED: "ADD_STORE_ACCOUNT_FULFILLED",
  
  UPDATE_STORE_ACCOUNT: "UPDATE_STORE_ACCOUNT",
  UPDATE_STORE_ACCOUNT_PENDING: "UPDATE_STORE_ACCOUNT_PENDING",
  UPDATE_STORE_ACCOUNT_REJECTED: "UPDATE_STORE_ACCOUNT_REJECTED",
  UPDATE_STORE_ACCOUNT_FULFILLED: "UPDATE_STORE_ACCOUNT_FULFILLED",
  
  RESET_STORE_ACCOUNT: "RESET_STORE_ACCOUNT",
  SHOW_STORE_ACCOUNT_FORM: "SHOW_STORE_ACCOUNT_FORM"
};