export default {
  REQUEST_STORE_LOCATION: "REQUEST_STORE_LOCATION",
  REQUEST_STORE_LOCATION_PENDING: "REQUEST_STORE_LOCATION_PENDING",
  REQUEST_STORE_LOCATION_REJECTED: "REQUEST_STORE_LOCATION_REJECTED",
  REQUEST_STORE_LOCATION_FULFILLED: "REQUEST_STORE_LOCATION_FULFILLED",

  ARCHIVE_STORE_LOCATION: "ARCHIVE_STORE_LOCATION",
  ARCHIVE_STORE_LOCATION_PENDING: "ARCHIVE_STORE_LOCATION_PENDING",
  ARCHIVE_STORE_LOCATION_REJECTED: "ARCHIVE_STORE_LOCATION_REJECTED",
  ARCHIVE_STORE_LOCATION_FULFILLED: "ARCHIVE_STORE_LOCATION_FULFILLED",

  ADD_STORE_LOCATION: "ADD_STORE_LOCATION",
  ADD_STORE_LOCATION_PENDING: "ADD_STORE_LOCATION_PENDING",
  ADD_STORE_LOCATION_REJECTED: "ADD_STORE_LOCATION_REJECTED",
  ADD_STORE_LOCATION_FULFILLED: "ADD_STORE_LOCATION_FULFILLED",

  UPDATE_STORE_LOCATION: "UPDATE_STORE_LOCATION",
  UPDATE_STORE_LOCATION_PENDING: "UPDATE_STORE_LOCATION_PENDING",
  UPDATE_STORE_LOCATION_REJECTED: "UPDATE_STORE_LOCATION_REJECTED",
  UPDATE_STORE_LOCATION_FULFILLED: "UPDATE_STORE_LOCATION_FULFILLED",

  RESET_STORE_LOCATION: "RESET_STORE_LOCATION",
  SHOW_STORE_LOCATION_FORM: "SHOW_STORE_LOCATION_FORM"
};