export const REQUEST_STORE_LOCATION            = "REQUEST_STORE_LOCATION";
export const REQUEST_STORE_LOCATION_PENDING    = "REQUEST_STORE_LOCATION_PENDING";
export const REQUEST_STORE_LOCATION_REJECTED   = "REQUEST_STORE_LOCATION_REJECTED";
export const REQUEST_STORE_LOCATION_FULFILLED  = "REQUEST_STORE_LOCATION_FULFILLED";

export const ARCHIVE_STORE_LOCATION            = "ARCHIVE_STORE_LOCATION";
export const ARCHIVE_STORE_LOCATION_PENDING    = "ARCHIVE_STORE_LOCATION_PENDING";
export const ARCHIVE_STORE_LOCATION_REJECTED   = "ARCHIVE_STORE_LOCATION_REJECTED";
export const ARCHIVE_STORE_LOCATION_FULFILLED  = "ARCHIVE_STORE_LOCATION_FULFILLED";

export const ADD_STORE_LOCATION            = "ADD_STORE_LOCATION";
export const ADD_STORE_LOCATION_PENDING    = "ADD_STORE_LOCATION_PENDING";
export const ADD_STORE_LOCATION_REJECTED   = "ADD_STORE_LOCATION_REJECTED";
export const ADD_STORE_LOCATION_FULFILLED  = "ADD_STORE_LOCATION_FULFILLED";