export default {
  REQUEST_LANGUAGE: "REQUEST_LANGUAGE",
  REQUEST_LANGUAGE_PENDING: "REQUEST_LANGUAGE_PENDING",
  REQUEST_LANGUAGE_REJECTED: "REQUEST_LANGUAGE_REJECTED",
  REQUEST_LANGUAGE_FULFILLED: "REQUEST_LANGUAGE_FULFILLED",

  ARCHIVE_LANGUAGE: "ARCHIVE_LANGUAGE",
  ARCHIVE_LANGUAGE_PENDING: "ARCHIVE_LANGUAGE_PENDING",
  ARCHIVE_LANGUAGE_REJECTED: "ARCHIVE_LANGUAGE_REJECTED",
  ARCHIVE_LANGUAGE_FULFILLED: "ARCHIVE_LANGUAGE_FULFILLED",

  ADD_LANGUAGE: "ADD_LANGUAGE",
  ADD_LANGUAGE_PENDING: "ADD_LANGUAGE_PENDING",
  ADD_LANGUAGE_REJECTED: "ADD_LANGUAGE_REJECTED",
  ADD_LANGUAGE_FULFILLED: "ADD_LANGUAGE_FULFILLED",

  UPDATE_LANGUAGE: "UPDATE_LANGUAGE",
  UPDATE_LANGUAGE_PENDING: "UPDATE_LANGUAGE_PENDING",
  UPDATE_LANGUAGE_REJECTED: "UPDATE_LANGUAGE_REJECTED",
  UPDATE_LANGUAGE_FULFILLED: "UPDATE_LANGUAGE_FULFILLED",

  RESET_LANGUAGE: "RESET_LANGUAGE",
  RESET_LANGUAGE_ADD: "RESET_LANGUAGE_ADD",
  SHOW_LANGUAGE_FORM: "SHOW_LANGUAGE_FORM"
};
