export const REQUEST_TAX            = "REQUEST_TAX";
export const REQUEST_TAX_PENDING    = "REQUEST_TAX_PENDING";
export const REQUEST_TAX_REJECTED   = "REQUEST_TAX_REJECTED";
export const REQUEST_TAX_FULFILLED  = "REQUEST_TAX_FULFILLED";

export const ARCHIVE_TAX = "ARCHIVE_TAX";