export const REQUEST_TAX            = "REQUEST_TAX";
export const REQUEST_TAX_PENDING    = "REQUEST_TAX_PENDING";
export const REQUEST_TAX_REJECTED   = "REQUEST_TAX_REJECTED";
export const REQUEST_TAX_FULFILLED  = "REQUEST_TAX_FULFILLED";

export const ARCHIVE_TAX            = "ARCHIVE_TAX";
export const ARCHIVE_TAX_PENDING    = "ARCHIVE_TAX_PENDING";
export const ARCHIVE_TAX_REJECTED   = "ARCHIVE_TAX_REJECTED";
export const ARCHIVE_TAX_FULFILLED  = "ARCHIVE_TAX_FULFILLED";

export const ADD_TAX            = "ADD_TAX";
export const ADD_TAX_PENDING    = "ADD_TAX_PENDING";
export const ADD_TAX_REJECTED   = "ADD_TAX_REJECTED";
export const ADD_TAX_FULFILLED  = "ADD_TAX_FULFILLED";

export const UPDATE_TAX            = "UPDATE_TAX";
export const UPDATE_TAX_PENDING    = "UPDATE_TAX_PENDING";
export const UPDATE_TAX_REJECTED   = "UPDATE_TAX_REJECTED";
export const UPDATE_TAX_FULFILLED  = "UPDATE_TAX_FULFILLED";

export const RESET_TAX       = "RESET_TAX";
export const SHOW_TAX_FORM   = "SHOW_TAX_FORM";