export default {
  ACTIVE: 1,
  DEACTIVE: 0,
  ALL_STATE: 2,
  IS_SYSTEM: 1,
  IS_DEFAULT: 1,
  CURRENCY_POSITION: {BEFORE: 0, AFTER: 1},
  GENERATE_PRODUCT_CODE: {AUTO: 0, MANAUL: 1},
  OPERATION_TYPE: {INCOME: 0, EXPENSE: 1},
  GENDER: { MALE: 0, FEMALE: 1 }
};