export default {
  ACTIVE: 1,
  ARCHIVE: 3,
  DEACTIVE: 0,
  ALL_STATE: 2,
  IS_SYSTEM: 1,
  IS_DEFAULT: 1,
  NOT_DEFAULT: 0,
  CURRENCY_POSITION: {BEFORE: 0, AFTER: 1},
  GENERATE_PRODUCT_CODE: {MANAUL: 0, AUTO: 1},
  OPERATION_TYPE: {INCOME: 1, EXPENSE: 0},
  GENDER: {
    MALE: 0,
    FEMALE: 1
  },
  IMAGE_SPACE: {
    GENERAL: "general",
    EMPLOYEE: "employee",
    PRODUCT: "product"
  }
};