export default {
  BOOKING_STATUS: {
    BOOKED: "BOOKEN",
    SERVING: "SERVING",
    SERVED: "SERVED",
    DELAYED: "DELAYED",
    CANCELLED: "CANCELLED"
  },
  MARK_COMPLETED: "MARK_AS_COMPLETE",
  MARK_CANCELLED: "MARK_AS_CANCELLED",
  MARK_DELAY: "MARK_AS_DELAY"
};