export default {
  REQUEST_BRAND: "REQUEST_BRAND",
  REQUEST_BRAND_PENDING: "REQUEST_BRAND_PENDING",
  REQUEST_BRAND_REJECTED: "REQUEST_BRAND_REJECTED",
  REQUEST_BRAND_FULFILLED: "REQUEST_BRAND_FULFILLED",
  
  ARCHIVE_BRAND: "ARCHIVE_BRAND",
  ARCHIVE_BRAND_PENDING: "ARCHIVE_BRAND_PENDING",
  ARCHIVE_BRAND_REJECTED: "ARCHIVE_BRAND_REJECTED",
  ARCHIVE_BRAND_FULFILLED: "ARCHIVE_BRAND_FULFILLED",
  
  ADD_BRAND: "ADD_BRAND",
  ADD_BRAND_PENDING: "ADD_BRAND_PENDING",
  ADD_BRAND_REJECTED: "ADD_BRAND_REJECTED",
  ADD_BRAND_FULFILLED: "ADD_BRAND_FULFILLED",
  
  UPDATE_BRAND: "UPDATE_BRAND",
  UPDATE_BRAND_PENDING: "UPDATE_BRAND_PENDING",
  UPDATE_BRAND_REJECTED: "UPDATE_BRAND_REJECTED",
  UPDATE_BRAND_FULFILLED: "UPDATE_BRAND_FULFILLED",
  
  RESET_BRAND: "RESET_BRAND",
  SHOW_BRAND_FORM: "SHOW_BRAND_FORM"
};