export default {
  REQUEST_CONDITION: "REQUEST_CONDITION",
  REQUEST_CONDITION_PENDING: "REQUEST_CONDITION_PENDING",
  REQUEST_CONDITION_REJECTED: "REQUEST_CONDITION_REJECTED",
  REQUEST_CONDITION_FULFILLED: "REQUEST_CONDITION_FULFILLED",
  
  ARCHIVE_CONDITION: "ARCHIVE_CONDITION",
  ARCHIVE_CONDITION_PENDING: "ARCHIVE_CONDITION_PENDING",
  ARCHIVE_CONDITION_REJECTED: "ARCHIVE_CONDITION_REJECTED",
  ARCHIVE_CONDITION_FULFILLED: "ARCHIVE_CONDITION_FULFILLED",
  
  ADD_CONDITION: "ADD_CONDITION",
  ADD_CONDITION_PENDING: "ADD_CONDITION_PENDING",
  ADD_CONDITION_REJECTED: "ADD_CONDITION_REJECTED",
  ADD_CONDITION_FULFILLED: "ADD_CONDITION_FULFILLED",
  
  UPDATE_CONDITION: "UPDATE_CONDITION",
  UPDATE_CONDITION_PENDING: "UPDATE_CONDITION_PENDING",
  UPDATE_CONDITION_REJECTED: "UPDATE_CONDITION_REJECTED",
  UPDATE_CONDITION_FULFILLED: "UPDATE_CONDITION_FULFILLED",
  
  RESET_CONDITION: "RESET_CONDITION",
  SHOW_CONDITION_FORM: "SHOW_CONDITION_FORM"
};