export default {
  REQUEST_PRODUCTS_TYPE: "REQUEST_PRODUCTS_TYPE",
  REQUEST_PRODUCTS_TYPE_PENDING: "REQUEST_PRODUCTS_TYPE_PENDING",
  REQUEST_PRODUCTS_TYPE_REJECTED: "REQUEST_PRODUCTS_TYPE_REJECTED",
  REQUEST_PRODUCTS_TYPE_FULFILLED: "REQUEST_PRODUCTS_TYPE_FULFILLED",
  
  ARCHIVE_PRODUCTS_TYPE: "ARCHIVE_PRODUCTS_TYPE",
  ARCHIVE_PRODUCTS_TYPE_PENDING: "ARCHIVE_PRODUCTS_TYPE_PENDING",
  ARCHIVE_PRODUCTS_TYPE_REJECTED: "ARCHIVE_PRODUCTS_TYPE_REJECTED",
  ARCHIVE_PRODUCTS_TYPE_FULFILLED: "ARCHIVE_PRODUCTS_TYPE_FULFILLED",
  
  ADD_PRODUCTS_TYPE: "ADD_PRODUCTS_TYPE",
  ADD_PRODUCTS_TYPE_PENDING: "ADD_PRODUCTS_TYPE_PENDING",
  ADD_PRODUCTS_TYPE_REJECTED: "ADD_PRODUCTS_TYPE_REJECTED",
  ADD_PRODUCTS_TYPE_FULFILLED: "ADD_PRODUCTS_TYPE_FULFILLED",
  
  UPDATE_PRODUCTS_TYPE: "UPDATE_PRODUCTS_TYPE",
  UPDATE_PRODUCTS_TYPE_PENDING: "UPDATE_PRODUCTS_TYPE_PENDING",
  UPDATE_PRODUCTS_TYPE_REJECTED: "UPDATE_PRODUCTS_TYPE_REJECTED",
  UPDATE_PRODUCTS_TYPE_FULFILLED: "UPDATE_PRODUCTS_TYPE_FULFILLED",

  DETAIL_PRODUCTS_TYPE: "DETAIL_PRODUCTS_TYPE",
  DETAIL_PRODUCTS_TYPE_PENDING: "DETAIL_PRODUCTS_TYPE_PENDING",
  DETAIL_PRODUCTS_TYPE_REJECTED: "DETAIL_PRODUCTS_TYPE_REJECTED",
  DETAIL_PRODUCTS_TYPE_FULFILLED: "DETAIL_PRODUCTS_TYPE_FULFILLED",
  RESET_DETAIL_PRODUCTS_TYPE: "RESET_DETAIL_PRODUCTS_TYPE",
  
  RESET_PRODUCTS_TYPE: "RESET_PRODUCTS_TYPE",
  SHOW_PRODUCTS_TYPE_FORM: "SHOW_PRODUCTS_TYPE_FORM"
};