export default {
  REQUEST_PRODUCT: "REQUEST_PRODUCT",
  REQUEST_PRODUCT_PENDING: "REQUEST_PRODUCT_PENDING",
  REQUEST_PRODUCT_REJECTED: "REQUEST_PRODUCT_REJECTED",
  REQUEST_PRODUCT_FULFILLED: "REQUEST_PRODUCT_FULFILLED",

  UPLOAD_PRODUCT_IMAGE: "UPLOAD_PRODUCT_IMAGE",
  UPLOAD_PRODUCT_IMAGE_PENDING: "UPLOAD_PRODUCT_IMAGE_PENDING",
  UPLOAD_PRODUCT_IMAGE_REJECTED: "UPLOAD_PRODUCT_IMAGE_REJECTED",
  UPLOAD_PRODUCT_IMAGE_FULFILLED: "UPLOAD_PRODUCT_IMAGE_FULFILLED",

  REQUEST_PRODUCT_LOG: "REQUEST_PRODUCT_LOG",
  REQUEST_PRODUCT_LOG_PENDING: "REQUEST_PRODUCT_LOG_PENDING",
  REQUEST_PRODUCT_LOG_REJECTED: "REQUEST_PRODUCT_LOG_REJECTED",
  REQUEST_PRODUCT_LOG_FULFILLED: "REQUEST_PRODUCT_LOG_FULFILLED",

  REQUEST_PRODUCT_COST_LOG: "REQUEST_PRODUCT_COST_LOG",
  REQUEST_PRODUCT_COST_LOG_PENDING: "REQUEST_PRODUCT_COST_LOG_PENDING",
  REQUEST_PRODUCT_COST_LOG_REJECTED: "REQUEST_PRODUCT_COST_LOG_REJECTED",
  REQUEST_PRODUCT_COST_LOG_FULFILLED: "REQUEST_PRODUCT_COST_LOG_FULFILLED",

  SEARCH_PRODUCT: "SEARCH_PRODUCT",
  SEARCH_PRODUCT_PENDING: "SEARCH_PRODUCT_PENDING",
  SEARCH_PRODUCT_REJECTED: "SEARCH_PRODUCT_REJECTED",
  SEARCH_PRODUCT_FULFILLED: "SEARCH_PRODUCT_FULFILLED",
  SEARCH_PRODUCT_RESET: "SEARCH_PRODUCT_RESET",
  
  ARCHIVE_PRODUCT: "ARCHIVE_PRODUCT",
  ARCHIVE_PRODUCT_PENDING: "ARCHIVE_PRODUCT_PENDING",
  ARCHIVE_PRODUCT_REJECTED: "ARCHIVE_PRODUCT_REJECTED",
  ARCHIVE_PRODUCT_FULFILLED: "ARCHIVE_PRODUCT_FULFILLED",

  ARCHIVE_VARIANT_PRODUCT: "ARCHIVE_VARIANT_PRODUCT",
  ARCHIVE_VARIANT_PRODUCT_PENDING: "ARCHIVE_VARIANT_PRODUCT_PENDING",
  ARCHIVE_VARIANT_PRODUCT_REJECTED: "ARCHIVE_VARIANT_PRODUCT_REJECTED",
  ARCHIVE_VARIANT_PRODUCT_FULFILLED: "ARCHIVE_VARIANT_PRODUCT_FULFILLED",
  RESET_ARCHIVE_VARIANT_PRODUCT: "RESET_ARCHIVE_VARIANT_PRODUCT",
  
  ADD_PRODUCT: "ADD_PRODUCT",
  ADD_PRODUCT_PENDING: "ADD_PRODUCT_PENDING",
  ADD_PRODUCT_REJECTED: "ADD_PRODUCT_REJECTED",
  ADD_PRODUCT_FULFILLED: "ADD_PRODUCT_FULFILLED",

  CLONE_PRODUCT: "CLONE_PRODUCT",
  CLONE_PRODUCT_PENDING: "CLONE_PRODUCT_PENDING",
  CLONE_PRODUCT_REJECTED: "CLONE_PRODUCT_REJECTED",
  CLONE_PRODUCT_FULFILLED: "CLONE_PRODUCT_FULFILLED",
  
  UPDATE_PRODUCT: "UPDATE_PRODUCT",
  UPDATE_PRODUCT_PENDING: "UPDATE_PRODUCT_PENDING",
  UPDATE_PRODUCT_REJECTED: "UPDATE_PRODUCT_REJECTED",
  UPDATE_PRODUCT_FULFILLED: "UPDATE_PRODUCT_FULFILLED",

  UPDATE_PARTIAL_PRODUCT: "UPDATE_PARTIAL_PRODUCT",
  UPDATE_PARTIAL_PRODUCT_PENDING: "UPDATE_PARTIAL_PRODUCT_PENDING",
  UPDATE_PARTIAL_PRODUCT_REJECTED: "UPDATE_PARTIAL_PRODUCT_REJECTED",
  UPDATE_PARTIAL_PRODUCT_FULFILLED: "UPDATE_PARTIAL_PRODUCT_FULFILLED",

  DETAIL_PRODUCTS: "DETAIL_PRODUCTS",
  DETAIL_PRODUCTS_PENDING: "DETAIL_PRODUCTS_PENDING",
  DETAIL_PRODUCTS_REJECTED: "DETAIL_PRODUCTS_REJECTED",
  DETAIL_PRODUCTS_FULFILLED: "DETAIL_PRODUCTS_FULFILLED",
  RESET_DETAIL_PRODUCTS: "RESET_DETAIL_PRODUCTS",
  PARTIAL_RESET_DETAIL_PRODUCTS: "PARTIAL_RESET_DETAIL_PRODUCTS",
  
  RESET_PRODUCT: "RESET_PRODUCT",
  SHOW_PRODUCT_FORM: "SHOW_PRODUCT_FORM"
};