export default {
  CHECK_PRODUCT_VARIANT: "CHECK_PRODUCT_VARIANT",
  CHECK_PRODUCT_VARIANT_PENDING: "CHECK_PRODUCT_VARIANT_PENDING",
  CHECK_PRODUCT_VARIANT_REJECTED: "CHECK_PRODUCT_VARIANT_REJECTED",
  CHECK_PRODUCT_VARIANT_FULFILLED: "CHECK_PRODUCT_VARIANT_FULFILLED",
  
  RESET_PRODUCT_VARIANT: "RESET_PRODUCT_VARIANT"
};