export default {
  REQUEST_PRODUCTS_TAG: "REQUEST_PRODUCTS_TAG",
  REQUEST_PRODUCTS_TAG_PENDING: "REQUEST_PRODUCTS_TAG_PENDING",
  REQUEST_PRODUCTS_TAG_REJECTED: "REQUEST_PRODUCTS_TAG_REJECTED",
  REQUEST_PRODUCTS_TAG_FULFILLED: "REQUEST_PRODUCTS_TAG_FULFILLED",
  
  ARCHIVE_PRODUCTS_TAG: "ARCHIVE_PRODUCTS_TAG",
  ARCHIVE_PRODUCTS_TAG_PENDING: "ARCHIVE_PRODUCTS_TAG_PENDING",
  ARCHIVE_PRODUCTS_TAG_REJECTED: "ARCHIVE_PRODUCTS_TAG_REJECTED",
  ARCHIVE_PRODUCTS_TAG_FULFILLED: "ARCHIVE_PRODUCTS_TAG_FULFILLED",
  
  ADD_PRODUCTS_TAG: "ADD_PRODUCTS_TAG",
  ADD_PRODUCTS_TAG_PENDING: "ADD_PRODUCTS_TAG_PENDING",
  ADD_PRODUCTS_TAG_REJECTED: "ADD_PRODUCTS_TAG_REJECTED",
  ADD_PRODUCTS_TAG_FULFILLED: "ADD_PRODUCTS_TAG_FULFILLED",
  
  UPDATE_PRODUCTS_TAG: "UPDATE_PRODUCTS_TAG",
  UPDATE_PRODUCTS_TAG_PENDING: "UPDATE_PRODUCTS_TAG_PENDING",
  UPDATE_PRODUCTS_TAG_REJECTED: "UPDATE_PRODUCTS_TAG_REJECTED",
  UPDATE_PRODUCTS_TAG_FULFILLED: "UPDATE_PRODUCTS_TAG_FULFILLED",
  
  RESET_PRODUCTS_TAG: "RESET_PRODUCTS_TAG",
  SHOW_PRODUCTS_TAG_FORM: "SHOW_PRODUCTS_TAG_FORM"
};