export default {
  REQUEST_UNIT: "REQUEST_UNIT",
  REQUEST_UNIT_PENDING: "REQUEST_UNIT_PENDING",
  REQUEST_UNIT_REJECTED: "REQUEST_UNIT_REJECTED",
  REQUEST_UNIT_FULFILLED: "REQUEST_UNIT_FULFILLED",
  REQUEST_UNIT_RESET: "REQUEST_UNIT_RESET",
  
  ARCHIVE_PRODUCTS_UNIT: "ARCHIVE_PRODUCTS_UNIT",
  ARCHIVE_PRODUCTS_UNIT_PENDING: "ARCHIVE_PRODUCTS_UNIT_PENDING",
  ARCHIVE_PRODUCTS_UNIT_REJECTED: "ARCHIVE_PRODUCTS_UNIT_REJECTED",
  ARCHIVE_PRODUCTS_UNIT_FULFILLED: "ARCHIVE_PRODUCTS_UNIT_FULFILLED",
  
  ADD_PRODUCTS_UNIT: "ADD_PRODUCTS_UNIT",
  ADD_PRODUCTS_UNIT_PENDING: "ADD_PRODUCTS_UNIT_PENDING",
  ADD_PRODUCTS_UNIT_REJECTED: "ADD_PRODUCTS_UNIT_REJECTED",
  ADD_PRODUCTS_UNIT_FULFILLED: "ADD_PRODUCTS_UNIT_FULFILLED",
  
  UPDATE_PRODUCTS_UNIT: "UPDATE_PRODUCTS_UNIT",
  UPDATE_PRODUCTS_UNIT_PENDING: "UPDATE_PRODUCTS_UNIT_PENDING",
  UPDATE_PRODUCTS_UNIT_REJECTED: "UPDATE_PRODUCTS_UNIT_REJECTED",
  UPDATE_PRODUCTS_UNIT_FULFILLED: "UPDATE_PRODUCTS_UNIT_FULFILLED",
  
  RESET_PRODUCTS_UNIT: "RESET_PRODUCTS_UNIT",
  SHOW_PRODUCTS_UNIT_FORM: "SHOW_PRODUCTS_UNIT_FORM"
};