export default {
  REQUEST_PRODUCT: "REQUEST_PRODUCT",
  REQUEST_PRODUCT_PENDING: "REQUEST_PRODUCT_PENDING",
  REQUEST_PRODUCT_REJECTED: "REQUEST_PRODUCT_REJECTED",
  REQUEST_PRODUCT_FULFILLED: "REQUEST_PRODUCT_FULFILLED",

  SEARCH_PRODUCT: "SEARCH_PRODUCT",
  SEARCH_PRODUCT_PENDING: "SEARCH_PRODUCT_PENDING",
  SEARCH_PRODUCT_REJECTED: "SEARCH_PRODUCT_REJECTED",
  SEARCH_PRODUCT_FULFILLED: "SEARCH_PRODUCT_FULFILLED",
  
  ARCHIVE_PRODUCT: "ARCHIVE_PRODUCT",
  ARCHIVE_PRODUCT_PENDING: "ARCHIVE_PRODUCT_PENDING",
  ARCHIVE_PRODUCT_REJECTED: "ARCHIVE_PRODUCT_REJECTED",
  ARCHIVE_PRODUCT_FULFILLED: "ARCHIVE_PRODUCT_FULFILLED",
  
  ADD_PRODUCT: "ADD_PRODUCT",
  ADD_PRODUCT_PENDING: "ADD_PRODUCT_PENDING",
  ADD_PRODUCT_REJECTED: "ADD_PRODUCT_REJECTED",
  ADD_PRODUCT_FULFILLED: "ADD_PRODUCT_FULFILLED",
  
  UPDATE_PRODUCT: "UPDATE_PRODUCT",
  UPDATE_PRODUCT_PENDING: "UPDATE_PRODUCT_PENDING",
  UPDATE_PRODUCT_REJECTED: "UPDATE_PRODUCT_REJECTED",
  UPDATE_PRODUCT_FULFILLED: "UPDATE_PRODUCT_FULFILLED",
  
  RESET_PRODUCT: "RESET_PRODUCT",
  SHOW_PRODUCT_FORM: "SHOW_PRODUCT_FORM"
};