export default {
  REQUEST_UNIT: "REQUEST_UNIT",
  REQUEST_UNIT_PENDING: "REQUEST_UNIT_PENDING",
  REQUEST_UNIT_REJECTED: "REQUEST_UNIT_REJECTED",
  REQUEST_UNIT_FULFILLED: "REQUEST_UNIT_FULFILLED",
  REQUEST_UNIT_RESET: "REQUEST_UNIT_RESET",
  
  ARCHIVE_UNIT: "ARCHIVE_UNIT",
  ARCHIVE_UNIT_PENDING: "ARCHIVE_UNIT_PENDING",
  ARCHIVE_UNIT_REJECTED: "ARCHIVE_UNIT_REJECTED",
  ARCHIVE_UNIT_FULFILLED: "ARCHIVE_UNIT_FULFILLED",
  
  ADD_UNIT: "ADD_UNIT",
  ADD_UNIT_PENDING: "ADD_UNIT_PENDING",
  ADD_UNIT_REJECTED: "ADD_UNIT_REJECTED",
  ADD_UNIT_FULFILLED: "ADD_UNIT_FULFILLED",
  
  UPDATE_UNIT: "UPDATE_UNIT",
  UPDATE_UNIT_PENDING: "UPDATE_UNIT_PENDING",
  UPDATE_UNIT_REJECTED: "UPDATE_UNIT_REJECTED",
  UPDATE_UNIT_FULFILLED: "UPDATE_UNIT_FULFILLED",
  
  RESET_UNIT: "RESET_UNIT",
  SHOW_UNIT_FORM: "SHOW_UNIT_FORM"
};