export default {
  REQUEST_PRODUCT_VARIANT: "REQUEST_PRODUCT_VARIANT",
  REQUEST_PRODUCT_VARIANT_PENDING: "REQUEST_PRODUCT_VARIANT_PENDING",
  REQUEST_PRODUCT_VARIANT_REJECTED: "REQUEST_PRODUCT_VARIANT_REJECTED",
  REQUEST_PRODUCT_VARIANT_FULFILLED: "REQUEST_PRODUCT_VARIANT_FULFILLED",

  CHECK_PRODUCT_VARIANT: "CHECK_PRODUCT_VARIANT",
  CHECK_PRODUCT_VARIANT_PENDING: "CHECK_PRODUCT_VARIANT_PENDING",
  CHECK_PRODUCT_VARIANT_REJECTED: "CHECK_PRODUCT_VARIANT_REJECTED",
  CHECK_PRODUCT_VARIANT_FULFILLED: "CHECK_PRODUCT_VARIANT_FULFILLED",

  CHECK_PRODUCT_ATTRIBUTE: "CHECK_PRODUCT_ATTRIBUTE",
  CHECK_PRODUCT_ATTRIBUTE_PENDING: "CHECK_PRODUCT_ATTRIBUTE_PENDING",
  CHECK_PRODUCT_ATTRIBUTE_REJECTED: "CHECK_PRODUCT_ATTRIBUTE_REJECTED",
  CHECK_PRODUCT_ATTRIBUTE_FULFILLED: "CHECK_PRODUCT_ATTRIBUTE_FULFILLED",

  CHECK_PRODUCT_ATTRIBUTE_VALUE: "CHECK_PRODUCT_ATTRIBUTE_VALUE",
  CHECK_PRODUCT_ATTRIBUTE_VALUE_PENDING: "CHECK_PRODUCT_ATTRIBUTE_VALUE_PENDING",
  CHECK_PRODUCT_ATTRIBUTE_VALUE_REJECTED: "CHECK_PRODUCT_ATTRIBUTE_VALUE_REJECTED",
  CHECK_PRODUCT_ATTRIBUTE_VALUE_FULFILLED: "CHECK_PRODUCT_ATTRIBUTE_VALUE_FULFILLED",
  
  RESET_PRODUCT_VARIANT: "RESET_PRODUCT_VARIANT"
};