export default {
  REQUEST_VARIANT_ATTRIBUTE: "REQUEST_VARIANT_ATTRIBUTE",
  REQUEST_VARIANT_ATTRIBUTE_PENDING: "REQUEST_VARIANT_ATTRIBUTE_PENDING",
  REQUEST_VARIANT_ATTRIBUTE_REJECTED: "REQUEST_VARIANT_ATTRIBUTE_REJECTED",
  REQUEST_VARIANT_ATTRIBUTE_FULFILLED: "REQUEST_VARIANT_ATTRIBUTE_FULFILLED",
  
  ARCHIVE_VARIANT_ATTRIBUTE: "ARCHIVE_VARIANT_ATTRIBUTE",
  ARCHIVE_VARIANT_ATTRIBUTE_PENDING: "ARCHIVE_VARIANT_ATTRIBUTE_PENDING",
  ARCHIVE_VARIANT_ATTRIBUTE_REJECTED: "ARCHIVE_VARIANT_ATTRIBUTE_REJECTED",
  ARCHIVE_VARIANT_ATTRIBUTE_FULFILLED: "ARCHIVE_VARIANT_ATTRIBUTE_FULFILLED",
  
  ADD_VARIANT_ATTRIBUTE: "ADD_VARIANT_ATTRIBUTE",
  ADD_VARIANT_ATTRIBUTE_PENDING: "ADD_VARIANT_ATTRIBUTE_PENDING",
  ADD_VARIANT_ATTRIBUTE_REJECTED: "ADD_VARIANT_ATTRIBUTE_REJECTED",
  ADD_VARIANT_ATTRIBUTE_FULFILLED: "ADD_VARIANT_ATTRIBUTE_FULFILLED",
  
  UPDATE_VARIANT_ATTRIBUTE: "UPDATE_VARIANT_ATTRIBUTE",
  UPDATE_VARIANT_ATTRIBUTE_PENDING: "UPDATE_VARIANT_ATTRIBUTE_PENDING",
  UPDATE_VARIANT_ATTRIBUTE_REJECTED: "UPDATE_VARIANT_ATTRIBUTE_REJECTED",
  UPDATE_VARIANT_ATTRIBUTE_FULFILLED: "UPDATE_VARIANT_ATTRIBUTE_FULFILLED",
  
  RESET_VARIANT_ATTRIBUTE: "RESET_VARIANT_ATTRIBUTE",
  SHOW_VARIANT_ATTRIBUTE_FORM: "SHOW_VARIANT_ATTRIBUTE_FORM"
};