export default {
  DISCOUNT_TYPE: {
    PERCENTAGE: 0,
    AMOUNT: 1,
    EACH_ITEM: 2
  },
  LOCAL_SCHEMA: {
    LOCATION: "LOCATION"
  },
  PARK_RECEIPT: "PARK_RECEIPT",
  CURRENT_RECEIPT: "CURRENT_RECEIPT",
  TRANSACTION_TYPE: {
    PRE_ORDER: 0,
    INVOICE: 1,
    RECEIPT: 2,
    CREDIT_NOTE: 3,
    RETURN: 4
  },
  TRANSACTION_STATUS: {
    OPEN: 0,
    OVERDUE: 1,
    PAID: 2,
    CREDIT: 4,
    CLOSED: 5
  },
  TRANSACTION_STEP: {
    PROCESS: 1,
    VOID: 2,
    RETURN: 3,
    COMPLETED: 4,
    IN_DELIVERY: 5,
    CREDIT: 6,
    PAID: 7
  },
  PAYMENT_METHOD_AVIALE_ON_POS: 1,
  PRODUCT_AVIALABLE_ON_SALE: 1,
  OPEN_SALE_REGISTRATION_STATUS: {
    OPEN: 1,
    CLOSED: 0
  },
  LOCATION_NOT_FOUND: 619,
  LANGUAGE_ALREADY_EXIST: 603,
  LITE_PLAN_NOT_ALLOW_CREAE_LOCATION:  628,
  PRO_PLAN_NOT_ALLOW_CREAE_LOCATION: 629,
  SERIAL_NUMBER_REQUIRE: 634,
  PAPER_SIZE: {
    A4: 1,
    THERMAL: 2,
    MINI_THERMAL: 3
  },
  CUSTOMER_CREDIT_STATUS: {
    DISABLE: 1,
    ENABLE: 2
  },
  QUOTATION_STEP: {
    DRAFT : 0,
    PROCESS : 1,
    CANCEL : 2,
    COMPLETED : 4
  },
  QUOTATION_STEP_COLOR: {
    DRAFT: "#FAAD14",
    PROCESS: "#2db7f5",
    CANCEL: "#2DB7F5",
    COMPLETE: "#5BC726"
  }
};