export default {
  DISCOUNT_TYPE: {
    PERCENTAGE: 0,
    AMOUNT: 1,
    EACH_ITEM: 2
  },
  PARK_RECEIPT: "PARK_RECEIPT",
  CURRENT_RECEIPT: "CURRENT_RECEIPT",
  TRANSACTION_TYPE: {
    PRE_ORDER: 0,
    INVOICE: 1,
    RECEIPT: 2,
    CREDIT_NOTE: 3,
    RETURN: 4
  },
  TRANSACTION_STATUS: {
    OPEN: 0,
    OVERDUE: 1,
    PAID: 2,
    PENDING: 3
  },
  PAYMENT_METHOD_AVIALE_ON_POS: 1,
  PRODUCT_AVIALABLE_ON_SALE: 1,
  OPEN_SALE_REGISTRATION_STATUS: {
    OPEN: 1,
    CLOSED: 0
  },
  LOCATION_NOT_FOUND: 619,
  LANGUAGE_ALREADY_EXIST: 603
};