export default {
  "operation_record_title": [
    "Operation Record",
    "ការកត់ត្រាប្រតិបត្ដិការ",
    "Operation Record"
  ],

  "col_operation_record_recordfor":[
    "Record For",
    "កត់ត្រាសម្រាប់",
    "Record For"
  ],

  "operation_record_income": [
    "Income",
    "ចំណូល",
    "ဝငျငှေ"
  ],

  "input_operation_record_for": [
    "Record For",
    "កត់ត្រាសម្រាប់",
    "သည်စံချိန်တင်"
  ],
  
  "error_operation_record_name_length": [
    "Name allow from 3 to 100 character only",
    "ឈ្មោះអនុញ្ញាតតែពី 3 ទៅ 100 តួប៉ុណ្ណោះ",
    "သာ 3 ရေ 100 မှဇာတ်ကောင်ကနေခွင့်ပြုပါအမည်ပြောပါ"
  ],

  "text_warning_delete_system_record": [
    "We don't allow to delete record generate by system",
    "We don't allow to delete record generate by system",
    "We don't allow to delete record generate by system"
  ],

  "text_generated_by": [
    "Generated By",
    "បានបង្កើតដោយ",
    "Generated By"
  ],

  "error_require_amount": [
    "Enter amount",
    "Enter amount",
    "Enter amount"
  ]
};
