export default {
  REQUEST_PURCHASE_ORDER: "REQUEST_PURCHASE_ORDER",
  REQUEST_PURCHASE_ORDER_PENDING: "REQUEST_PURCHASE_ORDER_PENDING",
  REQUEST_PURCHASE_ORDER_REJECTED: "REQUEST_PURCHASE_ORDER_REJECTED",
  REQUEST_PURCHASE_ORDER_FULFILLED: "REQUEST_PURCHASE_ORDER_FULFILLED",

  ARCHIVE_PURCHASE_ORDER: "ARCHIVE_PURCHASE_ORDER",
  ARCHIVE_PURCHASE_ORDER_PENDING: "ARCHIVE_PURCHASE_ORDER_PENDING",
  ARCHIVE_PURCHASE_ORDER_REJECTED: "ARCHIVE_PURCHASE_ORDER_REJECTED",
  ARCHIVE_PURCHASE_ORDER_FULFILLED: "ARCHIVE_PURCHASE_ORDER_FULFILLED",

  ADD_PURCHASE_ORDER: "ADD_PURCHASE_ORDER",
  ADD_PURCHASE_ORDER_PENDING: "ADD_PURCHASE_ORDER_PENDING",
  ADD_PURCHASE_ORDER_REJECTED: "ADD_PURCHASE_ORDER_REJECTED",
  ADD_PURCHASE_ORDER_FULFILLED: "ADD_PURCHASE_ORDER_FULFILLED",

  UPDATE_PURCHASE_ORDER: "UPDATE_PURCHASE_ORDER",
  UPDATE_PURCHASE_ORDER_PENDING: "UPDATE_PURCHASE_ORDER_PENDING",
  UPDATE_PURCHASE_ORDER_REJECTED: "UPDATE_PURCHASE_ORDER_REJECTED",
  UPDATE_PURCHASE_ORDER_FULFILLED: "UPDATE_PURCHASE_ORDER_FULFILLED",

  REQUEST_PURCHASE_ORDER_NUMBER: "REQUEST_PURCHASE_ORDER_NUMBER",
  REQUEST_PURCHASE_ORDER_NUMBER_PENDING: "REQUEST_PURCHASE_ORDER_NUMBER_PENDING",
  REQUEST_PURCHASE_ORDER_NUMBER_REJECTED: "REQUEST_PURCHASE_ORDER_NUMBER_REJECTED",
  REQUEST_PURCHASE_ORDER_NUMBER_FULFILLED: "REQUEST_PURCHASE_ORDER_NUMBER_FULFILLED",
  
  
  RESET_PURCHASE_ORDER: "RESET_PURCHASE_ORDER",
  SHOW_PURCHASE_ORDER_FORM: "SHOW_PURCHASE_ORDER_FORM",

  RESET_SHOW_FORM_EMAIL_PURCHASE_ORDER: "RESET_SHOW_FORM_EMAIL_PURCHASE_ORDER",
  SHOW_EMAIL_FORM_PURCHASE_ORDER: "SHOW_EMAIL_FORM_PURCHASE_ORDER"

};