export default {
  REQUEST_RECEIVE_PURCHASE: "REQUEST_RECEIVE_PURCHASE",
  REQUEST_RECEIVE_PURCHASE_PENDING: "REQUEST_RECEIVE_PURCHASE_PENDING",
  REQUEST_RECEIVE_PURCHASE_REJECTED: "REQUEST_RECEIVE_PURCHASE_REJECTED",
  REQUEST_RECEIVE_PURCHASE_FULFILLED: "REQUEST_RECEIVE_PURCHASE_FULFILLED",
  
  ARCHIVE_RECEIVE_PURCHASE: "ARCHIVE_RECEIVE_PURCHASE",
  ARCHIVE_RECEIVE_PURCHASE_PENDING: "ARCHIVE_RECEIVE_PURCHASE_PENDING",
  ARCHIVE_RECEIVE_PURCHASE_REJECTED: "ARCHIVE_RECEIVE_PURCHASE_REJECTED",
  ARCHIVE_RECEIVE_PURCHASE_FULFILLED: "ARCHIVE_RECEIVE_PURCHASE_FULFILLED",
  
  ADD_RECEIVE_PURCHASE: "ADD_RECEIVE_PURCHASE",
  ADD_RECEIVE_PURCHASE_PENDING: "ADD_RECEIVE_PURCHASE_PENDING",
  ADD_RECEIVE_PURCHASE_REJECTED: "ADD_RECEIVE_PURCHASE_REJECTED",
  ADD_RECEIVE_PURCHASE_FULFILLED: "ADD_RECEIVE_PURCHASE_FULFILLED",
  
  UPDATE_RECEIVE_PURCHASE: "UPDATE_RECEIVE_PURCHASE",
  UPDATE_RECEIVE_PURCHASE_PENDING: "UPDATE_RECEIVE_PURCHASE_PENDING",
  UPDATE_RECEIVE_PURCHASE_REJECTED: "UPDATE_RECEIVE_PURCHASE_REJECTED",
  UPDATE_RECEIVE_PURCHASE_FULFILLED: "UPDATE_RECEIVE_PURCHASE_FULFILLED",
  
  RESET_RECEIVE_PURCHASE: "RESET_RECEIVE_PURCHASE",
  SHOW_RECEIVE_PURCHASE_FORM: "SHOW_RECEIVE_PURCHASE_FORM"
};