export default {
  REQUEST_REORDER_POINT: "REQUEST_REORDER_POINT",
  REQUEST_REORDER_POINT_PENDING: "REQUEST_REORDER_POINT_PENDING",
  REQUEST_REORDER_POINT_REJECTED: "REQUEST_REORDER_POINT_REJECTED",
  REQUEST_REORDER_POINT_FULFILLED: "REQUEST_REORDER_POINT_FULFILLED",
  
  ARCHIVE_REORDER_POINT: "ARCHIVE_REORDER_POINT",
  ARCHIVE_REORDER_POINT_PENDING: "ARCHIVE_REORDER_POINT_PENDING",
  ARCHIVE_REORDER_POINT_REJECTED: "ARCHIVE_REORDER_POINT_REJECTED",
  ARCHIVE_REORDER_POINT_FULFILLED: "ARCHIVE_REORDER_POINT_FULFILLED",
  
  ADD_REORDER_POINT: "ADD_REORDER_POINT",
  ADD_REORDER_POINT_PENDING: "ADD_REORDER_POINT_PENDING",
  ADD_REORDER_POINT_REJECTED: "ADD_REORDER_POINT_REJECTED",
  ADD_REORDER_POINT_FULFILLED: "ADD_REORDER_POINT_FULFILLED",
  
  UPDATE_REORDER_POINT: "UPDATE_REORDER_POINT",
  UPDATE_REORDER_POINT_PENDING: "UPDATE_REORDER_POINT_PENDING",
  UPDATE_REORDER_POINT_REJECTED: "UPDATE_REORDER_POINT_REJECTED",
  UPDATE_REORDER_POINT_FULFILLED: "UPDATE_REORDER_POINT_FULFILLED",
  
  RESET_REORDER_POINT: "RESET_REORDER_POINT",
  SHOW_REORDER_POINT_FORM: "SHOW_REORDER_POINT_FORM"
};