export default {
  REQUEST_RETURN_PURCHASE: "REQUEST_RETURN_PURCHASE",
  REQUEST_RETURN_PURCHASE_PENDING: "REQUEST_RETURN_PURCHASE_PENDING",
  REQUEST_RETURN_PURCHASE_REJECTED: "REQUEST_RETURN_PURCHASE_REJECTED",
  REQUEST_RETURN_PURCHASE_FULFILLED: "REQUEST_RETURN_PURCHASE_FULFILLED",
  
  ARCHIVE_RETURN_PURCHASE: "ARCHIVE_RETURN_PURCHASE",
  ARCHIVE_RETURN_PURCHASE_PENDING: "ARCHIVE_RETURN_PURCHASE_PENDING",
  ARCHIVE_RETURN_PURCHASE_REJECTED: "ARCHIVE_RETURN_PURCHASE_REJECTED",
  ARCHIVE_RETURN_PURCHASE_FULFILLED: "ARCHIVE_RETURN_PURCHASE_FULFILLED",
  
  ADD_RETURN_PURCHASE: "ADD_RETURN_PURCHASE",
  ADD_RETURN_PURCHASE_PENDING: "ADD_RETURN_PURCHASE_PENDING",
  ADD_RETURN_PURCHASE_REJECTED: "ADD_RETURN_PURCHASE_REJECTED",
  ADD_RETURN_PURCHASE_FULFILLED: "ADD_RETURN_PURCHASE_FULFILLED",
  
  UPDATE_RETURN_PURCHASE: "UPDATE_RETURN_PURCHASE",
  UPDATE_RETURN_PURCHASE_PENDING: "UPDATE_RETURN_PURCHASE_PENDING",
  UPDATE_RETURN_PURCHASE_REJECTED: "UPDATE_RETURN_PURCHASE_REJECTED",
  UPDATE_RETURN_PURCHASE_FULFILLED: "UPDATE_RETURN_PURCHASE_FULFILLED",
  
  RESET_RETURN_PURCHASE: "RESET_RETURN_PURCHASE",
  SHOW_RETURN_PURCHASE_FORM: "SHOW_RETURN_PURCHASE_FORM"
};