export default {
  REQUEST_STOCK_TRANSFER: "REQUEST_STOCK_TRANSFER",
  REQUEST_STOCK_TRANSFER_PENDING: "REQUEST_STOCK_TRANSFER_PENDING",
  REQUEST_STOCK_TRANSFER_REJECTED: "REQUEST_STOCK_TRANSFER_REJECTED",
  REQUEST_STOCK_TRANSFER_FULFILLED: "REQUEST_STOCK_TRANSFER_FULFILLED",
  
  ARCHIVE_STOCK_TRANSFER: "ARCHIVE_STOCK_TRANSFER",
  ARCHIVE_STOCK_TRANSFER_PENDING: "ARCHIVE_STOCK_TRANSFER_PENDING",
  ARCHIVE_STOCK_TRANSFER_REJECTED: "ARCHIVE_STOCK_TRANSFER_REJECTED",
  ARCHIVE_STOCK_TRANSFER_FULFILLED: "ARCHIVE_STOCK_TRANSFER_FULFILLED",
  
  ADD_STOCK_TRANSFER: "ADD_STOCK_TRANSFER",
  ADD_STOCK_TRANSFER_PENDING: "ADD_STOCK_TRANSFER_PENDING",
  ADD_STOCK_TRANSFER_REJECTED: "ADD_STOCK_TRANSFER_REJECTED",
  ADD_STOCK_TRANSFER_FULFILLED: "ADD_STOCK_TRANSFER_FULFILLED",
  
  UPDATE_STOCK_TRANSFER: "UPDATE_STOCK_TRANSFER",
  UPDATE_STOCK_TRANSFER_PENDING: "UPDATE_STOCK_TRANSFER_PENDING",
  UPDATE_STOCK_TRANSFER_REJECTED: "UPDATE_STOCK_TRANSFER_REJECTED",
  UPDATE_STOCK_TRANSFER_FULFILLED: "UPDATE_STOCK_TRANSFER_FULFILLED",
  
  RESET_STOCK_TRANSFER: "RESET_STOCK_TRANSFER",
  RESET_REQUEST_STOCK_TRANSFER: "RESET_REQUEST_STOCK_TRANSFER",
  RESET_ADD_STOCK_TRANSFER: "RESET_ADD_STOCK_TRANSFER",
  SHOW_STOCK_TRANSFER_FORM: "SHOW_STOCK_TRANSFER_FORM"
};