export default {
  REQUEST_STOCK_TRANSFER: "REQUEST_STOCK_TRANSFER",
  REQUEST_STOCK_TRANSFER_PENDING: "REQUEST_STOCK_TRANSFER_PENDING",
  REQUEST_STOCK_TRANSFER_REJECTED: "REQUEST_STOCK_TRANSFER_REJECTED",
  REQUEST_STOCK_TRANSFER_FULFILLED: "REQUEST_STOCK_TRANSFER_FULFILLED",

  REQUEST_STOCK_TRANSFER_DETAIL: "REQUEST_STOCK_TRANSFER_DETAIL",
  REQUEST_STOCK_TRANSFER_DETAIL_PENDING: "REQUEST_STOCK_TRANSFER_DETAIL_PENDING",
  REQUEST_STOCK_TRANSFER_DETAIL_REJECTED: "REQUEST_STOCK_TRANSFER_DETAIL_REJECTED",
  REQUEST_STOCK_TRANSFER_DETAIL_FULFILLED: "REQUEST_STOCK_TRANSFER_DETAIL_FULFILLED",
  
  ARCHIVE_STOCK_TRANSFER: "ARCHIVE_STOCK_TRANSFER",
  ARCHIVE_STOCK_TRANSFER_PENDING: "ARCHIVE_STOCK_TRANSFER_PENDING",
  ARCHIVE_STOCK_TRANSFER_REJECTED: "ARCHIVE_STOCK_TRANSFER_REJECTED",
  ARCHIVE_STOCK_TRANSFER_FULFILLED: "ARCHIVE_STOCK_TRANSFER_FULFILLED",
  
  ADD_STOCK_TRANSFER: "ADD_STOCK_TRANSFER",
  ADD_STOCK_TRANSFER_PENDING: "ADD_STOCK_TRANSFER_PENDING",
  ADD_STOCK_TRANSFER_REJECTED: "ADD_STOCK_TRANSFER_REJECTED",
  ADD_STOCK_TRANSFER_FULFILLED: "ADD_STOCK_TRANSFER_FULFILLED",
  
  UPDATE_STOCK_TRANSFER: "UPDATE_STOCK_TRANSFER",
  UPDATE_STOCK_TRANSFER_PENDING: "UPDATE_STOCK_TRANSFER_PENDING",
  UPDATE_STOCK_TRANSFER_REJECTED: "UPDATE_STOCK_TRANSFER_REJECTED",
  UPDATE_STOCK_TRANSFER_FULFILLED: "UPDATE_STOCK_TRANSFER_FULFILLED",

  APPROVE_STOCK_TRANSFER: "APPROVE_STOCK_TRANSFER",
  APPROVE_STOCK_TRANSFER_PENDING: "APPROVE_STOCK_TRANSFER_PENDING",
  APPROVE_STOCK_TRANSFER_REJECTED: "APPROVE_STOCK_TRANSFER_REJECTED",
  APPROVE_STOCK_TRANSFER_FULFILLED: "APPROVE_STOCK_TRANSFER_FULFILLED",
  RESET_APPROVE_STOCK_TRANSFER: "RESET_APPROVE_STOCK_TRANSFER",

  CANCEL_STOCK_TRANSFER: "CANCEL_STOCK_TRANSFER",
  CANCEL_STOCK_TRANSFER_PENDING: "CANCEL_STOCK_TRANSFER_PENDING",
  CANCEL_STOCK_TRANSFER_REJECTED: "CANCEL_STOCK_TRANSFER_REJECTED",
  CANCEL_STOCK_TRANSFER_FULFILLED: "CANCEL_STOCK_TRANSFER_FULFILLED",
  RESET_CANCEL_STOCK_TRANSFER: "RESET_CANCEL_STOCK_TRANSFER",
  
  RESET_STOCK_TRANSFER: "RESET_STOCK_TRANSFER",
  RESET_REQUEST_STOCK_TRANSFER: "RESET_REQUEST_STOCK_TRANSFER",
  REQUEST_STOCK_TRANSFER_DETAIL_FULL_RESET: "REQUEST_STOCK_TRANSFER_DETAIL_FULL_RESET",
  REQUEST_STOCK_TRANSFER_DETAIL_RESET: "REQUEST_STOCK_TRANSFER_DETAIL_RESET",
  RESET_ADD_STOCK_TRANSFER: "RESET_ADD_STOCK_TRANSFER",
  RESET_ADD_PARTIAL_STOCK_TRANSFER: "RESET_ADD_PARTIAL_STOCK_TRANSFER",
  RESET_UPDATE_STOCK_TRANSFER: "RESET_UPDATE_STOCK_TRANSFER",
  RESET_UPDATE_PARTIAL_STOCK_TRANSFER: "RESET_UPDATE_PARTIAL_STOCK_TRANSFER",
  SHOW_STOCK_TRANSFER_FORM: "SHOW_STOCK_TRANSFER_FORM"
};