export default {
  REQUEST_STOCK_MANAGEMENT: "REQUEST_STOCK_MANAGEMENT",
  REQUEST_STOCK_MANAGEMENT_PENDING: "REQUEST_STOCK_MANAGEMENT_PENDING",
  REQUEST_STOCK_MANAGEMENT_REJECTED: "REQUEST_STOCK_MANAGEMENT_REJECTED",
  REQUEST_STOCK_MANAGEMENT_FULFILLED: "REQUEST_STOCK_MANAGEMENT_FULFILLED",
  
  ARCHIVE_STOCK_MANAGEMENT: "ARCHIVE_STOCK_MANAGEMENT",
  ARCHIVE_STOCK_MANAGEMENT_PENDING: "ARCHIVE_STOCK_MANAGEMENT_PENDING",
  ARCHIVE_STOCK_MANAGEMENT_REJECTED: "ARCHIVE_STOCK_MANAGEMENT_REJECTED",
  ARCHIVE_STOCK_MANAGEMENT_FULFILLED: "ARCHIVE_STOCK_MANAGEMENT_FULFILLED",
  
  ADD_STOCK_MANAGEMENT: "ADD_STOCK_MANAGEMENT",
  ADD_STOCK_MANAGEMENT_PENDING: "ADD_STOCK_MANAGEMENT_PENDING",
  ADD_STOCK_MANAGEMENT_REJECTED: "ADD_STOCK_MANAGEMENT_REJECTED",
  ADD_STOCK_MANAGEMENT_FULFILLED: "ADD_STOCK_MANAGEMENT_FULFILLED",
  
  UPDATE_STOCK_MANAGEMENT: "UPDATE_STOCK_MANAGEMENT",
  UPDATE_STOCK_MANAGEMENT_PENDING: "UPDATE_STOCK_MANAGEMENT_PENDING",
  UPDATE_STOCK_MANAGEMENT_REJECTED: "UPDATE_STOCK_MANAGEMENT_REJECTED",
  UPDATE_STOCK_MANAGEMENT_FULFILLED: "UPDATE_STOCK_MANAGEMENT_FULFILLED",
  
  RESET_STOCK_MANAGEMENT: "RESET_STOCK_MANAGEMENT",
  SHOW_STOCK_MANAGEMENT_FORM: "SHOW_STOCK_MANAGEMENT_FORM"
};