export default {
  REQUEST_SUPPLIER: "REQUEST_SUPPLIER",
  REQUEST_SUPPLIER_PENDING: "REQUEST_SUPPLIER_PENDING",
  REQUEST_SUPPLIER_REJECTED: "REQUEST_SUPPLIER_REJECTED",
  REQUEST_SUPPLIER_FULFILLED: "REQUEST_SUPPLIER_FULFILLED",
  
  ARCHIVE_SUPPLIER: "ARCHIVE_SUPPLIER",
  ARCHIVE_SUPPLIER_PENDING: "ARCHIVE_SUPPLIER_PENDING",
  ARCHIVE_SUPPLIER_REJECTED: "ARCHIVE_SUPPLIER_REJECTED",
  ARCHIVE_SUPPLIER_FULFILLED: "ARCHIVE_SUPPLIER_FULFILLED",
  
  ADD_SUPPLIER: "ADD_SUPPLIER",
  ADD_SUPPLIER_PENDING: "ADD_SUPPLIER_PENDING",
  ADD_SUPPLIER_REJECTED: "ADD_SUPPLIER_REJECTED",
  ADD_SUPPLIER_FULFILLED: "ADD_SUPPLIER_FULFILLED",
  
  UPDATE_SUPPLIER: "UPDATE_SUPPLIER",
  UPDATE_SUPPLIER_PENDING: "UPDATE_SUPPLIER_PENDING",
  UPDATE_SUPPLIER_REJECTED: "UPDATE_SUPPLIER_REJECTED",
  UPDATE_SUPPLIER_FULFILLED: "UPDATE_SUPPLIER_FULFILLED",
  
  RESET_SUPPLIER: "RESET_SUPPLIER",
  SHOW_SUPPLIER_FORM: "SHOW_SUPPLIER_FORM"
};