export default {
   REQUEST_CATEGORY: "REQUEST_CATEGORY",
   REQUEST_CATEGORY_PENDING: "REQUEST_CATEGORY_PENDING",
   REQUEST_CATEGORY_REJECTED: "REQUEST_CATEGORY_REJECTED",
   REQUEST_CATEGORY_FULFILLED: "REQUEST_CATEGORY_FULFILLED",
   
   ARCHIVE_CATEGORY: "ARCHIVE_CATEGORY",
   ARCHIVE_CATEGORY_PENDING: "ARCHIVE_CATEGORY_PENDING",
   ARCHIVE_CATEGORY_REJECTED: "ARCHIVE_CATEGORY_REJECTED",
   ARCHIVE_CATEGORY_FULFILLED: "ARCHIVE_CATEGORY_FULFILLED",
   
   ADD_CATEGORY: "ADD_CATEGORY",
   ADD_CATEGORY_PENDING: "ADD_CATEGORY_PENDING",
   ADD_CATEGORY_REJECTED: "ADD_CATEGORY_REJECTED",
   ADD_CATEGORY_FULFILLED: "ADD_CATEGORY_FULFILLED",
   
   UPDATE_CATEGORY: "UPDATE_CATEGORY",
   UPDATE_CATEGORY_PENDING: "UPDATE_CATEGORY_PENDING",
   UPDATE_CATEGORY_REJECTED: "UPDATE_CATEGORY_REJECTED",
   UPDATE_CATEGORY_FULFILLED: "UPDATE_CATEGORY_FULFILLED",
 
   DETAIL_CATEGORY: "DETAIL_CATEGORY",
   DETAIL_CATEGORY_PENDING: "DETAIL_CATEGORY_PENDING",
   DETAIL_CATEGORY_REJECTED: "DETAIL_CATEGORY_REJECTED",
   DETAIL_CATEGORY_FULFILLED: "DETAIL_CATEGORY_FULFILLED",
   RESET_DETAIL_CATEGORY: "RESET_DETAIL_CATEGORY",
   
   RESET_CATEGORY: "RESET_CATEGORY",
   SHOW_CATEGORY_FORM: "SHOW_CATEGORY_FORM"
 };