export default {
  REQUEST_INCOME_EXPENSE_CATEGORY: "REQUEST_INCOME_EXPENSE_CATEGORY",
  REQUEST_INCOME_EXPENSE_CATEGORY_PENDING: "REQUEST_INCOME_EXPENSE_CATEGORY_PENDING",
  REQUEST_INCOME_EXPENSE_CATEGORY_REJECTED: "REQUEST_INCOME_EXPENSE_CATEGORY_REJECTED",
  REQUEST_INCOME_EXPENSE_CATEGORY_FULFILLED: "REQUEST_INCOME_EXPENSE_CATEGORY_FULFILLED",
  
  ARCHIVE_INCOME_EXPENSE_CATEGORY: "ARCHIVE_INCOME_EXPENSE_CATEGORY",
  ARCHIVE_INCOME_EXPENSE_CATEGORY_PENDING: "ARCHIVE_INCOME_EXPENSE_CATEGORY_PENDING",
  ARCHIVE_INCOME_EXPENSE_CATEGORY_REJECTED: "ARCHIVE_INCOME_EXPENSE_CATEGORY_REJECTED",
  ARCHIVE_INCOME_EXPENSE_CATEGORY_FULFILLED: "ARCHIVE_INCOME_EXPENSE_CATEGORY_FULFILLED",
  
  ADD_INCOME_EXPENSE_CATEGORY: "ADD_INCOME_EXPENSE_CATEGORY",
  ADD_INCOME_EXPENSE_CATEGORY_PENDING: "ADD_INCOME_EXPENSE_CATEGORY_PENDING",
  ADD_INCOME_EXPENSE_CATEGORY_REJECTED: "ADD_INCOME_EXPENSE_CATEGORY_REJECTED",
  ADD_INCOME_EXPENSE_CATEGORY_FULFILLED: "ADD_INCOME_EXPENSE_CATEGORY_FULFILLED",
  
  UPDATE_INCOME_EXPENSE_CATEGORY: "UPDATE_INCOME_EXPENSE_CATEGORY",
  UPDATE_INCOME_EXPENSE_CATEGORY_PENDING: "UPDATE_INCOME_EXPENSE_CATEGORY_PENDING",
  UPDATE_INCOME_EXPENSE_CATEGORY_REJECTED: "UPDATE_INCOME_EXPENSE_CATEGORY_REJECTED",
  UPDATE_INCOME_EXPENSE_CATEGORY_FULFILLED: "UPDATE_INCOME_EXPENSE_CATEGORY_FULFILLED",
  
  RESET_INCOME_EXPENSE_CATEGORY: "RESET_INCOME_EXPENSE_CATEGORY",
  SHOW_INCOME_EXPENSE_CATEGORY_FORM: "SHOW_INCOME_EXPENSE_CATEGORY_FORM"
};