export default {
  REQUEST_OPEN_SALE_REGISTRATION: "REQUEST_OPEN_SALE_REGISTRATION",
  REQUEST_OPEN_SALE_REGISTRATION_PENDING: "REQUEST_OPEN_SALE_REGISTRATION_PENDING",
  REQUEST_OPEN_SALE_REGISTRATION_REJECTED: "REQUEST_OPEN_SALE_REGISTRATION_REJECTED",
  REQUEST_OPEN_SALE_REGISTRATION_FULFILLED: "REQUEST_OPEN_SALE_REGISTRATION_FULFILLED",

  OPEN_SALE_REGISTRATION: "OPEN_SALE_REGISTRATION",
  OPEN_SALE_REGISTRATION_PENDING: "OPEN_SALE_REGISTRATION_PENDING",
  OPEN_SALE_REGISTRATION_REJECTED: "OPEN_SALE_REGISTRATION_REJECTED",
  OPEN_SALE_REGISTRATION_FULFILLED: "OPEN_SALE_REGISTRATION_FULFILLED",
  
  CLOSE_SALE_REGISTRATION: "CLOSE_SALE_REGISTRATION",
  CLOSE_SALE_REGISTRATION_PENDING: "CLOSE_SALE_REGISTRATION_PENDING",
  CLOSE_SALE_REGISTRATION_REJECTED: "CLOSE_SALE_REGISTRATION_REJECTED",
  CLOSE_SALE_REGISTRATION_FULFILLED: "CLOSE_SALE_REGISTRATION_FULFILLED",

  RESET_OPEN_SALE_REGISTRATION: "RESET_OPEN_SALE_REGISTRATION",
  RESET_REQUEST_OPEN_SALE_REGISTRATION: "RESET_REQUEST_OPEN_SALE_REGISTRATION", 
  SHOW_OPEN_SALE_REGISTRATION_FORM: "SHOW_PAYMENT_FORM"
};