export default {
  REQUEST_QUOTATION: "REQUEST_QUOTATION",
  REQUEST_QUOTATION_PENDING: "REQUEST_QUOTATION_PENDING",
  REQUEST_QUOTATION_REJECTED: "REQUEST_QUOTATION_REJECTED",
  REQUEST_QUOTATION_FULFILLED: "REQUEST_QUOTATION_FULFILLED",

  ARCHIVE_QUOTATION: "ARCHIVE_QUOTATION",
  ARCHIVE_QUOTATION_PENDING: "ARCHIVE_QUOTATION_PENDING",
  ARCHIVE_QUOTATION_REJECTED: "ARCHIVE_QUOTATION_REJECTED",
  ARCHIVE_QUOTATION_FULFILLED: "ARCHIVE_QUOTATION_FULFILLED",

  ADD_QUOTATION: "ADD_QUOTATION",
  ADD_QUOTATION_PENDING: "ADD_QUOTATION_PENDING",
  ADD_QUOTATION_REJECTED: "ADD_QUOTATION_REJECTED",
  ADD_QUOTATION_FULFILLED: "ADD_QUOTATION_FULFILLED",

  UPDATE_QUOTATION: "UPDATE_QUOTATION",
  UPDATE_QUOTATION_PENDING: "UPDATE_QUOTATION_PENDING",
  UPDATE_QUOTATION_REJECTED: "UPDATE_QUOTATION_REJECTED",
  UPDATE_QUOTATION_FULFILLED: "UPDATE_QUOTATION_FULFILLED",

  DETAIL_QUOTATION: "DETAIL_QUOTATION",
  DETAIL_QUOTATION_PENDING: "DETAIL_QUOTATION_PENDING",
  DETAIL_QUOTATION_REJECTED: "DETAIL_QUOTATION_REJECTED",
  DETAIL_QUOTATION_FULFILLED: "DETAIL_QUOTATION_FULFILLED",
  RESET_DETAIL_QUOTATION: "RESET_DETAIL_QUOTATION",
  PARTIAL_RESET_DETAIL_QUOTATION: "PARTIAL_RESET_DETAIL_QUOTATION",

  RESET_QUOTATION: "RESET_QUOTATION",
  RESET_ERROR_QUOTATION: "RESET_ERROR_QUOTATION",
  SHOW_QUOTATION_FORM: "SHOW_QUOTATION_FORM"
};