export default {
  REQUEST_RECEIVE_PAYMENT: "REQUEST_RECEIVE_PAYMENT",
  REQUEST_RECEIVE_PAYMENT_PENDING: "REQUEST_RECEIVE_PAYMENT_PENDING",
  REQUEST_RECEIVE_PAYMENT_REJECTED: "REQUEST_RECEIVE_PAYMENT_REJECTED",
  REQUEST_RECEIVE_PAYMENT_FULFILLED: "REQUEST_RECEIVE_PAYMENT_FULFILLED",

  ADD_RECEIVE_PAYMENT: "ADD_RECEIVE_PAYMENT",
  ADD_RECEIVE_PAYMENT_PENDING: "ADD_RECEIVE_PAYMENT_PENDING",
  ADD_RECEIVE_PAYMENT_REJECTED: "ADD_RECEIVE_PAYMENT_REJECTED",
  ADD_RECEIVE_PAYMENT_FULFILLED: "ADD_RECEIVE_PAYMENT_FULFILLED",

  UPDATE_RECEIVE_PAYMENT: "UPDATE_RECEIVE_PAYMENT",
  UPDATE_RECEIVE_PAYMENT_PENDING: "UPDATE_RECEIVE_PAYMENT_PENDING",
  UPDATE_RECEIVE_PAYMENT_REJECTED: "UPDATE_RECEIVE_PAYMENT_REJECTED",
  UPDATE_RECEIVE_PAYMENT_FULFILLED: "UPDATE_RECEIVE_PAYMENT_FULFILLED",

  DETAIL_RECEIVE_PAYMENT: "DETAIL_RECEIVE_PAYMENT",
  DETAIL_RECEIVE_PAYMENT_PENDING: "DETAIL_RECEIVE_PAYMENT_PENDING",
  DETAIL_RECEIVE_PAYMENT_REJECTED: "DETAIL_RECEIVE_PAYMENT_REJECTED",
  DETAIL_RECEIVE_PAYMENT_FULFILLED: "DETAIL_RECEIVE_PAYMENT_FULFILLED",
  RESET_DETAIL_RECEIVE_PAYMENT: "RESET_DETAIL_RECEIVE_PAYMENT",
  PARTIAL_RESET_DETAIL_RECEIVE_PAYMENT: "PARTIAL_RESET_DETAIL_RECEIVE_PAYMENT",

  RESET_RECEIVE_PAYMENT: "RESET_RECEIVE_PAYMENT",
  RESET_ERROR_RECEIVE_PAYMENT: "RESET_ERROR_RECEIVE_PAYMENT",
  SHOW_RECEIVE_PAYMENT_FORM: "SHOW_RECEIVE_PAYMENT_FORM"
};