export default {
  REQUEST_SALE_HISTORY: "REQUEST_SALE_HISTORY",
  REQUEST_SALE_HISTORY_PENDING: "REQUEST_SALE_HISTORY_PENDING",
  REQUEST_SALE_HISTORY_REJECTED: "REQUEST_SALE_HISTORY_REJECTED",
  REQUEST_SALE_HISTORY_FULFILLED: "REQUEST_SALE_HISTORY_FULFILLED",
  
  RESET_SALE_HISTORY: "RESET_SALE_HISTORY",
  SHOW_SALE_HISTORY_FORM: "SHOW_SALE_HISTORY_FORM"
};