export default {
  REQUEST_TRANSACTION: "REQUEST_TRANSACTION",
  REQUEST_TRANSACTION_PENDING: "REQUEST_TRANSACTION_PENDING",
  REQUEST_TRANSACTION_REJECTED: "REQUEST_TRANSACTION_REJECTED",
  REQUEST_TRANSACTION_FULFILLED: "REQUEST_TRANSACTION_FULFILLED",

  REQUEST_TODAY_SALE_SUMMARY: "REQUEST_TODAY_SALE_SUMMARY",
  REQUEST_TODAY_SALE_SUMMARY_PENDING: "REQUEST_TODAY_SALE_SUMMARY_PENDING",
  REQUEST_TODAY_SALE_SUMMARY_REJECTED: "REQUEST_TODAY_SALE_SUMMARY_REJECTED",
  REQUEST_TODAY_SALE_SUMMARY_FULFILLED: "REQUEST_TODAY_SALE_SUMMARY_FULFILLED",

  ADD_TRANSACTION: "ADD_TRANSACTION",
  ADD_TRANSACTION_PENDING: "ADD_TRANSACTION_PENDING",
  ADD_TRANSACTION_REJECTED: "ADD_TRANSACTION_REJECTED",
  ADD_TRANSACTION_FULFILLED: "ADD_TRANSACTION_FULFILLED",

  UPDATE_TRANSACTION: "UPDATE_TRANSACTION",
  UPDATE_TRANSACTION_PENDING: "UPDATE_TRANSACTION_PENDING",
  UPDATE_TRANSACTION_REJECTED: "UPDATE_TRANSACTION_REJECTED",
  UPDATE_TRANSACTION_FULFILLED: "UPDATE_TRANSACTION_FULFILLED",

  DETAIL_TRANSACTION: "DETAIL_TRANSACTION",
  DETAIL_TRANSACTION_PENDING: "DETAIL_TRANSACTION_PENDING",
  DETAIL_TRANSACTION_REJECTED: "DETAIL_TRANSACTION_REJECTED",
  DETAIL_TRANSACTION_FULFILLED: "DETAIL_TRANSACTION_FULFILLED",
  RESET_DETAIL_TRANSACTION: "RESET_DETAIL_TRANSACTION",
  PARTIAL_RESET_DETAIL_TRANSACTION: "PARTIAL_RESET_DETAIL_TRANSACTION",

  RETURN_TRANSACTION: "RETURN_TRANSACTION",
  RETURN_TRANSACTION_PENDING: "RETURN_TRANSACTION_PENDING",
  RETURN_TRANSACTION_REJECTED: "RETURN_TRANSACTION_REJECTED",
  RETURN_TRANSACTION_FULFILLED: "RETURN_TRANSACTION_FULFILLED",

  RESET_TRANSACTION: "RESET_TRANSACTION",
  RESET_ERROR_TRANSACTION: "RESET_ERROR_TRANSACTION",
  SHOW_PAYMENT_FORM: "SHOW_PAYMENT_FORM"
};