export default {
  REQUEST_TRANSACTION: "REQUEST_TRANSACTION",
  REQUEST_TRANSACTION_PENDING: "REQUEST_TRANSACTION_PENDING",
  REQUEST_TRANSACTION_REJECTED: "REQUEST_TRANSACTION_REJECTED",
  REQUEST_TRANSACTION_FULFILLED: "REQUEST_TRANSACTION_FULFILLED",

  ADD_TRANSACTION: "ADD_TRANSACTION",
  ADD_TRANSACTION_PENDING: "ADD_TRANSACTION_PENDING",
  ADD_TRANSACTION_REJECTED: "ADD_TRANSACTION_REJECTED",
  ADD_TRANSACTION_FULFILLED: "ADD_TRANSACTION_FULFILLED",

  UPDATE_TRANSACTION: "UPDATE_TRANSACTION",
  UPDATE_TRANSACTION_PENDING: "UPDATE_TRANSACTION_PENDING",
  UPDATE_TRANSACTION_REJECTED: "UPDATE_TRANSACTION_REJECTED",
  UPDATE_TRANSACTION_FULFILLED: "UPDATE_TRANSACTION_FULFILLED",

  RESET_TRANSACTION: "RESET_TRANSACTION",
  SHOW_PAYMENT_FORM: "SHOW_PAYMENT_FORM"
};