export default {
  ACCESS_TOKEN: "ACCESS_TOKEN",
  STORE_ACCESS_TOKEN: "STORE_ACCESS_TOKEN",
  STORE_NAME: "STORE_NAME",

  CHECK_AUTHENTICATION: "CHECK_AUTHENTICATION",
  CHECK_AUTHENTICATION_PENDING: "CHECK_AUTHENTICATION_PENDING",
  CHECK_AUTHENTICATION_REJECTED: "CHECK_AUTHENTICATION_REJECTED",
  CHECK_AUTHENTICATION_FULFILLED: "CHECK_AUTHENTICATION_FULFILLED",
};