export default {
  ACCESS_TOKEN: "ACCESS_TOKEN",
  STORE_ACCESS_TOKEN: "STORE_ACCESS_TOKEN",
  STORE_NAME: "STORE_NAME",
  SECURE_SUBDOMAIN: "secure",

  CHECK_AUTHENTICATION: "CHECK_AUTHENTICATION",
  CHECK_AUTHENTICATION_PENDING: "CHECK_AUTHENTICATION_PENDING",
  CHECK_AUTHENTICATION_REJECTED: "CHECK_AUTHENTICATION_REJECTED",
  CHECK_AUTHENTICATION_FULFILLED: "CHECK_AUTHENTICATION_FULFILLED",

  SEND_MAIL: "SEND_MAIL",
  SEND_MAIL_PENDING: "SEND_MAIL_PENDING",
  SEND_MAIL_REJECTED: "SEND_MAIL_REJECTED",
  SEND_MAIL_FULFILLED: "SEND_MAIL_FULFILLED",
  SEND_MAIL_RESET: "SEND_MAIL_RESET"
};