export default {
  ACCESS_TOKEN: "accessToken",
  STORE_ACCESS_TOKEN: "storeAccessToken",

  CHECK_AUTHENTICATION: "CHECK_AUTHENTICATION",
  CHECK_AUTHENTICATION_PENDING: "CHECK_AUTHENTICATION_PENDING",
  CHECK_AUTHENTICATION_REJECTED: "CHECK_AUTHENTICATION_REJECTED",
  CHECK_AUTHENTICATION_FULFILLED: "CHECK_AUTHENTICATION_FULFILLED",
};