export default {
  REQUEST_BUSINESS_PLAN: "REQUEST_BUSINESS_PLAN",
  REQUEST_BUSINESS_PLAN_PENDING: "REQUEST_BUSINESS_PLAN_PENDING",
  REQUEST_BUSINESS_PLAN_REJECTED: "REQUEST_BUSINESS_PLAN_REJECTED",
  REQUEST_BUSINESS_PLAN_FULFILLED: "REQUEST_BUSINESS_PLAN_FULFILLED"
};