export default {
  REQUEST_BUSINESS_TYPE: "REQUEST_BUSINESS_TYPE",
  REQUEST_BUSINESS_TYPE_PENDING: "REQUEST_BUSINESS_TYPE_PENDING",
  REQUEST_BUSINESS_TYPE_REJECTED: "REQUEST_BUSINESS_TYPE_REJECTED",
  REQUEST_BUSINESS_TYPE_FULFILLED: "REQUEST_BUSINESS_TYPE_FULFILLED"
};