export default {
  REQUEST_CLIENT: "REQUEST_CLIENT",
  REQUEST_CLIENT_PENDING: "REQUEST_CLIENT_PENDING",
  REQUEST_CLIENT_REJECTED: "REQUEST_CLIENT_REJECTED",
  REQUEST_CLIENT_FULFILLED: "REQUEST_CLIENT_FULFILLED",
  REQUEST_CLIENT_RESET: "REQUEST_CLIENT_RESET",
  
  REGISTER_CLIENT_STEP: "REGISTER_CLIENT_STEP",
  REGISTER_CLIENT: "REGISTER_CLIENT",
  REGISTER_CLIENT_PENDING: "REGISTER_CLIENT_PENDING",
  REGISTER_CLIENT_REJECTED: "REGISTER_CLIENT_REJECTED",
  REGISTER_CLIENT_FULFILLED: "REGISTER_CLIENT_FULFILLED",
  RESET_REGISTER_CLIENT: "RESET_REGISTER_CLIENT",

  CLIENT_SIGNIN: "CLIENT_SIGNIN",
  CLIENT_SIGNIN_PENDING: "CLIENT_SIGNIN_PENDING",
  CLIENT_SIGNIN_REJECTED: "CLIENT_SIGNIN_REJECTED",
  CLIENT_SIGNIN_FULFILLED: "CLIENT_SIGNIN_FULFILLED",
  CLIENT_SIGNIN_RESET: "CLIENT_SIGNIN_RESET",

  DOMAIN_SIGNIN: "DOMAIN_SIGNIN",
  DOMAIN_SIGNIN_PENDING: "DOMAIN_SIGNIN_PENDING",
  DOMAIN_SIGNIN_REJECTED: "DOMAIN_SIGNIN_REJECTED",
  DOMAIN_SIGNIN_FULFILLED: "DOMAIN_SIGNIN_FULFILLED",
  DOMAIN_SIGNIN_RESET: "DOMAIN_SIGNIN_RESET",
};