export default {
  REQUEST_CURRENCY: "REQUEST_CURRENCY",
  REQUEST_CURRENCY_PENDING: "REQUEST_CURRENCY_PENDING",
  REQUEST_CURRENCY_REJECTED: "REQUEST_CURRENCY_REJECTED",
  REQUEST_CURRENCY_FULFILLED: "REQUEST_CURRENCY_FULFILLED"
};