export default {
  SEND_MAIL: "SEND_MAIL",
  SEND_MAIL_PENDING: "SEND_MAIL_PENDING",
  SEND_MAIL_REJECTED: "SEND_MAIL_REJECTED",
  SEND_MAIL_FULFILLED: "SEND_MAIL_FULFILLED",
  SEND_MAIL_RESET: "SEND_MAIL_RESET"
};