export default {
  NOT_FOUND: 404,
  EXPIRED: 602,
  DEACTIVE: 600,
  INVALID_USER_PASSWORD: 601,
  NO_PERMISSION_ON_STORE: 604,
  NO_AUTHENTICATE_TO_STORE: 605,
  STORE_ACCESS_TOKEN_EXPIRED: 606,
  INTERNAL_SERVER_ERROR: 500,
  NETWORK_ERROR: "Network Error",
  CURRENT_PASSWORD_NOT_MATCH: 607
};