export default {
  NOT_FOUND: 404,
  BAD_REQUEST: 400,
  EXPIRED: 602,
  DEACTIVE: 600,
  INVALID_USER_PASSWORD: 601,
  NO_PERMISSION_ON_STORE: 604,
  NO_AUTHENTICATE_TO_STORE: 605,
  STORE_ACCESS_TOKEN_EXPIRED: 606,
  INTERNAL_SERVER_ERROR: 500,
  NETWORK_ERROR: "Network Error",
  CURRENT_PASSWORD_NOT_MATCH: 607,
  PO_NUMBER_ALREADY_EXIST: 611,
  STORE_NAME_EXIST: 623,
  CURRENCY_NOT_FOUND: 624,
  DEVICE_NOT_FOUND: 625,
  DEVICE_NOT_AVAILABLE: 626
};