export default {
    REQUEST_GRAPH: "REQUEST_GRAPH",
    REQUEST_GRAPH_PENDING: "REQUEST_GRAPH_PENDING",
    REQUEST_GRAPH_REJECTED: "REQUEST_GRAPH_REJECTED",
    REQUEST_GRAPH_FULFILLED: "REQUEST_GRAPH_FULFILLED",

    REQUEST_PIPE: "REQUEST_PIPE",
    REQUEST_PIPE_PENDING: "REQUEST_PIPE_PENDING",
    REQUEST_PIPE_REJECTED: "REQUEST_PIPE_REJECTED",
    REQUEST_PIPE_FULFILLED: "REQUEST_PIPE_FULFILLED",

    REQUEST_CARD_DASHBOARD: "REQUEST_CARD_DASHBOARD",
    REQUEST_CARD_DASHBOARD_PENDING: "REQUEST_CARD_DASHBOARD_PENDING",
    REQUEST_CARD_DASHBOARD_REJECTED: "REQUEST_CARD_DASHBOARD_REJECTED",
    REQUEST_CARD_DASHBOARD_FULFILLED: "REQUEST_CARD_DASHBOARD_FULFILLED"

  };