export default {
  REQUEST_LANGUAGE: "REQUEST_LANGUAGE",
  REQUEST_LANGUAGE_PENDING: "REQUEST_LANGUAGE_PENDING",
  REQUEST_LANGUAGE_REJECTED: "REQUEST_LANGUAGE_REJECTED",
  REQUEST_LANGUAGE_FULFILLED: "REQUEST_LANGUAGE_FULFILLED"
};