export default {
  REQUEST_USERS: "REQUEST_USERS",
  REQUEST_USERS_PENDING: "REQUEST_USERS_PENDING",
  REQUEST_USERS_REJECTED: "REQUEST_USERS_REJECTED",
  REQUEST_USERS_FULFILLED: "REQUEST_USERS_FULFILLED",
};