export const REQUEST_USERS            = "REQUEST_USERS";
export const REQUEST_USERS_PENDING    = "REQUEST_USERS_PENDING";
export const REQUEST_USERS_REJECTED   = "REQUEST_USERS_REJECTED";
export const REQUEST_USERS_FULFILLED  = "REQUEST_USERS_FULFILLED";
export const SELECT_SUBREDDIT         = "SELECT_SUBREDDIT";
export const INVALIDATE_SUBREDDIT     = "INVALIDATE_SUBREDDIT";